project:
  type: website
  output-dir: docs
  pre-render: recent_posts.py

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Logic Matters"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - site-news.qmd
      - icon: bluesky
        href: https://bsky.app/profile/logicmatters.bsky.socialquarto
format:
  html:
    theme: cosmo
    mainfont: "STIX Two Text, serif"
    fontsize: 1.15em
    css: styles.css

