project:
  type: website
  output-dir: docs
  pre-render: recent_posts.py

website:
  description: "Logic, philosophy of mathematics, and related topics."
  site-url: https://logicmatters.net  # you must change this appropriately for RSS feeds to work properly
  title: "Logic Matters"
  navbar:
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "IFL"
        href: ifl/index.qmd
      - text: "Gödel"
        href: igt/index.qmd
      - text: "Categories"
        href: categories/index.qmd
      - text: "Guide"
        href: tyl/index.qmd
      - text: "Archive"
        href: archive/index.qmd
      - text: "LaTeX"
        href: latex-for-logicians/index.qmd
    right:
      - text: "About"
        href: about.qmd
      - icon: bluesky
        href: https://bsky.app/profile/logicmatters.bsky.social
format:
  html:
    theme: cosmo
    mainfont: "STIX Two Text, serif"
    fontsize: 1.15em
    css: styles.css

