---
title: "Diagrams"
page-layout: article
format:
  html:
    include-before-body: _lfl-nav.html
---

**General-purpose packages for drawing diagrams**

- [pgf and TikZ ](https://ctan.org/pkg/pgf)(Till Tantau 2005–16, now The PGF/TikZ Team): a general TeX macro package for generating graphics, with a user-friendly syntax layer called TikZ.

- [XY-pic](http://www.tug.org/applications/Xy-pic/) (Kristoffer Rose and Ross Moore 1991–2013; extremely powerful and versatile: there's a chapter on this in *[The LaTeX Graphics Companion](http://www.amazon.com/exec/obidos/tg/detail/-/0201854694/qid=1089801075/sr=8-1/ref=sr_8_xs_ap_i1_xgl14/103-8930024-8299019?v=glance&s=books&n=507846)*)

**Diagrams for modal logicians**

- [A Quick TikZ Guide for Modal Logicians](http://www.actual.world/resources/tex/doc/TikZ.pdf) (Alex Kocurek, 2020)

- [Diagrams of sphere models for variably strict conditionals](https://github.com/rzach/ptolemaic-astronomy) (Richard Zach 2018)

**Commutative diagrams for  category theory**

There is a useful [Guide to commutative diagrams packages](http://www.jmilne.org/not/CDGuide.pdf) (J.S. Milne). But the headline recommendations are

- [diagrams.tex](http://www.paultaylor.eu/diagrams/) (Paul Taylor 1986--2019), classic macros: much used and usually highly rated -- though not so much by Milne -- for drawing simple or very complicated commutative diagrams for category theory.

- [tikz-cd](http://www.ctan.org/pkg/tikz-cd) (Florencio Neves, Augusto Stoffel 2012–21). This package facilitates the creation of commutative diagrams in TikZ by providing a convenient set of macros and reasonable default settings. This is what I use: but (a TikZ issue, I believe) a diagram-heavy document can be slow to generate a PDF: you might want to investigate and use the "memoize" package so that (unchanged) diagrams are not re-processed every time you re-typeset your document, considerably speeding things up.

**Other resources**

- [Tree drawing in LaTeX](http://www.essex.ac.uk/linguistics/external/clmt/latex4ling/) (from LaTeX for Linguists)

- The [semantics](http://www.ctan.org/pkg/semantic) package supplies T-diagrams and other resources.

- [Dednat](http://angg.twu.net/dednat6.html) (Eduardo Ochs, 2019) processes proofs or diagrams written without markup, using LuaLaTeX.

- [The logix package](https://ctan.org/pkg/logix) (Michael Finney 2001-2022) provides knot symbols for constructing knot diagrams.

*Checked 9 October 2024*
