---
title: "Fonts, etc."
page-layout: article
---

You can fritter away an inordinate amount of time deciding what combinations of fonts and what page layouts to use for longer documents. So read this at your peril ...!

**Enhancements to Computer Modern**

There really is a lot to be said for sticking to the tried and tested LaTeX default font family, Computer Modern. However, it does have to be acknowledged that the Type 1 Postscript implementation of the font is not entirely true to Donald Knuth’s original design, and can produce rather too light-weight a look to the printed page. Two solutions:

- The [mlmodern package](https://ctan.org/pkg/mlmodern?lang=en) aims to provide a better implementation, avoiding the spindliness of most other Type 1 versions of Computer Modern. This works with LaTeX.

- Using the default option of the [fontsetup package](https://ctan.org/pkg/fontsetup?lang=en) will provide a ‘Book’ weight version of Computer Modern, slightly heavier than the familiar default. The package also a number of other font options -- but since it is working with Unicode OpenType versions, you will need to use the XeLaTeX engine or similar.

**Other fonts?**

Of course, LaTeX (or at least its XeLaTeX etc. versions) can handle any OpenType font you want. But here we are concerned with the limited number of fonts which play nicely with suitably matching symbol fonts, of which a significant number are freely available.

- This page from TUG (the Tex Users Group) lists [LaTeX fonts with maths support](https://tug.org/FontCatalogue/mathfonts.html). Click on the individual fonts for more info.

- For additional comments, see these pages about [Choice of Type 1 fonts for typesetting Maths](https://texfaq.org/FAQ-psfchoice) and [Unicode maths using OpenType fonts](https://texfaq.org/FAQ-otf-maths).

- A now rather old survey of [free maths fonts for LaTeX](http://anorien.csc.warwick.ac.uk/mirrors/CTAN/info/Free_Math_Font_Survey/survey.pdf) is still worth consulting (Stephen Hartke, 2006).

- See also the more recent [recent LaTeX fonts](http://math.ucsd.edu/~msharpe/RecentTexFonts.pdf) (Michael Sharpe, 2014).

- NB, perhaps, [the Tex Gyre fonts](https://ctan.org/pkg/tex-gyre) which have associated maths support.

- XeTeX/LuaLaTeX users have more font options, since they they can use the Unicode fonts via the [unicode-math package](http://github.com/wspr/unicode-math), which provides a number of options. Also see again the [fontsetup package](https://ctan.org/pkg/fontsetup?lang=en).

- It is well worth looking at this page of links to a number of PDFs of a couple of chapters of [a book set in different combinations of fonts](http://empslocal.ex.ac.uk/people/staff/gv219/aofd/fonts/) (by Geoffrey Vallis).

- Finally, there is then an extensive links page [Fonts for mathematics](http://luc.devroye.org/math.html) (Luc Devroye, 2014-2024).

**A better LaTeX class for page layout**

- [The memoir class](https://www.ctan.org/tex-archive/macros/latex/contrib/memoir/?lang=en) (Peter Wilson, Lars Madsen, 2001 - 2024) is a major LaTeX add-on which is  especially useful for anyone involved in writing book-length documents, logician or not. Its very long [manual](http://www.ctan.org/tex-archive/macros/latex/contrib/memoir/memman.pdf) is full of good advice on digital typography. Here are [illustrations of some chapter styles](https://www.ctan.org/pkg/memoirchapterstyles?lang=en). Page layout becomes infinitely adjustable (which may or may not be a good thing! -- but I enjoyed using it to design the Big Red Logic Books).

*Updated 9 October 2024*
