---
title: "Categorically diverted"
date: "2026-04-19"
---

<span style="display:none">Brauss</span>


<p>Another six large-carrier bags of books have gone to Oxfam. And my tiny redecorated study is at last put together again, and -- a miracle! -- with no books in piles on the floor. Rather late in the day, it is the nicest-looking room I have ever had. The Morris paper is a real delight. A new dim-out blind works a treat, radically reducing distracting reflections in my large Apple monitor. Gemini has explained how to reassemble a better minimalist music system from kit I already had. So suitably inspired, back to work!</p>



<hr class="wp-block-separator has-alpha-channel-opacity is-style-wide"/>



<p>I didn’t at all plan this, though. I seem to be re-checking the third edition of <em>Introducing Category Theory</em> for typos and thinkos before making a hardback edition. A third of the way through, I have so far found only few (with a bit of help from claude.ai) -- and the only significant errors are now <a href="https://www.logicmatters.net/resources/pdfs/corrections_ICT3_1.pdf">listed here</a>. As I slowly proceed, however, I’m occasionally tinkering with the exposition in small ways, and also removing a few over-excited exclamation marks and such like. So there will be an updated PDF and reprint of the paperback in a few weeks, as well as the promised hardback for libraries.</p>



<p>This is displacement activity. Revising the Gödel book -- maintaining the same level of accessibility while improving some exposition and removing some handwaving -- is causing me a bit more grief than I was expecting. I am taking that slowly.</p>



<hr class="wp-block-separator has-alpha-channel-opacity is-style-wide"/>



<p>“How does it do <em>that</em>?” -- I am still amazed by Claude’s ability as a proofreading and editorial assistant (I will write more about this some time). But I am not in the least inclined to attribute mental states to the LLM I am interacting with, and it hasn’t occurred to me to get fussed about the ontological status of my “interlocutor”. <a href="https://philarchive.org/rec/CHAWWT-8">Here’s the philosopher David Chalmers tangling with the issue</a>. But I can’t get excited. </p>



<hr class="wp-block-separator has-alpha-channel-opacity is-style-wide"/>



<p>Have I mentioned how much Schubert’s piano music means to me? Have I mentioned how much I admire Elisabeth Brauß among younger pianists? Have I mentioned that, a few years ago, she gave a quite wonderful performance of Schubert’s first set of Impromptus at a Birmingham concert? I rather think I may have done! But I’ll say it again, <a href="https://www.bbc.co.uk/sounds/play/m002tm8f">because the BBC has rebroadcast that performance</a> (from 5.12.40 in). Do listen: it will make your day better.</p>

