---
title: "Incurvati's *Conceptions of Set*, revisited"
date: "2026-07-02"
---

When Luca Incurvati’s admirable *Conceptions of Set and the Foundations of Mathematics* was published by CUP in early 2020, I wrote a series of blog posts about the book. I certainly do not want to stand by everything I then said (not least because of comments I received from a number of people, including from Luca himself). So I won't archive those earlier posts. Instead, let me try to do a little better with some (shorter) chapter-by-chapter notes.

<hr>

The book's first chapter is titled ‘Concepts and conceptions’. Not that Luca wants to suggest a sharp distinction here between concept and conception. But roughly, to characterise the *concept* of set is to characterise (at least in part) what someone has to grasp if they are to count as understanding ‘set’ in the right way. But that characterisation will leave open a lot of fundamental questions about the nature of sets and about what sorts of sets there are, about how sets relate to their members, and so forth. And our answers to such questions will typically be guided by a *conception* of sets, which tells us something about what it is to be a set (a story which “someone could agree or disagree with though without being reasonably deemed not to possess the concept” of set). 

Take for example the now familiar iterative conception of sets (and 'conception' indeed seems the natural word here). You don’t have to have grasped *that* surprisingly late arrival on the scene in order to count as understanding ‘set’. I suppose that we *might* wonder about the understanding of someone who couldn't see that the iterative conception, once presented, was at least a *candidate* for an appropriate conception of the world of sets: but reasoned rejection of the now standard conception would surely not debar you from counting as talking about sets. 

Overall, the plan of the book is to consider a number of candidate conceptions of sets in addition to the iterative one, giving a rather more sympathetic hearing than usual to some of the rivals, before eventually arguing that the iterative conception remains, so to speak, the best buy.

<hr>

But what *does* belong to the core concept of set as opposed to a more elaborated conception? Luca suggests three key elements:

1. *Unity*: “A set is ... a single object, over and above its members.”
2. *Unique decomposition*: “A set has a unique decomposition” into its members.
3. *Extensionality*: The familiar criterion of identity for sets -- sets are identical if and only if they have the same members.

By the way, in talking about members here, it isn’t (I take it) being assumed that we can call on a prior, fully articulated, notion of *membership*. The notions ‘set (of)’ and ‘member (of)’ have to be elucidated in tandem -- just as e.g. ‘fusion (of)’ and ‘part (of)’ have to be elucidated in tandem.

These three aspects of the concept of set distinguish it from neighbouring ideas. (1) is needed to distinguish sets from mere pluralities -- it distinguishes the set of Gottlob, Bertrand and Kurt from those men. (2) is needed to distinguish sets from mereological fusions which can be carved into parts in arbitrarily many ways. (3) is needed to distinguish the relation between a set and its members, and the relation between an intensionally individuated property and the objects which have the property (different such properties can have the same extension, i.e. can apply to the very same objects).

<hr> 

Let’s pause over (1). In an everyday sense, we have two sets of Trollope’s Barchester Chronicles in the house. We can distinguish the two sets of six books, and count the sets -- two sets, twelve individual books. One set is particularly beautifully produced, the other was much cheaper and its books easier to read in bed. Let's agree that, if we can refer to *X*s, count *X*s, and predicate properties of *X*s, then *X*s are objects at least in a thin logical sense: so let's grant that the two sets can therefore be thought of as objects in this minimal sense. But should we think of these sets of books -- sets in a common-or-garden sense -- as additional objects “over and above” the books themselves? This hardly seems compelling.

We need a distinction here, a version of Russell's distinction between a "class as many" and a "class as one". Paul Finsler also drew the needed contrast a century ago in a lovely quote Luca which gives:

> It would surely be inconvenient if one always had to speak of many things in the plural; it is much more convenient to use the singular and speak of them as a *class*. [...] A class of things is understood as being the things themselves, while the set which contains them as its elements is a single thing, in general distinct from the things comprising it. [...] Thus a set is a genuine, individual entity. By contrast, a class is singular only by virtue of linguistic usage; in actuality, it almost always signifies a plurality.

I’d say that much common-or-garden set talk can be construed as no more than non-committal class-as-many talk, i.e. it is singular talk of pluralities. Luca cheerfully claims “if I say that the set of books on my table has two elements, you [as an English speaker] understand what I am saying”. But I rather suspect that the non-mathematician, non-philosopher (i) is going to find the talk of ‘elements’ here really a little peculiar. And as Luca would agree, (ii) humdrum talk of a set of books often falls short of referring to a class-as-one, to something over and above the books there on the table. 

There’s little to be gained, though, in spending more time wondering just how much set talk “as it occurs in everyday parlance” (as Luca puts it) really is *set* talk in Finsler’s sense, as characterised by Luca’s (1). This is a minor issue.  Rather, let’s move on to ask the key question: what is the cash value of the claim that a *set* (the real thing, not a mere class) is a “genuine [bangs the table!] individual entity” [Finsler], is “a single object, over and above its members” [Luca]?

<hr>

Surely *one* essential thought here is that sets (in the sense which contrasts with classes) are themselves objects which can be collected together to form new sets. At the most basic, starting with Gottlob, Bertrand, and Kurt, we can form the two-membered sets {Gottlob, Bertrand} and {Bertrand, Kurt}; and from those two sets we can then form another two-membered set {{Gottlob, Bertrand}, {Bertrand, Kurt}}. Someone who hasn’t grasped that sets can straightforwardly be members of other sets arguably hasn't grasped the concept of set that we are after.

Luca would agree, making the point particularly clearly when commenting on my earlier blog post. He wrote that to replace 'object' with a more colourless term like 'item' in Unity would "leave out an important aspect of Unity, which is precisely the one that serves to ensure that sets are the kinds of things that can themselves be collected together."

I would add another related, equally fundamental, thought: that subsets are the same kind of object as sets -- and hence the very same object can be both a subset (of *X*, say) and also a member of another set (e.g. of the powerset of *X*).

<hr>

A quick aside. Looking ahead, one supposed conception of sets that Luca is *not* going to discuss is that embodied in ETCS, the Elementary Theory of the Category of Sets. But this seems well-judged to me. As I argue in the last two chapters of my category theory book, ETCS just doesn't square with the conventional concept of set, rejecting extensionality as ordinarily understood, not allowing the same items to be members of one set and subsets of another, and more. This, of course, isn't to rule out ETCS as in fact supplying a more apt "foundation" for mathematics than a conventional set theory. But, say I, it is swimming in a different conceptual orbit, more akin to a type theory. Though all that is a story for another place.

<hr>



Let’s take it then that the concept of set is (at least in part) characterised by Luca’s three conditions -- Unity (a set is in some sense a unity, distinct from its members), Unique Decomposition (a set decomposes into its members in just one way), Extensionality. Which leaves more to be said. But then there are various possible views of the *role* of the further story we need, in further elaborating a conception of sets.

Suppose, for example, that you come to the view that the concept of set, as pre-theoretically grasped, is governed by the assumption that for any coherent predicate there is a set of objects which satisfy it. Then, rapidly, we get to a classically inconsistent naive set theory. Put on hold for now the option of revising your logic as a palliative. Then you’ll want to work with a classically consistent replacement concept of set*. And the further story we need is an elaboration of this replacement concept.

But put aside for now the idea that our pre-theoretical notion of set is inconsistent. How might things then go? Maybe there are a number of distinct ways of coming up with different, more refined concepts, each with clear virtues. Or it may turn out that one sharpening is particularly fruitful, mathematically speaking. [Possible model: we have a rough-and-ready concept of a computable function. This can be refined in various ways, though one direction -- giving us the notion of an effectively computable function, where we abstract from considerations of computation length or storage costs, etc. -- turns out to be particularly fruitful.] Or perhaps further reflection on our core concept of set points us in some way to there being a unique concept to analyse.

But let's not fuss too much about in advance whether we are going to find ourselves replacing, sharpening or analysing our pre-theoretic concept of set (and not fuss about demarcating the cases): rather, we want first to have some conceptions laid out to discuss and then think about what it takes to adjudicate between them.

<hr>

In this initial chapter, Luca has something to say about three such guiding thoughts. One we have already touched on, the thought that every contentful predicate has a set as extension, which lands us with *naive set theory*. Luca then gives a familiar diagnosis of what goes wrong. Say a concept is (i) indefinitely extensible if, taking any set of things which fall under *C*, there is an operation which produces a further thing which falls under *C*. Say a concept *C* is (ii) collectivising [Potter] or universal [Luca] if there is a set of everything that falls under the concept *C*. Then naive theory takes the concept of set to be both (i) indefinitely extensible and (ii) universal. And that way contradiction lies. A similar diagnosis can be given, as Luca nicely explains, for Cantor’s Paradox, the Burali-Forti Paradox, and Mirimanoff’s Paradox. So we want our developed consistent set theory to allow only one of extensibility and universality. And Luca promises to discuss theories of both kinds. And now we see that one role for a conception of sets in the sense of some guiding thoughts can be (i) to indeed guide us in one direction or the other, and (ii) also give us some initial confidence that we are going to avoid falling into paradox.

Luca at the end of his chapter discusses two more guiding thoughts, what he calls the *logical* and *combinatorial* conception of sets. A logical conception treats sets as essentially associated with some predicate, concept, or property (the naive theory involves a naive version of this thought). A combinatorial conception arguably goes back to Cantor himself -- and can be associated with images such as a sequence of random choices of what goes into the set. Thus Bernays writes that on this conception, “one views a set of integers as the result of infinitely many independent acts deciding for each number whether it should be included or excluded.” An idea which might well raise some philosophical eyebrows. Indeed, there’s a tradition that worries that standard set theory is, so to speak, conceived in sin, being an unholy alliance between a logical conception (which gives us infinite sets but not arbitrary collections) and a combinatorial conception (which -- if we take Bernays seriously -- apparently gives us finite arbitrary collections but not infinite ones unless we are going to countenance supertasks involving an infinite number of independent choices: and why, a Weyl might ask, suppose that such a fairy-story even makes sense?). 

That tradition may be quite misplaced, of course. Perhaps Bernays's image of viewing an infinite set of integers "as the result of infinitely many independent acts deciding for each number whether it should be included or excluded” should be regarded as no more than a mere façon de parler, a dramatic way of emphasising the merely negative point that on the combinatorial conception "the existence of a set does not depend on the existence of a condition satisfied by all the members or of a rule for selecting them" (to quote Luca on p. 44). Fine. But is there really no more making a conception of set a combinatorial conception than agreement on that negative point? We shall see ...
