---
title: "BML: I need a plan ..."
date: "2026-08-05"
description: "About plans for updating *Beginning Mathematical Logic*, and about a missed Oslo trip."
---

A month full of distractions, fatigue, brain fog. Great. But it *has* made one thing clear. It wouldn't be wise for the time being to embark (or continue) on a large-scale project like a new edition of the Gödel book or of my intro logic text. 

What I need are some relatively unchallenging small-scale projects. Such as revising some of the chapters of *Beginning Mathematical Logic* (which are largely independent of each other).

Since I moved Logic Matters to its new incarnation on GitHub Pages, I am getting much more helpful and reliable statistics; and the *BML* Study Guide is consistently revealed as the most downloaded PDF (shading the logic book). So updating chapters certainly won't be wasted effort, and needn't be too effortful. 

But how best to handle a rolling, chapter by occasional chapter, update of *BML*?  The cleanest plan, methinks, would be simply to withdraw the paperback once updates get going (reinstating it if and when the new version of the Guide settles again into a steady state). Then I can be relaxed about updating the PDF at intervals without worrying that work-in-progress stages have chapters of different dates/levels of polish (as long as the status of each chapter is clearly signalled).

So that's a plan. Watch this space.

<hr>

It doesn't look, then, that we will get to Oslo in the coming fortnight to meet up with The Daughter again. And to catch a concert or two from the Oslo Kammermusikkfestival. The opening concert in [the University Aula](https://www.uio.no/english/about/culture/collection/aula/) with the Edvard Munch murals looked particularly enticing -- not least because Elisabeth Brauß is playing (in Dvořák’s wonderful Piano Quintet No. 2). She gets more and more impressive: 

{{< video https://youtu.be/4tWcaTko1SE?si=CqcmyjyWhMPBjxho >}}

