---
title: "Settling in -- and a PHQ concert"
date: "2026-06-06"
---

The domain name logicmatters.net now points to this new site freely hosted on GitHub. Which was quick! It has indeed been quite a fun, fast, mildly nerdy, journey from the old WordPress site. So here are brief notes about the state of play (though sensible readers will probably want to skip straight on to the terrific new Pavel Haas Quartet video linked below). 

* As you will see, only recent blog posts (and comments) have been copied across from the old WordPress site. However, you can find some of the more interesting(?) [older posts archived here](/archive/). And I will add more to the archive when the spirit moves me -- there are only about 1850 posts from twenty years of blogging to read through again, with rather mixed feelings too.

* As you will also see, there is no longer a Wordpress-style comment system. I could set up the heavy-duty GitHub-based app, but this in fact seems wild overkill for a blog which gets only a few comments a month.  Instead, every blog post invites you to send comments by email or to discuss on Mastodon, and I’ll manually copy in any contributions of general intrest. We’ll see how that works. 

* The blog preview page gives the new RSS feed address, though I have set up a redirect on Cloudflare and so the old feed address should still work.

* I have preserved a lot of the old site's folder structure, so external links that pointed to the old site should mostly still work. When the initial dust has settled I will set up redirects for any frequently used broken links.

* As mentioned before, I did wonder about pensioning off the LaTeX for Logicians pages (dating originally from way back). But, somewhat to my surprise, Google Analytics reported that they have still in fact been getting signifcant traffic. So there is now a revised, somewhat leaner, suite of pages which may still have some use.

But no more nerdy procrastination, then: I have no excuse not to get back to revising *Beginning Mathematical Logic*.

<hr>

And now for something outstanding. At Wigmore Hall, The Pavel Haas Quartet with -- after the interval -- Boris Giltburg (piano) and Petr Ries (double bass) perform Dvorak's 'American' Quartet and Schubert's Trout Quintet. Simply wonderful perfomances.

{{< video https://www.youtube.com/watch?v=Qj2cPuj6vro&start=240
 >}}

