---
title: "Twenty years on, what next?"
date: "2026-05-23"
categories: ["This and that"]
---


<p>The Logic Matters blog started on 9 March 2006. Bother! -- I missed its twentieth birthday. Raise a belated glass, as that was a milestone of sorts.</p>

<p>I do plan to continue with the blog and website. But I am going to experiment (initially in a local sandbox) with moving from having an expensively hosted WordPress site to using a Static Site Generator like Quarto for a site freely hosted on Github. Three reasons:</p>

<ul class="wp-block-list">
<li>As I say, expense. Hosting plus various paid WordPress plug-ins for security etc. costs in the region of £400 a year. This cost is only partially met by the small royalties I get from the Logic Matters books (the prices are set at the minimum possible, just rounded up, and I’d like to continue that student-friendly policy).  </li>

<li>WordPress bloat. Managing and trouble-shooting can occasionally be annoying.</li>

<li>But mainly, future-proofing. A legacy Github website can continue to serve up Logic Matters pdfs for as long as there is any interest, without needing someone to maintain an expensive WordPress site.</li>
</ul>

<p>Predictably, after twenty years, there is a real mess behind the scenes here, and Something Ought To Be Done to tidy things up. A year or two ago I wouldn’t have wanted to devote the time and learning effort to moving to Github, wrangling with CSS, and the like. But one thing that Gemini and friends really excel at is patiently holding your hand through such nerdy tasks. So I think now could be the time at least to experiment.</p>

<hr>

::: {.hanging}
*Aron T comments:* Congrats on this twentieth anniversary. I have only been following you for less than half that time, but this site and all your work is fantastic. Thanks so much and wishing you many more productive years.

I would highly encourage you to work with an LLM in setting up a GitHub site. I did that for my personal math studies site (Julia and LaTex all around) and it saved me tons of work. Just remember to always verify/carefully check everything it suggests and builds.
:::
<p></p>
::: {.hanging}
*PS replies:* Thanks, Aron. Glad you find the site useful! 

I’m using Gemini for general guidance and hand-holding for the site rebuild, and heavily using Claude Code for the actual coding in VS Code -- which is frankly pretty amazing to a newbie. (I can say, roughly, duplicate such-and-such chunk of the existing site, making new pages, preserving links, tidying away all the Wordpress cruft, and lo and behold, off it goes and does the job, with only a few minor tweaks needed to get it right. I just can’t imagine doing this without an LLM assistant.)
:::
<p></p> 
::: {.hanging}
*Rowsety Moid comments* I’m curious about what coding Claude did and what language(s) it used.

Also, how understandable is the code.

(I’m not a fan of “coding” as a term, btw. It’s largely replaced “programming” but makes the whole thing sound like low-level clerical work.)
:::
<p></p>
::: {.hanging}
*PS replies* Claude’s coding tasks were mainly (I think) writing Python scripts to bulk process old WordPress posts, using the data to build new nice Markdown files, and otherwise to wrangle with CSS. Low level tasks no doubt, but beyond my pay grade!
:::
<p></p>
::: {.hanging}
*Aron T comments* As someone who has worked in the software technology field for over fifty years, the “coding” vs “programming” distinction you make is actually an excellent way to describe the difference between LLMs and humans. LLMs are extremely useful at taking over low-level clerical tasks from programmers. Human programmers are the thinkers, architects and designers. The increase in productivity LLMs bring is equivalent to the large increase in productivity I felt in college when I moved from punched cards to green screen terminals. The hype that LLMs will replace human programmers is just that-hype.
:::