---
title: "Philosophy of Religion 1: The ability to sin"
date: "2008-03-25"
page-layout: article
---

The first chapter of Murray and Rea's An Introduction to the Philosophy of Religion is called 'Attributes of God: independence, goodness and power'. You can get an idea of its style and content from its final paragraph:
> As the foregoing makes clear, the topic of the concept of God is a philosophically rich and fascinating one. In engaging the concept philosophically we must first decide which concept of God is salient, and then consider the various puzzles that arise for the divine attributes that follow from that concept. Our attention has been focused on the concept of God that arises from perfect-being theology. On that concept God is, among other things, self-existent (or necessarily existing), a creator and providential superintender, and perfectly good. While these attributes initially seem straightforward, more careful scrutiny shows us that interesting  puzzles lie just beneath the surface. Do these puzzles show that there is something incoherent about the concept of God found in perfect-being theology? It is not at all clear that they do. However, it is also not clear that they don't. As we have seen, resolving this question requires taking stands on controversial claims which are currently at the forefront of discussion in the field. For this reason, discussion on these topics will be vigorous and ongoing.

That is, it has to be said, rather flat-footed prose, isn't it? (How did "engaging the concept" or "on that concept God is self-existent" get past the copy editor, I wonder grumpily). And the conclusion is bathetic. I fear there might be some students readers nodding off over this.

But if the style leaves something to be desired, what about the content? Well note that, from the off, this isn't so much philosophy of religion but the philosophy of theological speculation. Some may very well ask: How many of those who have just attended Holy Week services, for example, are committed to "perfect-being theology" in anything like the sense discussed here? Why? Just how is that commitment manifested in the quotidian prayers and practices of the unreflectively pious? I don't know -- and Murray and Rea don't pause to tell us. Which seems pretty unsatisfactory, both philosophically and pedagogically. Philosophically, because the relationships between religion and the religious life, on the one hand, and theological speculation, on the other, are surely rather obscure. We should certainly be asking, for example, what does talk of God's perfect goodness mean e.g. in the thought of someone trying to live a Christian life (there is surely some hermeneutic exploration needed here). And the danger in just diving in to wrestle with theological speculation is that those students of religious inclination will just feel that somehow that this is an intellectual game that doesn't really engage with their beliefs.

OK, but given that Murray and Rea are playing the theological speculation game, how well do they do it?

So far, I'm inclined to say, it all goes a bit quickly, and in places superficially. Here's one example. They are discussing the proposition that a  being is morally praiseworthy only if it has the ability to sin. And they offer as a consideration against this proposition that we'd think someone praiseworthy who, faced with a possible occasion for killing finds homicide unthinkable (rather than finds himself genuinely torn over the issue, weighing up the pros and cons and coming down against killing in the end). But to find homicide "unthinkable" is to take the thought that A would be an act of homicide as a conclusive reason against doing A that simply silences any putative reasons for doing A. And  someone who finds homicide unthinkable in that sense (most of us, I hope!) isn't thereby rendered unable to pull the trigger -- it is not a kind of paralysis, or like an inability to lift a ton weight. But if I can still pull the trigger, exactly why I don't I count as still having the "ability to sin" here (albeit an ability I at the moment wouldn't dream of exercising)? After all, I have the ability -- don't I? -- to change my mind about what's unthinkable and so do the dastardly deed. Well, there's more to be said: but we certainly need to know a lot more about the relevant notion of ability in play here in the proposition under discussion. But Murray and Rea rush on.
