---
title: "Philosophy of Religion 2: Eternity"
date: "2008-03-27"
page-layout: article
---

The second chapter of the Murray/Rea Introduction is on "Attributes of God: eternity, knowledge and providence". It has to be said, again, that the discussion  seems to be pretty remote from engaging with the religious meaning of talk of seeking eternal life or of not being able to hide from God's knowledge, and so forth. But we'll just have to let this pass. Taking the investigations into philosophical theology on their own terms, how do they fare?

Here's an example -- a small one, but not entirely untypical perhaps. The context is talking about omniscience:

> There are set-theoretic reasons for thinking that it makes no sense to talk about "every proposition". For example, one might think that it makes sense to talk about every proposition only if there is a set of all propositions; but there are good reasons for thinking that there can't be a set of all propositions. Here's why: let P be the set of all propositions. Now consider the conjunction C of all members of P. C won't be a member of P, since no conjunction has itself as a conjunct. Thus P can't be the set of all propositions. ... Hence it looks like there is no set of all propositions; and so it looks as if we can't say things like "God believes every proposition." If this argument is sound, then, the common-sense definition of omniscience will have to be modified.

Two comments -- ignoring the point that the argument really ought to have have been directed explicitly against "God believes every true proposition". First, no indication at all is given of why one one might think that it makes sense to talk about every proposition only if there is a set of all propositions (a student might very reasonably ask why, if she wants to talk about all donkeys, she has to believe in something else as well, namely a set of donkeys). So we are actually given no reason to suppose that generalizing over propositions is illegitimate, even if there is no set of all propositions. Second, although there is indeed a plausible argument against the claim that there is a set of all propositions (the Cantorian argument exploited by Patrick Grim in his The Incomplete Universe), this isn't it. For a start, suppose you think of propositions as individuated by the set of possible worlds they are true at. Then the conjunction of (P & Q) with P and with Q is the same proposition as (P & Q) -- so a conjunction can "contain itself as a conjunct" in one perfectly good sense. If Murray and Rea don't like that entirely familiar but abstract Lewisian view of propositions, then  they had better explain  what other notion of proposition  they are working with, and then they need to explain why on their (less abstract?) account, the operation of forming infinitary conjunctions is well defined. But of course they don't.

This is rather sloppy writing and sloppy thinking, of  just the kind we are trying to get our students to avoid!

Ok, let's now take something more central. Issues about eternity and providence involve -- at least on Murray and Rea's construal -- issues about the metaphysics of time. So they talk a little about different metaphysical theories, outlining what they call "eternalism" and presentism. I doubt whether students will understand much of the two positions from the over-brisk presentation. And the level of discussion is feeble. Eternalism supposedly holds

> the familiar subjective experience of the flow of time, the transition from one moment to the next, is mere illusion. ... Likewise, eternalism leaves no room for the idea that the past is gone or that the future is open and unsettled.

Wrong both times, of course. A B-theorist like Mellor in Real Time II can and does  give an account of the subjective experience of the flow of time -- it is no illusion that we have experiences that can reasonably be so-called, and those experience are not illusory in that they  tell us nothing false about the world. And for an eternalist, of course the past is gone -- it is past, it is out of our causal reach, there is nothing we can do about it, it is over! And an eternalist doesn't have to be a determinist: he is as able to hold that the future is "open", as unsettled-by-the-present, as a presentist.

And what about the eternal? Murray and Rea really struggle with the idea the God is eternal  but atemporal (so eternal in some sense other than everlasting). How about this: "The idea underlying the doctrine of divine eternity is that God's life is sort of like an infinitely thick specious present."? Sort of like? Since when has "A is sort of like B" passed muster as an acceptable form of philosophical analysis?

And what do they mean by the "specious present"? Well, we are told that "the metaphysical present is a durationless instant, an infinitesimal moment of time" -- thereby revealing that Murray and Rea don't know what "infinitesimal" means. By constrast, our experience of the present "has some temporal thickness": when we hear a friend speak, there is a good sense in which we are conscious "all at once" of a word or phrase, even though the event we are conscious of has duration. (There is no mystery about this, of course: there is a story to be told about the output of  information-processing about such events into a short-term buffer.) And "this sort of temporarily thick experience of the present is what people refer to as the (experience of) the 'specious present'".

So the idea, is it, that while we have information available to us "all at once" (in a snapshot, so to speak) about a relatively short duration, God has information available "all at once" (in a snapshot, so to speak) about a much longer duration? But of course, just having a snap-shot experience doesn't in itself constitute any kind of life, however much information is available in that experience, or however wide its scope. For a conscious life in any ordinary sense of 'life' is constituted by temporal sequences of such experiences. But God is atemporal, it is being supposed. However, I forget: God's life is only sort of like the specious present.
