---
title: "Philosophy of Religion 3: The Trinity"
date: "2008-03-28"
page-layout: article
---

The first part of the Murray/Rea book, 'The Nature of God', has a couple of chapters on God's attributes which I've just said just a bit about: and now there's a chapter on more specifically Christian characterizations of God. I'll take Ch. 3, 'God triune and incarnate', in three bites, discussing the Trinity here first.

Just an aside first. It is always difficult to know how to organize introductory books on any area of philosophy.  As someone once put it, we need to travel over a wide field of thought criss-cross in every direction. So I fully accept that no linear order is going to be entirely  satisfactory. But I do have to say that I find something a bit odd in the Murray/Rea approach here. To get stuck into the Trinity or the mystery (or should that be Mystery, with a capital "M") of the incarnation before we've been given even the flimsiest reason for supposing that there's anything that has enough of the supposed attributes of God to count as such does seem to be going about things a bit topsy turvy. But ok, let's read on.

And in fact, the first few pages are rather a good read, because Murray and Rea acknowledge  that  the doctrine of the Trinity is a pretty rum one, on the face of it beset  with internal contradictions,  yet is central to traditional Christian doctrine. And they have no trouble trashing a number of once more-or-less popular analogies or models that are supposed to shed light on the doctrine. Things go less well when they go on to offer three more analogies that are supposed to help us out.

- (I paraphrase:) The Father, Son and Holy Spirit are like three members of a family. They are each divine, but the Godhead, i.e. the society of three persons, is the one God. Well, likewise Zeus, Hera, Athena, Apollo and company are a family. The individuals are each divine: can we then say the society of gods, the Pantheon, is the Godhead, god-as-one? Well, that doesn't sound at all right about the Greek Pantheon. And following the analogy would have us talking about The Father, Son and Holy Ghost as three gods. Murray and Rea note the worry, saying that the family analogy "pushes in the direction of polytheism". (They limply suggest that the defender of the analogy might say that the criticism requires "a serious analysis of what exactly it means to be a polytheist". But such a defender would just be missing the point. We plainly don't need any heavy duty analysis of polytheism to see that the family analogy assimilates Father, Son and Holy Ghost too closely to the Greek Pantheon in a way no traditional Trinitarian would want.)
- Just as a single human being can have multiple personalities, so too a single God can exist in three persons. The trouble with that formulation, of course, is that a personality (in the usual sense) isn't a person; so we need to say something stronger, namely that where there is a single human being there may be more than one person. And sure, some have claimed that that is possible, e.g. in the case of some commissurotomy patients (though the claim is highly contentious). But even if we accept it, it doesn't seem to help very much. For if a society of three people inhabiting three different bodies in a family relation isn't a good model of the Trinity, why is a society of three people fighting over the same body? (Murray and Rea are in fact equally suspicious. But having so far come up with two dud analogies they say "these two analogies seem to have a great deal of heuristic value". But that's cheating. An analogy that you can't make work is an analogy that doesn't work: you have to go back to drawing board, not wistfully wonder whether it might have "heuristic value", whatever that is.)
- The Father, Son and Holy Spirit are the same God but different persons in just the way that a statue and its constitutive lump are the same material object but different form-matter compounds. The trouble here is that Murray and Rea explain "are the same material object" as "share all of their matter in common". So, when the wraps are off, their idea is that the Father, Son and Holy Spirit "are the same God" in just the way that a statue and its constitutive lump share all of their matter in common. But how can that be, unless we construe "are the same God" as "share all of their spirit-stuff in common", or something like that? And of course we haven't the foggiest what that begins to mean.  Ah, say   Murray and Rea quickly, "Of course, God is not material, so this can only be an analogy." But if it isn't an analogy we come near to being able to make use of, this is just useless arm-waving.

So, as far as Murray and Rea's arguments go, the doctrine of the Trinity (as a bit of metaphysics) ends up as utterly  obscure as it was at the outset. No surprise there then. As to the question of the religious content of the doctrine, what it means in a religiously led life to walk with God and acknowledge Jesus as his Son, and so forth, all that sadly goes unexplored.

What was a surprise was an argument they report from Richard Swinburne that purports to show that there are a priori reasons -- quite independent of scripture -- for the doctrine of the Trinity. God is perfectly loving; but need not have created anything. But perfect love requires a beloved, one existing even if he didn't create anything, so this would have to be another divine person. But truly perfect love requires not only one beloved but also a third object of love -- an  additional person whom lover and beloved can cooperate together in loving. Hence the Trinity. Wow! Murray and Rea report Swinburne's argument for the delights of threesomes with a straight face (though they don't buy it). Mockery might seem a more apt response.
[And now I better take a bit of break from the Introduction to the Philosophy of Religion, and get back to talking about the terrific Shapiro/Wright paper ... But I'll no doubt not be able to resist returning to Murray and Rea soon!]
