---
title: "Philosophy of Religion 4: Lord, Liar, Lunatic"
date: "2008-03-30"
page-layout: article
---

The Murray/Rea Introduction t*o the Philosophy of Religion* contains a rather extraordinary episode at pp. 75--80 which I can't forbear from commenting on.

They consider the following argument -- they call it the "Lord-Liar-Lunatic" argument -- for believing the Jesus of Nazereth was divine. Jesus claimed to be divine. The claim is either true or false. If the latter, either Jesus knew it was false, and was a liar. "On the other hand, if he unwittingly falsely claimed to be divine, then he was crazy." But

> the influence of Jesus's teaching ... has been enormous. Literally millions of people have found peace, sanity and virtue in orienting their lives round his teachings. ... All of these facts together make it seem very likely that Jesus was neither so wicked and egomaniacal as to try deliberately to deceive others into thinking that he was divine, nor so mentally unbalanced as to be fundamentally confused about his own origin, powers and identity. If Jesus was not a liar or a lunatic ... then there is only one alternative left: his claim to divinity was true.

Which really is a quite jaw-droppingly awful argument. Suppose we grant that Jesus claimed himself to be divine (I thought that was contended by many biblical scholars, but let it pass). And suppose he did so sincerely even though he wasn't divine. Then he was badly deluded. But what on earth is the problem with that? History is full of people suffering from "crazy" delusions but functioning very successful in many domains of life.

Murray and Rea argue, in effect, that you can't be "sane" and so deluded as to believe yourself divine when you aren't (it isn't, they argue, the sort of thing you can make a straight mistake about, at least if "divine" is used in the "perfect being" sense). OK: for the sake of argument, let's agree with Murray and Rea: if Jesus was not divine, he was not fully "sane". But -- to repeat -- that of course is entirely compatible with e.g. being an inspirational moral teacher. Bad cognitive mulfunction in one area is compatible with managing spectacularly well in other areas.

Another related point. Suppose a world of many messianic preachers, all deluded as to their own divinity (well, there's been a fair bit of it around over the centuries -- it's a mental virus that can infect people, it seems). Most preach a variety of messages that fall on stony ground. Some preach messages that "catch on" temporarily, but in a quite horribly destructive way. But one, let's suppose, picking up on ideas already in the air, charismatically preaches in a way that strikes a chord with his contemporary listeners; the message is taken up and propagated; and this time, let's suppose "millions of people [find] peace, sanity and virtue in orienting their lives round his teachings". But the fact that one such preacher happens to initiate a benignly propagating message [if that's what we think Christianity is -- of course, that's the subject of a different argument!] isn't any evidence at all that his pretensions to be divine are any less deluded that those of his colleagues. Given enough different shots at it, and our apparent human propensities to be caught up by religious ideas, one deluded preacher was more or less bound to strike lucky.

Murray and Rea write that "the Lord-Liar-Lunatic argument seems to us ... to be stronger than some contemporary critics have given it credit for being". I do find that an astonishing thing to say. The argument is quite transparently hopeless.
