---
title: "Philosophy of Religion 5: Incarnation"
date: "2008-03-31"
page-layout: article
---

The concluding part of Chapter 3 of Michael Murray and Michael Rea's An Introduction to the Philosophy of Religion concerns the incarnation. Just two very quick comments on these pages, one on how the authors approach the issue, and one on their final shot at a supposedly helpful analogy.

Murray and Rea kick off by quoting from at length from the Chalcedonian Creed of AD451, which propounds a doctrine of the incarnation, in effect by contrasting the "correct" view with various possible heretical interpretations. But the creed does seem -- unsurprisingly -- to be shot through with relics of philosophical views of the time. A student reader might very reasonably ask: why should we take a document that seems to be coloured by the metaphysics of the day as authoritative in shaping our understanding of what we might now mean by talking, say, of Jesus as our Lord? Different believers at different times (or at least, those with a taste for philosophizing about it) will no doubt interpret their religion in the light of the philosophical fashions of the day. Why give any special weight to the intellectual fashions of the fifth century? 

The student's worry here has, it seems to me, some real force.  And Murray and Rea don't really address such worries. They do talk of Christianity as a 'doctrinal religion', and argue that "a proper assessment of Christianity will require attention to a proper understanding of the core doctrines". But it will probably be very unclear even to a believing student why understanding the religious doctrines of the gospels is best done via a later credal gloss which is then to be interpreted rather on the model of trying to make sense of an ancient metaphysics text.  I suspect that Murray and Rea are in danger of losing their audience here.

But be that as it may. Let's briefly consider their own best shot at understanding how it might make sense to speak of Jesus as being one person but as having both a human mind (that can, as scripture tells us, grow in wisdom and suffer temptation) and a divine mind. "Suppose," they say, "we think that the human mind and the divine mind are related in a way similar to the way in which a person's conscious mind is said to relate to her 'subconscious' mind."

Well, the contents of Joan's subconscious mental processing are not routinely present to her consciousness (though some of them may be available). But equally, of course, they aren't present to any other consciousness. There's just one centre of consciousness here! But presumably, in the case of Jesus's divine mind, that is a centre of consciousness (if we understand anything at all about the divine mind!). So what is going on here, according to the model, is that we have two centres of consciousness but with only the kind of partial access within Jesus from the human to the divine mind that we have within Joan from the conscious to the subconscious part of her mind. But that now sounds just like two (albeit imperfectly communicating) persons associated with Jesus -- in the way there are two persons imperfectly communicating in a commissurotomy patient, according to Murray and Rea. Why isn't that exactly the Nestorian "two person" heresy that they were struggling to avoid?
