---
title: "Philosophy of Religion 7: Religious experience"
date: "2008-04-02"
page-layout: article
---

I'm finding myself blogging about the Murray/Rea book in more detail than I ever intended: and having got into my stride, I really ought to go back to say more about the first chapter about which I have so far said very little here. Ok, I might do that in due course, especially if I get round to organizing these comments into a single document. But for the moment, let me just press on talking about Chapter 4, this time picking up on some of their remarks about "religious experience".

I'm always highly suspicious about talk of "religious experience", as if it is some special and distinctive category of experience. So what do Murray and Rea mean? Well, they talk of (i) "mystical experiences -- visions or other sorts of overwhelming experiences that present themselves as experiences of God", more mundanely (ii) "a sense of divine forgiveness, a subtle awareness of the presence of God, an internal impression that this or that sacred book is divinely inspired", (iii) experiences which people have "taken to involve some sort of direct awareness of God, or of God's communicating something to them".

Well, that's already a very mixed bag. "An internal impression that this or that sacred book is divinely inspired" sounds like a gut hunch -- a sort of thought. Thinking you are forgiven is presumably another thought (if you hold that perceptual experiences have non-conceptual content, then it would be entirely obscure how you can have a quasi-perceptual experience freighted with the concept of forgiveness!). "Visions", by contrast, are presumably visual experiences -- though it beats me how those can be experiences of an incorporeal God. And talk of "some sort of direct awareness" is just arm-waving.

But ok, let's take "religious experience" as a catch-all label, without worrying too much about the connotations of "experience". (But so understood -- as it seems to be by Murray and Rea --  we shouldn't be at all impressed by claims like Alston's that religious experiences are analogous to perceptual experiences. Many of the supposed examples covered by the catch-all usage are plainly not analogous). Anyway:  what reasons are there for trusting the deliverances of "religious experiences"?

Murray and Rea write, following Alston, "it is very hard to find reasons for thinking religious experience ought not to be trusted that do not also indict perceptual experience". Really? A common-or-garden  account of the  origins of my perceptual experience has it that, when I see the cup of coffee on the desk right now, my having that experience is caused by the cup of coffee on the desk. It is very far from clear, by contrast, that the obvious account of someone's "sort of direct awareness of God" when she has that experience is that the experience is caused by some interaction with a deity. Dan Dennett, for example, offers a nice evolutionary account of why we might be prone to just those kinds of thought, over-interpreting the presence of agency in the world, even though they are false and not generated by the presence of deities. And whether his story is exactly right or not doesn't matter too much: the point is that it gives us a template for an inviting kind of naturalistic story about our proneness to certain kinds of illusory thoughts and experiences (intimations of the supernatural) that does not also indict ordinary perceptual experience. Given that we can, in 2008,  begin to see at least the outlines of various possible naturalistic stories, and putting that together with a presumption in favour of not multiplying entities beyond necessity, it is of course -- to say the very least -- a wide open question whether religious experience has any claim at all to be trusted.

Murray and Rea are reliabilists in epistemology (I'm happy to agree), and seem to think that "there is at least prima facie reason for thinking that religious experience can justify religious belief in just the same way that perceptual experience justifies perceptual belief" because it is  prima facie reasonable to presume that religious experiences are reliably generated. Well if 'prima facie' means 'on very first impression, before we think about it', so be it. But just on a moment's second thought, that first impression should entirely evaporate.
