---
title: "Philosophy of Religion 8: Pluralism"
date: "2008-04-03"
page-layout: article
---

No. I'm not giving up my day job. A new logic book project is under way and taking nearly all my attention. When I'm more confident that it is "taking off" and going places, I'll say more about it here: but not yet -- after all, I don't want to ... erm ... tempt fate! I also must finish Absolute Generality in the next week or two. So the Introduction to the Philosophy of Religion is just a bit of late-evening reading, and the comments are dashed off quickly for fun.

Anyway: I've just been looking at the section where Murray and Rea wonder whether the fact that religious experience seems to tell different people such different things might rationally rather undermine an inclination to take our own experiences at face value. To which you'd think the answer is a plain "yes". But ah no, they say, that would be a mistake.

Suppose you are a Christian who thinks that only those like you who, by special grace, have been granted a revelation of the divine have access to reliable religious experiences: then widespread disagreement among the heathens is only what you'd expect. "Far from being evidence of unreliability, her particular circumstances are precisely what she should expect" if she were among the elect.

Indeed. But beside the point.

The issue isn't whether someone can have an internally coherent set of beliefs which enables her to "explain" to herself why -- in the face of massive disagreement -- hers are the correct views and everyone else is out of step. That's only too easy (though also that way madness lies).

The issue at stake is surely this.  I don't already believe I am one of the elect, because I don't yet know what to believe. Perhaps I'm seeking God, but at this point I'm unsure about the path.  But here I am having certain experiences which seem to intimate some kind of divine presence, seem to have religious content or whatever. Initially, let's suppose, I'm rather inclined to accept the experiences as veridical. But in a calmer moment I start reflecting. I want to know how trustworthy these experiences are. Am I just suffering some kind of illusion? Satan's stratagems are many. I try to crosscheck with others (as I might crosscheck with others about other surprising experiences). I find -- at least if I look outside those subject to the same immediate cultural influences -- unending disagreements about their experiences. Some give quite different religious interpretations, some seem to give interpretations freighted with aesthetic concepts, or other non-religious readings.  It certainly now  seems that this diversity should rationally lead me to reduce my initial higher degree  confidence in how to interpret what is happening to me.  Why not?

Noting that such disagreements needn't reduce the confidence of someone else who already "knows" that she is one of the elect and "knows" that her experiences are reliable is neither here nor there.  The question is how someone who doesn't already know their religious experiences are trustworthy   should change their rational degrees of belief in the light of finding that initially compelling-seeming experiences don't readily crosscheck.
