---
title: "Philosophy of Religion 9: Theistic arguments"
date: "2008-04-06"
page-layout: article
---

Chapter 5 of the Murray/Rea Introduction is called "Theistic arguments". They start off -- perhaps rather too predictably -- by considering at length the tricksy argument which philosophy of religion courses seem to get obsessed with, but which (at least in my experience) has the least to do with the actual reasons real-world believers give for their beliefs. That's our old friend the ontological argument, of course.

Murray and Rea have no trouble in kicking into touch a classical version of the argument (their pp. 129-130 explanation is exemplary). Though they are a bit feeble earlier when talking about the existence-isn't-a-property objection. For they just don't mention how you might try to make sense of what is going with that objection by linking existence talk to the existential quantifier, etc. (an odd omission, as the intended readers' intro logic lecturer has probably been mentioning that very point -- why not make the connection?).

But instead of leaving well alone, Murray and Rea next go on to consider a Plantinga-style modal version of the argument (which even Plantinga doesn't think is probative). But if their readers aren't supposed to know enough logic to be in a position to cope with the existential quantifier in discussing responses to the classical argument, they are surely just going to be flummoxed by this! They certainly aren't going to be in a position to discuss it properly (e.g. by  evaluating the S5 principle for the needed metaphysical modality, discussing whether freedom from self-contradiction is a ground for attributing the requisite kind of metaphysical possibility, and so on -- certainly Murray and Rea don't give them the tools to do this).

Anyway, leaving the modal argument rather in the air, our authors go on to consider  cosmological arguments. And again they have no great problem disposing of some classical varieties, perhaps after unnecessary palaver. (Though another odd omission is that they don't explicitly connect what they say to the quantifier shift fallacy exposed in intro logic courses, where various cosmological and design arguments are typically offered as a prime illustration.)

Finally, Murray and Rea discuss design arguments, ending up with a weak treatment of the "fine tuning" argument. I say weak, because they rightly present the argument as a probabilistic one -- but say nothing about the kind of probability involved or the probability principles being applied. Since critics have suggested that the argument confuses different kinds of probabilities, and/or argued that the principles involved about distributions of the values of physical constants in possible ranges are fallacious, this is a pretty serious omission. And worryingly so, given that of all the arguments mentioned in the chapter, this is the one that actually has some currency in half-informed thinking outside the academy. You might have thought that Murray and Rea would really want to be wrestling with it, and pushing a lot harder on its probabilistic credentials. To say the least, an opportunity badly missed here.
