---
title: "Philosophy of Religion 10: Anti-theistic arguments"
date: "2008-04-09"
page-layout: article
---

Where have we got to, then, a bit over half way through Murray and Rea's [An Introduction to the Philosophy of Religion](http://www.cambridge.org/uk/catalogue/catalogue.asp?isbn=9780521619554)?

Religious belief has been tied (I'd say pretty misguidedly) to "perfect being" theology. Murray and Rea have a shot at making metaphysical sense of talk of a perfect being in the first couple of chapters -- which I haven't discussed enough here, and really should come back to. But the notion is (unsurprisingly) left pretty murky. Their attempts in Ch. 3 to make sense of the doctrines of the Trinity and the incarnation are based on hopeless analogies. They seem to place some weight on "religious experience" in Ch. 4 but are remarkably silent on what that might consist in -- and they give no good reasons for supposing that such experiences are a reliable guide to anything. And in Ch. 5 our authors themselves defeat most of the standard arguments they consider for theism, except for the fine-tuning argument; and if that last one is still in play, it's arguably because they don't properly examine the probabilistic reasoning on which it depends.

So where do we go from here? The story continues ...

In Chapter 6, Murray and Rea turn to "Anti-theistic arguments". But, at this stage in the game, in what sense does the atheist need anti-theistic arguments? She might well muse along the following lines: 
> "Burden tennis", batting the burden of proof to and fro over the net, is rarely a very profitable pastime! But still, maybe this case is an exception. After all, "perfect being" theists, when you come down to it, are making some highly  exotic claims, claims that aren't that much clearer after Murray and Rea's  labours, and which  make the beliefs, say, of ancient Greek religion look very modest and humdrum. Not just powerful gods, but an omnipotent god. Not just gods  intermittently casting an amused eye over mortal folly, but an omniscient god. And one not just occasionally taking a passing interest in some of us, for good or ill (and occasionally, understandably, running off with a particularly pretty nymph) but loving us all equally. And on it goes, wilder and wilder (e.g. the three-for-the-price-of-one Trinity). By the workaday epistemic standards we use in most of our lives, those extravagant claims look quite extraordinarily fanciful. So we can reasonably insist that someone who advances such claims literally (not, for example, as inspiring myth) and expects to be taken seriously, had better have some very, very, good arguments. Pending such arguments, which we haven't been given yet, we atheists don't have much to do.

> Or at any rate, recalling Russell's teapot, we needn't do much by way of coming up with additional reasons against a  perfect being to add to the lack of weighty enough  reasons for believing in any such a thing. But of course -- in a spirit of  human curiosity -- we might well be interested in reflecting about what it is about our minds and about human societies that make us rather prone to be gripped by such fanciful ideas. What role do they play for us? What sustains religious belief in our emotional and social life in the absence of weighty reasons? Well, there's a very long tradition of intriguing enquiry about this --  the "natural history of religion", if you like -- which seeks to explain the role of religious belief. Thus, for example, Dennett's speculations about the evolutionary advantages of a tendency to over-interpret agency in our environment are just the latest ingredient in a long and complex story. And this evolving story seems to make a pretty good stab at the beginnings of explaining the role of religious beliefs without sustaining their truth-claims

Now, you might well have expected Murray and Rea to have addressed this sort of calm "default atheism" head on and at length at this point. For in a highly secularized society like large swathes of "middle England", inchoate versions of this kind of detachment from religion    are nowadays very widely shared.

But at the beginning of the "Anti-theistic arguments" chapter, they in fact say that "we will set aside arguments which claim that the absence of evidence makes belief in atheism more reasonable or obligatory since that issue was addressed in chapter 4." However, chapter 4 doesn't address default atheism. It talks about the notion of faith and about whether "religious experience" might be the result of a reliable belief-acquiring mechanism -- but we saw that the discussion of the latter was vitiated by a failure to properly discuss naturalistic stories about our proneness to such "experiences". As I noted before, Dennett (for example) is nowhere  mentioned. Nor is the Hume of the Natural History mentioned. Nor are Hegel, Feuerbach, Marx in the index (to take names from just one other familiar strand of enquiry about the roots of religion). It looks as if Murray and Rea are just not interested in engaging with the naturalizing default atheist.

Glancing ahead just at the subsection titles, however, I notice the next chapter "Religion and science" does in fact say something about evolutionary psychology and religious belief. So I'd better suspend judgement for a bit here. It may be that the complaint is only going to be that key bits of missing discussion come not in Ch. 4 but later in Ch. 7 (which might be pretty  ill-judged arrangement, but that's better than a disastrous lacuna). We shall have to see! For the moment, then, I just note that default atheism, seemingly the position of most of the students I've taught over the years, is not yet getting the kind of direct discussion that I'd have expected (at the point I would have expected it given what's gone before). I wonder: does this betoken the fact that North American authors are more used to dealing with students who are, as they say, coming from somewhere else? Anyway, we'll move on to consider what they do discuss in Chapter 6, which is mostly the argument from evil. (But I need to gather my strength for that, so don't hold your breath ....)
