---
title: "Philosophy of Religion 11: Which problem of evil?"
date: "2008-04-19"
page-layout: article
---

So where have we got up to, reading through Michael Murray and Michael Rea's [Introduction to the Philosophy of Religion](http://www.cup.cam.ac.uk/catalogue/catalogue.asp?isbn=9780521619554)? Ah, the problem of evil. But which problem of evil?

To start with, there's the particular problem for those whose religion is Bible-based. Because there is the evident sheer moral nastiness of the God of the Old Testament, who is sadistically keen on the killing of those who lapse into a bit of adultery, homosexuality, or who blaspheme, or even do a bit of work on the sabbath -- and who commands the Israelites to wholesale slaughter and genocide.  True, we like to think that the God of the New Testament has mellowed a bit: but even so, he still has   some decidedly vicious  tendencies. A violent end is  still prophesied  for those who haven't got round to seeing the light by the time of the second coming. The Bible is a bit undecided whether it is going to be a mass drowning (as in the time of Noah), or whether the destruction of the ungodly is to be by fire. But it is going to be very nasty either way. And let's not even visit the entirely repellent doctrine of eternal damnation in the fiery furnace. The Biblical God is an unpleasant piece of work, and Mill's attitude is the morally decent one: "I will call no being good who is not what I mean when I apply that epithet to my fellow creatures; and if such a creature can sentence me to hell for not so calling him, to hell I will go."

Of course, most modern believers -- leaving aside the more dingbat types of fundamentalist -- do sit fairly loose to the most morally offensive bits of the Bible, cherry pick the attractive episodes, and claim to believe in a deity not given to capricious rage and cruelty. Still, "by their fruits you shall know them" presumably applies to deities too. And the world as we find it is a ramshackle, mismanaged affair, full of suffering and pain for very many of God's creatures. And many find it very difficult to come to believe that we should worship God for his botched efforts, or think particularly kindly of the arrangements he has so cackhandedly put in place which involve so much pointless misery and worse. Didn't he care about making a world where things ran at least just a bit better (a bit less agony in some terminal cancers, for example)? It seems not. Moral rejection again seems to many the proper stance for decent grown ups.

However, I'm not going to pursue these two familiar strands of thinking about religion and evil here, for Murray and Rea don't pursue them either. They don't discuss the sheer unpleasantness of the Biblical God (you'd have thought this might have mattered more to them, given their focus of historically-rooted Christianity). Nor do they really explore the  kind of moral rejection of God because of encounters with evil that often leads people to lose their faith. Though surely this is very often the way: someone -- perhaps witnessing  the prolonged death agony of a close relative -- comes to think "this just makes no sense; if accepting God is accepting this, then I want no more  part of it", and she stops praying, stops religious observance, stops thinking in terms of God's purposes, and so on. It would be procrustean to construe this as a change in her metaphysical views, a revision in her catalogue of the ontology of the world: it is more that -- so to speak -- thought and talk about God becomes an irrelevance to her. But as we've noted before, Murray and Rea aren't in general much interested in these sorts of phemomena of religious life.

No, what they do discuss is what we might call "the metaphysical problem of evil". Is the existence of the God of the Philosophers -- the Perfect Being of Murray and Rea's opening chapters -- incompatible with, or is it at least rendered probabilistically improbable  by, the existence of so much evil in the world? Well, this is familiar territory. How do they cope? The story continues ...
