---
title: "Philosophy of Religion 12: Evil and the ad hoc"
date: "2008-04-27"
page-layout: article
---

Chapter 6 of the Murray/Rea book concentrates on the familiar argument that the existence of a "Perfect Being" God can't be squared with the amount of apparently utterly superfluous evil to be found in this sublunary world.

Half way through the chapter, Murray and Rea make a distinction between what they call a defence (''a possible reason, without concern for its believability, why God might permit evil" -- "a defence aims just at demonstrating the possibility of God's coexisting with evil"), and a theodicy ("a believable and reasonably comprehensive theory about why God might have permitted evil of the amount and variety we find in our world.").

That's an excellent distinction to make. But they miss the opportunity to add that a "defence", so called, is of course typically no defence at all; it's just an ad hoc patch with no virtue other that saving the appearances. A classic version of this sort of "defence" is found, of course, in Plantinga's daft ruminations about transworld depravity and so forth. This game-playing is of no more value to the struggling Perfect Being theist than any other bout of ad hockery used to save  theories from potentially fatal anomalies. And students should be told so. The philosophy of science in particular has, post Lakatos, a rich literature on what makes for an ad hoc move, and why such moves are intellectually disreputable and to be roundly criticized. It would have been good to see Murray and Rea engage with this literature and similarly lambast ad hoc "defences" in the debate on the problem of evil. But they don't.

Anyway, we needn't take mere "defences" seriously -- once the Perfect Being theist is reduced to relying on those, he's as lost as anyone else in a badly degenerating research programme who has to rely on ad hockery to fend off final refutation.

So what about the theodicies that Murray and Rea consider?

- *The punishment theodicy* Evil is a result of divine punishment for human wrong-doing. Murray and Rea don't like this, but they are almost offensively gentle about this horrible idea.  Visiting the sins of the fathers upon the children just makes out God to be vilely vindictive.

- *Natural consequence theodicy* Some evils are just the natural consequences of wrong doing. But as Murray and Rea note, that doesn't even get into the right ball-park for explaining the vast amount of  suffering produced in the world without the intervention of moral agents.
- *Free will theodicy* It is a good that there are free agents, and some free agents will (regretably) go wrong. But as Murray and Rea note again this doesn't get into the right ball-park for explaining natural evil. And of course, it doesn't get God off the hook even with respect to the actions produced by free agents. A powerful enough ominiscient being could snuff out a few conspicuously evil agents, a Hitler here, a Stalin there, and nudge down the amount of evil.
- *Natural law theodicy*. Evil arises out of preconditions that must be in place for creatures to exercise their freedom. But this smacks of ad hockery again. We haven't the foggiest reason to suppose that a world with free agents has to be a world with particularly nasty terminal cancers. Why shouldn't God have created a world with a patchwork of laws of relatively local extent (actually some like Nancy Cartwright think that is what he created!) which allows rather less suffering? And if that means intervening a bit more to keep the show on the road, well an omnipotent being who cared could do and would do that. As, in effect, Murray and Rea note.
- *Soul-making theodicies* We need some evil around to build a bit of moral character. But again, that's a quite ghastly idea, that a baby's terrible suffering should be there to help me make my soul better. And of course, there isn't the foggiest reason to suppose that all the evil there is in the world is needed for those supposed good purposes. Again, Murray and Rea are rather offensively silent on this singularly nasty idea.

So where have we got to? We've five theodicies mentioned, and even by Murray and Rea's own count, four of them are hopeless, and the fifth is equally bad.

Very oddly, however, they sum up the situation at the end of the chapter like this: "Are the arguments against the existence of God ... powerful? Some think so. However, as we have seen, these arguments rely on assumptions that are open to some serious challenges. How serious those challenges are is a matter for each of us to decide." Which is inept, twice over. Firstly, it misrepresents how their arguments have actually gone. But worse, beginning students -- as Murray and Rea must know -- don't need invitations to "decide" for themselves. They need precisely the opposite, injunctions to follow arguments carefully, and apportion their credences to the weight of arguments. Especially in this sort of area, students are only too willing to avail themselves of any get-outs.
