---
title: "Philosophy of Religion 14: Miracles?"
date: "2008-04-29"
page-layout: article
---

Those who are getting fed up with me banging on and on about the Murray/Rea Introduction to the Philosophy of Religion and are waiting for some serious stuff can rest easy. This will be the penultimate post on that book. And then it's back to Absolute Generality (as I must finish that and write a review in the next few days). Maybe I'll also post something elementary and expository here on Galois connections if I can sort an annoying bug in my thinking. And -- if the discussion goes well enough tomorrow -- I'll post the informal talk on Szabo on "Believing in things" here too. And there's more in the pipeline. I will return to logic matters, promise!

But in the meantime, back to Murray and Rea's Ch. 7, "Religion and science".  There's a central section on miracles, which makes some sound points against arguments which purport to show too quickly that the very idea of a miracle is incoherent. I won't discuss those. They then offer the following suggestion: a miracle is "an event (ultimately) caused by God that cannot be accounted for by the natural powers of natural substances alone". OK, let's work with that.

Could we have evidence of the occurrence of such events? Murray and Rea imagine being present at the parting of the Red Sea (assuming it happened for the sake of argument).  "If we were present for the occurrence of the event, none of us would think it more plausible that this event is to be explained by no-cause rather than a supernatural cause. ... In this context it seems very plausible that the event was caused by a supernatural agent looking to rescue the Israelites." Not so. Don't Murray and Rea ever read any science fiction? Sure, in the described context it seems very plausible that the event was caused by some non-human agency of super-human powers. But -- to borrow from the immortal Hitchhiker's Guide to the Galaxy -- a Vogon constructor fleet is just as good as a hypothesis as something supernatural, if that means divine (which it does in the context). In fact it's a better type of hypothesis, because we have some inkling how something like a Vogon constructor fleet might pull off the trick of parting the Red Sea (big engineering works being its forte) and have no clue at all about how a disembodied being gets to do major physical interventions.

Of course, if you already believe in God and don't already believe in Vogon constructor fleets, then of course you'll be inclined to put down the parting of the Red Sea to the first, not the second. But overlooking the possibility of rival hypotheses (not about Vogons in particular, of course, but of super-human but non-divine agency) is not exactly an intellectual virtue! The point remains that being present at the parting of the Red Sea at most gives you evidence of super-human agency, and no more.  It is no evidence per se of the supernatural or divine. And hence no evidence per se of a miracle defined as an event caused by divine agency (unless you already have an argument that the only super-human agency is divine -- which of course we haven't).

But of course, most of us aren't present at such events anyway. Beliefs in miracles usual rely on testimony. And discussions of miracles usually consider how to weigh up the likelihood of reliability of testimony when what is testified is in itself highly unlikely (and, perhaps, we also  know we are in area where fraud, wishful thinking, and foolish credulity abound). Weirdly, Murray and Rea opt not to discuss this at all.  For arguments of this sort "involve an examination of the integrity of historical evidence for the occurrence of particular miracles that is more appropriate for the domain of history than philosophy". Eh? Really? So much for the philosophical discussions of testimony, then.
