---
title: "Philosophy of Religion 15: Enough already!"
date: "2008-04-30"
page-layout: article
---

Suppose a first year student wrote this (about mind-body substance dualism):

> There are no very persuasive arguments against dualism ... Dualism is commonly mocked rather than argued against.

Then we'd berate this exhibition of sheer ignorance. We'd send the student away with a long reading list. Start, say, with the second chapter of Armstrong's classic Materialist Theory of the Mind. Or perhaps chapters II to V (over fifty pages of careful unpicking and assessment of various arguments, pro and con) of Smith and Jones's Introduction to the  Philosophy of Mind (yes, folks, it is still in print after 22 years: buy, buy while stocks last!).  And we can, of course, add a lot more.  The reason the vast majority of contemporary philosophers of mind reject naive substance dualism has nothing to do with mockery, and everything to do with the fact that that there are so many weighty problems with it that it has long since become, at the very least, a badly degenerating research program.

But that quotation doesn't come from a first year student but from Murray and Rea's book, at p. 266. I boggled when I read it, and despair. It really is pretty difficult to take authors who can write something like that seriously any more. My patience is at an end, so I'm going to stop. I'll not say anything then about their feeble discussion of "evolutionary models of religious beliefs", where they don't even mention Dan Dennett. And I'll not say anything about their equally feeble discussions of the status of morality.

This is not a good book. In fact, as readers of this blog will have come to suspect, I think it really is overall a rather bad, too often weakly argued, one. It is published in a prestigious series, and -- especially since student texts don't tend to get widely reviewed -- it could end up being widely read (no doubt a lot more widely read than my Gödel book which rubs shoulders with it in the series!), corrupting the minds of the youth. What was CUP thinking of?
