---
title: "Religion and The Philosophy of Religion"
date: "2008-03-25"
page-layout: article
---

I've commented here a couple of times about some daft newspapers columns about matters of religion and science (see [here](http://logicmatters.blogspot.com/2008/03/atheist-delusion.html) and [here](http://logicmatters.blogspot.com/2007/12/more-twaddle-about-religion.html)). And -- quite unexpectedly -- I've found myself contributing a number of responses on religion as a newbie panelist for Ask Philosophers (for example, [here](http://www.askphilosophers.org/question/2049), [here](http://www.askphilosophers.org/question/1750), and [here](http://www.askphilosophers.org/question/2012)).

I don't pretend, though, to be any kind of expert on the philosophy of religion: far from it (not that I needed to be to make the entirely obvious points in those postings I've just linked to). But I guess if I'm going to keep sounding off like this I ought to know just a bit more about the hot topics and fancy moves in the philosophy of religion these days. So this afternoon I picked up a copy of the brand new [An Introduction to the Philosophy of Religion](http://www.cambridge.org/uk/catalogue/catalogue.asp?isbn=9780521619554) by Michael J. Murray and Michael Rea. It's published in the same CUP series as my Gödel book -- which in part is what drew my attention to the book.

The publisher's website calls it "a balanced and broad introduction", though a quick browse through makes it look as if "fence-sitting" might be a bit more accurate. And apparently it will be "a valuable accompaniment to undergraduate and introductory graduate-level courses", but it looks more like a first year intro. undergrad text to me. But ooops, I mustn't rush to judgement! Having shelled out for the book (albeit with a hefty press author's discount!) I better read it now: so I'll dive in and report back here.

At least it will make light relief from thinking about Absolute Generality, and other logic stuff.
