---
title: "Buechner: Gödel, Putnam, and Functionalism"
---

*

 

Suppose an undergraduate wrote this:** The first [incompleteness theorem] says that there are truths of arithmetic that are not provable in a consistent first-order logic that can express arithmetic.

You’d patiently explain that there are four things wrong with this. First, it confuses “logic” with “theory”. Second, as you’d remind the student, the first theorem was originally proved for a higher-order theory, and applies to any theory which is properly axiomatized, whether first-order or not. Third, this statement confuses the conditions for semantic and syntactic versions of the first theorem. If you only assume the theory can express enough arithmetic, then you need to assume soundness to derive incompleteness; if you only assume consistency, as in the standard syntactic version, then you have to assume that the theory can represent enough arithmetic (where this is a matter of proving, rather than merely expressing, enough). And fourth, the statement is fatally ambiguous between (a) there are truths not provable in any consistent theory which can represent enough arithmetic, and (b) for any consistent theory etc. there are truths that that theory can’t prove. Given that folk misinterpretations of Gödel trade on that ambiguity, you drill into your students the importance of clearly avoiding it.

Your student goes on to write:** The standard view is that we cannot prove CON(PA), period. (I use CON(PA) as an abbreviation for the sentence that expresses the consistency of Peano Arithmetic.) … However, all that follows from the Gödel theorems is that we cannot prove CON(PA) with mathematical certainty.

Again, you’d start by patiently reminding the student that there is no such thing as the sentence that expresses the consistency of Peano Arithmetic — and indeed, as Gödel himself later observed, there are sentences that arguably in *some* sense express the consistency of PA (it depends how we regiment that murky idea of ‘expressing’)  which are provable in PA. In headline terms, it matters for the Second Theorem which consistency sentence you construct, in a way that it doesn’t matter for the First Theorem which Gödel sentence you construct. But second, and much more importantly, it certainly is not the standard view that we cannot prove CON(PA), period. Any good treatment emphasizes that unprovability in PA is not unprovability period.  Third, you’d add that it doesn’t follow from Gödel theorems either that “we cannot prove CON(PA) with mathematical certainty”. By ordinary standards of certainty, proofs inside ZF are usually regarded as being as solid as you could want, and you can certainly prove CON(PA) in that and weaker set theories. And anyway, what’s wrong, for example, in proving CON(PA) from PA plus the Pi_1 reflection schema for PA? If you are mathematically certain about PA and its implications (which almost everyone is!), why wouldn’t you be equally certain about the result of adding instances of the reflection schema? Arguably you should be: but in any case, nothing follows from Gödel theorems about that issue.

And fourth, you might quiz your student about what he makes of the Gentzen proof. Ah, he says,** We need transfinite inductions along a well-ordered path of length epsilon_0 to prove CON(PA) [in Gentzen’s way]. The issue, then, is this: if human minds know the truth of CON(PA) with mathematical certaintly, is the only method by which we do it the use of infinitely long derivations?

But there’s a hopeless misunderstanding here: you’d remind your student that a proof by transfinite induction is not an transfinitely long derivation: it is just a finite proof assuming that a certain ordering is well-founded.

Unfortunately, those quotations — and there’s more of the same — are not from a student essay but from a book, one published in 2007  by MIT Press no less, Jeff Buechner’s Gödel, Putnam, and Functionalism (see p. 8 fn. 8; p. 33; p. 39). I was asked to review it: but with garbles like that in a book one of whose main topics is the implications of Gödel for functionalist mechanism about the mind, I was not encouraged to read any further. Life being short, in the end I didn’t.
