---
title: "Cori & Lascar, Mathematical Logic"
---

*

 

René Cori and Daniel Lascar’s *Mathematical Logic* (OUP,  2000) is the translation of a French original first published in 1993. Its sub-title, “A Course with Exercises” highlights a *very* welcome feature of this text. The main bodies of the chapters in Part I add up to some 207 pages; there are in addition 31 pages of exercises and then, at the end of the Part I, no less than 85 pages of very well-presented solutions to the exercises. The proportions in Part II are similar. This means that even if you are using other texts as your main introductions to the various topics, you could profitably mine Cori and Lascar as a source of lots of worked exercises in a way that could be extremely useful, especially if you are largely teaching yourself logic from books.

What about the core presentations before you get to the exercises, though? Part I comprises four chapters. The first (46 pp. before the substantial set of exercises) is on the language and semantics of propositional logic, including a proof of the interpolation lemma and of compactness. The third (70 pp.) is on the language and semantics of predicate logic, with a little model theory. This is all highly respectable, though I wouldn’t recommend these pages as a first encounter — but you could safely add them to the long list of possible supplementary/consolidating readings, if their style appeals.

The fourth chapter (48 pp.) then *very* briskly introduces a proof-system for predicate logic (since this system counts as every instances of a tautology as an axiom, deleting the quantifier axioms and rules leaves us with a trivial and unilluminating proof system for propositional logic — evidently proof-theory isn’t the authors’ thing!). We then get a Henkin-style completeness proof, first for the case of finite/countable languages, and then for the general case appealing to Zorn’s Lemma, though the reader has to leap ahead to Part II of the book to find out what that lemma says. I didn’t find this to be particularly accessibly done, nor indeed are the following sections on Herbrand’s method and on resolution. There are better options out there.

What about the second chapter of Part I (43 pp.)? This is a stand-alone chapter which can be read independently or equally well can be skipped as far as following the rest of the book is concerned. You’ll need an amount of algebra and topology to follow this introduction to Boolean Algebra, which gets as far as the theorem that every Boolean algebra is isomorphic to the algebra of clopen subsets of its Stone space. Which strikes me as significantly more than the logical beginner really needs to know!

Moving on to Part II, there are again four chapters. The first of them (47 pp., still before the exercises) is on recursion theory and pretty clearly done, except that there is an unnecessarily non-standard characterization of a Turing machine. The next chapter (37 pp.) — after a little on representing recursive functions and on the arithmetization of syntax — gets us to versions of Gödel’s incompleteness theorems. Now, the detailed routes taken in the final sections — particularly to the second theorem — are not the most familiar ones. So it would be an interesting (and non-trivial) exercise for enthusiasts to work out quite how the arguments here relate to a conventional presentation as e.g. in my *IGT*. But this will therefore make the chapter interesting to those who already know a bit about incompleteness also makes it difficult to recommend it as a starting point for those new to the area.

The third chapter of Part II is on set theory (63 pp.). This is a more conventional treatment covering a conventional menu, and none the worse for that. We get the ZF axioms, and eventually Choice; meet the ordinals, transfinite induction, cardinals and their arithmetic, the axiom of foundation, and eventually inaccessibles and the reflection scheme. Indeed this does seem a particularly clear introduction at its level and scope of coverage.

The final chapter (50 pp.) is titled ‘Some model theory’. There is no default menu of topics for such a chapter. This one covers elementary substructures and the Tarski-Vaught test; something about the method of diagrams; more on interpolation and Beth’s definability theorem; ultraproducts and Łos’ theorem; some preservation theorems; the omitting types theorem; and a little more. All standard good things to know about, but perhaps — to my mind — not particularly excitingly done.

*Summary verdict*: The Gödel chapter and the sets chapter are worth mentioning in the *Study Guide*, in addition to the recommendations of the exercises/solutions.
