---
title: "De Swart, Philosophical and Mathematical Logic"
---

*

 

I have mixed feelings about Harrie de Swart’s *Philosophical and Mathematical Logic* (Springer, 2018). For this long book really is a strange mish-mash, supposedly aimed at philosophers. There are chapters (not very good) on e.g. the philosophy of language and “fallacies and unfair discussion methods”, and e.g. a section on social choice theory. Then there are chapters more directly relevant to the *Beginning Mathematical Logic Study* *Guide*, particularly on propositional and predicate logic, and on intuitionistic logic. Let’s concentrate on those.

If the overall structure of the book is a bit of a disorderly hodgepodge, so too can be the structure of individual chapters. Take, for example, the chapter on propositional logic. We get a bit of baby-logic level talk about truth-functions, then suddenly a compactness argument. Then we are back to baby-logic on defining inferential validity. Some remarks on enthymemes are followed by a bit of metalogic. We get an untidily-presented Hilbert-style proof system (the typography of this book is often clumsy). Then there is what is marked as a digression on a natural deduction system, too quick to be useful. Next we get Beth/Fitting tableaux and a completeness proof for them (but sadly not ideally well-presented, which is a great pity as it makes the treatment of tableaux in later chapters that bit less accessible ). The chapter finishes with a random walk through some paradoxes, and then some arm-waving history in a strange chronology. Frankly, what a presentational mess!

The ramble round propositional logic is followed by a so-so chapter on sets, finite and infinite. And then we are onto predicate logic. Now, this chapter on FOL has — by my lights — a very nice feature: de Swart notationally distinguishes constants from ‘free variables’ from ‘bound variables’ as three different types of symbols, and defines terms as built (ultimately, perhaps using function expressions) from constants and/or free variables alone. This enables him to sidestep that annoying fussing about allowable substitutions and about unwanted variable capture that arises if we take the conventional line and have an initially undifferentiated class of variables, and we get nice tableaux rules etc.

I’m rather minded in an updated version of the *Guide* to say enough about Beth/Fitting tableaux to make the discussion in de Swart’s propositional logic chapter rather more accessible, and then I can perhaps recommend those sections plus this chapter on FOL as pretty useful.

Taking up the tableaux theme again, I can then also recommend the chapter on intuitionistic logic which (as noted in an earlier version of the *Guide*) gives a pretty nicely explained account of one way of doing tableaux for this logic — even if this chapter is still not my ideal presentation of intuitionistic logic.  (The ideal short book has yet to be written!)

As for the rest of de Swart’s book? It must sound very ungrateful to say that someone who has written ten chapters adding up to well over five hundred pages would have done better to write a much more focused, more disciplined (but at points more expansive) book of less than half the length. But I’m afraid that that has to be my summary verdict.
