---
title: "Greg Restall, Proofs and Models in Philosophical Logic"
---

*

There does seem little consistency in the level/intended audience of the various books in the Cambridge *Elements* series. John Bell’s book on type theory is pretty hard-core graduate level, and mathematical in style and approach. John Burgess’s book on set theory I found to be a bit of a mixed bag: the earlier sections are nicely approachable at an introductory level; but the later overview of topics in higher set theory — though indeed interesting and well done — seems written for a different, significantly more mathematically sophisticated, audience. It is good to report, then, that Greg Restall — as his title promises — does keep philosophers and philosophical issues firmly in mind; he writes with great clarity at a level that should be pretty consistently accessible to someone who has done a first formal logic course.

After a short scene-setting introduction to the context, there are three main sections, titled ‘Proofs’, ‘Models’ and ‘Connections’. So, the first section is predictably on proof-styles — Frege-Hilbert proofs, Gentzen natural deduction, single-conclusion sequent calculi, multi-conclusion sequent calculi — with, along the way, discussions of ‘tonk’, of the role of contraction in deriving certain paradoxes, and more. I enjoyed reading this, and it strikes me as extremely well done (a definite recommendation for motivational reading in the proof-theory chapter of the *Beginning Math Logic* guide, or indeed perhaps earlier in the guide).

I can’t myself muster quite the same enthusiasm for the ‘Models’ section — though it is written with the same enviable clarity and zest. For what we get here is a discussion of variant models (at the level of propositional logic) with three values, with truth-value  gaps, and truth-value gluts, and with (re)-definitions of logical consequence to match, discussed with an eye on the treatment of various paradoxes (the Liar, the Curry paradox, the Sorites). I know there are many philosophers who get really excited by this sort of thing. Not me. However, if you are one, then you’ll find Restall’s discussion a very nicely organized introductory overview.

The shorter ‘Connections’ section, as you’d expect, says something technical about soundness and completeness proofs; but it also makes interesting remarks about the philosophical significance of such proofs, depending on whether you take a truth-first or inferentialist approach to semantics. (And then this is related back to the discussion of the paradoxes.)

If you aren’t a paradox-monger and think that truth-value gluts and the like are the work of the devil, you can skim some bits and still get a lot out of reading Restall’s book. For it is always good to stand back and see an area — even one you know quite well — being organised by an insightful and eminently clear logician. Overall, then, an excellent and very welcome *Element*.
