---
title: "Hilbert’s Foundations/Logic Lectures"
---

*

I’ve just been spending a couple of days looking at the massive volume of *David Hilbert’s Lectures on the Foundations of Arithmetic and Logic 1917-1933*, edited by William Ewald and Wilfried Sieg (Springer 2013), which has at last arrived in the library here.

The original material is all in German (sadly but understandably untranslated), and since my grasp of the language is non-existent, what I have been reading is in fact the general editorial introduction, and the introductions to the various chapters of book covering different lecture courses and supplementary material (like Bernays’s* Habilitationsschrift* published here for the first time). There’s a lot of other editorial apparatus (the whole project seems to have been done to an extremely high standard), but these discursive introductions themselves amount to upwards of 130 pages. They are extraordinarily interesting and illuminating even if you can’t (or simply don’t) read the texts they are introducing. True, some of the material in these introductions overlaps heavily with Sieg’s essays already published in his *Hilbert’s Programs and Beyond*, but it is all still well worth reading (again). So this is a volume your university library should certainly get: and not just for you to leave it on the shelf and admire from afar!

I take it that few people by now cleave to the old myth — propagated e.g. by Ramsey —  that Hilbert was a gung-ho naive (or even not-so naive) formalist. But that myth (already surely fatally damaged by Sieg and others) should be well and truly buried by the publication of these various lecture notes which witness Hilbert’s developing positions over the 1920s as he explores the foundations of arithmetic.

Let me just remark on two things that struck me — not about the development of Hilbert’s program(s) and the search for consistency proofs, however, but about his contribution to the modern logic. First, it is now clear that the wonderful book by Hilbert and Ackermann published in 1928 isn’t the fruit of a decade’s intensive work after Hilbert’s 1917 return to thinking hard about foundational matters. Rather, the early sections of that book are based very closely on notes for a 1920 lecture course ‘Logik-Kalkül’ prepared by Bernays, and then the core of the book is equally closely based on Bernays’s notes for a 1917/1918 course ‘Prinzipien der Mathematik’ (Ackermann’s contribution to the substantive content of the book indeed seems to have been markedly less than that of Bernays). So suddenly, within seven years of the first volume of *Principia* (which seems now to belong to a remote era), Hilbert has the makings of a logic text of a recognisable form can still be read with profit. That really is an astonishing achievement.

But second, there are more key ideas about logic in those early lectures which are left out of the book. Thus, in the 1920 lectures, the editors tell us** The logical calculus seems to have been designed to present propositional and first-order logic in a purely rule-based form which allows logical calculations to be presented as they naturally arise within a mathematical proof, and thus to furnish an analysis of logical inference and of the activity of mathematical reasoning.

This aspect of Hilbert’s logical investigations is lost from view in the later book Hilbert and Ackermann 1928 , where the rule-based version of quantificational logic is omitted altogether, and where the canonical versions of both sentential and first-order logic are presented axiomatically. But in these lectures the goal is to obtain a more direct representation of mathematical thought. In the 1922/23 lectures, Hilbert would formulate a calculus that presents, axiomatically, the elimination and introduction rules for the propositional connectives. Here, in early 1920, … Hilbert describes his rules for quantificational logic as ‘defining’ or ‘giving the meaning’ of the quantifiers. (pp. 279-80)

So here then already are intimations of ideas that Bernays’s student Gentzen would bring to maturity a dozen years later. Remarkable indeed.

There’s a lot more of equal interest in the editors’ wide-ranging introductory essays. Warmly recommended.
