---
title: "John Burgess, Set Theory"
---

*

Like other books in the Cambridge *Elements* series, this John Burgess’s contribution on *Set Theory* is about seventy, not-very-packed, pages (perhaps 30K words?). More than an encyclopedia article, or a handbook chapter, but half the length of a short book like my *Gödel Without Tears*. Books in the series are aimed at providing “a dynamic reference resource for graduate students [and] researchers”. And that’s already a tall order for a book on *this* topic, at any rate: for most graduate students in philosophy (even if logic-minded) are likely to be pretty much beginners when it comes to tackling some set theory — and a book accessible to such beginners isn’t likely to also to be of much interest to researchers.

OK, forget the impossible prospectus, and let me try to assess the book in its own terms. First, I certainly enjoyed a quick read. It is engagingly written. And at various points in the later pages Burgess very helpfully put some order into my fragmentary knowledge, or offered genuinely illuminating remarks. So I endorse the comment added below, “I especially liked the second half — on ‘higher set theory’ — and the picture it gives of the various subject areas (descriptive set theory, continuum questions, combinatorial set theory) and techniques (large cardinals, forcing, inner models, infinite games, …) and of how they’re interrelated. I can’t recall anything else that gives as good an overview so briefly.” However, although set theory isn’t my special thing, I didn’t exactly come to this innocent of prior knowledge. And I do have to doubt whether later pages of the book will really be accessible to many of the intended student audience. OK, it may be — for one example — that all the materials have officially been given to understand e.g. the Levy Reflection Principle on p. 55: but I suspect that a significant amount of mathematical maturity, as they say, would be needed to really appreciate what’s going on.

In headline terms, then, I don’t think that the book as a whole would work as advertised for many students. Still, the first half *does* make a nice motivating introduction, but one to be followed by (or read in conjunction with) a standard accessible introduction to set theory like Goldrei or Enderton. And *then *the enthusiast can return to try reading from §8 “Topics in Higher Set Theory” onwards to get a first overview of a few further more advanced topics, with a hope of getting a first inkling of what some of the interesting issues might be, before tackling a second-level set theory text.
