---
title: "Kirby: An Invitation to Model Theory"
---

*

 

The blurb of Jonathan Kirby’s *An Invitation to Model Theory* (CUP, 2019) describes the book’s aim like this: “[T]raditional introductions to model theory assume a graduate-level background of the reader. In this innovative textbook, [the author] brings model theory to an undergraduate audience. The highlights of basic model theory are illustrated through examples from specific structures familiar from undergraduate mathematics ….” Now, one thing that usually* isn’t* familiar to undergraduate mathematicians is any serious logic: so, as you would expect, Kirby’s book is an introduction to model theory that *doesn’t* presuppose a first logic course.

The *Invitation* is divided into six parts, each comprising five or six short chapters (the main text of the book is only 176 pages long), with dependencies very well signalled — the book is a model of clear structuring.  The first part ‘Languages and structures’ gives the logic-less student some basics about the ideas of a first-order language and interpretation in a structure, and then introduces the ideas of embeddings, substructures etc. (I rather suspect that some of the story about the basics of first-order languages would go too quickly if you really are a newcomer to this material.)

The next part of the book proves a compactness theorem (without depending on a prior proof of completeness) and gives some first applications. Part III, ‘Changing models’ proves downward and upward Löwenheim-Skolem theorems, gives some applications, gives examples of theories which are countably categorical (or categorical in other cardinals), and in particular use the back-and-forth method to show that countable models of the theory of dense linear orders with endpoints are isomorphic. Part IV starts by proving some results about quantifier elimination …

And we are now about 100 pages into the book. Is this perhaps beginning to sound a bit action-packed?  Manzano, for example, takes over 200 pages to get about as far. And I do suspect that for self-study Kirby’s book would make for tougher going for many students. Not that Kirby is unclear in what he *does* say; on the contrary, he writes beautifully clearly. But he could/should have said at least a little *more*. Significantly more classroom asides, plus some extra illustrative examples of key concepts, etc.  could have made a considerable difference.

For example, Part V is on types; and surely the student reader would have welcomed more explanation and motivation for the introduction of the notion than they get in §23.1. An  extra paragraph or three here would have helped a lot. And as this part of the book continues, the level of difficulty now seems to me to ratchet up markedly. I would have thought that by the time we get to §26.3 on zero-stable theories, or to a sudden invocation of strongly inaccessible cardinals in §27.3, many student readers could be losing the plot. (It’s not that the relevant notions aren’t clearly defined: but the motivations and significance may well pass them by).

The book finishes with five short chapters on the model theory of fields, applying earlier techniques, and leading up to a proof of Hilbert’s Nullstellensatz: interesting for algebraists, and pointing forward towards an important area of model theory — but maybe more than the logic-oriented reader will want in a first introduction to model theory.

Overall, then, I will stick to my Study Guide recommendations, where I suggest as a *first* route into the area the long last chapter ‘Some use of compactness’ from Goldrei’s excellent logic text, together with the more expansive book by María Manzano. The first two-thirds of Kirby’s book will then make for useful re-inforcement and supplementary material as necessary.
