---
title: "The metaphysics of logic?"
---

*

** A collection of essays on *The Metaphysics of Logic*, edited by Penelope Rush, was published as a very expensive haddock — no, no, you idiot spell-checker, *hardback — *in 2014. Even with my large discount as a CUP author, I balked at the price. But it is now newly available as a paperback, and (I confess, without looking too closely) I picked up a copy the other day.

I can’t honestly recommend that you do the same.

At my not-so-tender years, I’m just not very willing to spend my limited time reading papers that are badly written or  unclear where they are going. So I didn’t get very far with the first two pieces in the collection, by Penelope Rush herself and by Jody Azzouni.

The next paper by Stewart Shapiro is predictably three steps up in terms of clarity, focus, and lightness of touch. He is writing about ‘Pluralism, relativism and objectivity’. But if you have read his interesting 2014 book *Varieties of Logic *then you won’t find much new here.

There follows a typically thought-provoking paper by the late Solomon Feferman on his so-called conceptual structuralism. But it is available on his website here: Logic, mathematics and conceptual structuralism.

Penelope Maddy follows with ‘A second philosophy of logic’, again written with her characteristic clarity. But as with Shapiro’s paper, if you have been keeping up with this  author’s recent work, there will be no surprises. Maddy herself says that the paper “reworks and condenses the presentation” of Part III of her earlier book *Second Philosophy. *So while the paper here might serve some as a useful introduction to her thinking, it doesn’t really add anything new.

The next paper is at least new, but I’m not sure what other virtues it has. Curtis Franks is out to defend the idea that ‘logic, in the vigor and profundity that it displays nowadays, does and ought to command our interest precisely because of its disregard for norms of correctness’. So he aims to ‘lead the reader around a bit until his or her taste for a correct logic sours’. (Note the ‘a’.) Well, the therapy didn’t work on this reader (though there some interesting but hardly original remarks on the relationship of classical and intuitionist logic). But you can try for yourself here: Logical nihilism.

There follows a piece by Mark Steiner on ‘Wittgenstein and the covert Platonism of mathematical logic’. Wittgenstein seems to make both radical criticisms of classical ideas and to want to leave everything as it is. Steiner explores how to reconcile these tendencies.  Just how much you get out of this will depend on how much residual interest you have in Wittgenstein on the philosophy of the mathematics-he-really-seems-not-to-have-known-much-about.

And that’s all the papers in the first part of the collection, ‘The Main Positions’. These are  all papers by old hands, Rush apart, who have already contributed books on logic and foundations of mathematics. It would have been much more interesting to hear new takes on old positions from younger philosophers.

The next part of the book consists on four random papers cobbled together under the catch-all ‘History and Authors’. The only interesting one is Sandra Lapointe writing about Bolzano’s Logical Realism.

Finally we have three papers on ‘Specific issues’ (now the editor is *really* struggling to find an organising principle for her heap of contributions). Graham Priest has a short and thin piece on Revising Logic. Jc Beall, Michael Hughes, and Ross Vandegrift contribute another short paper, on Glutty theories and the logic of antinomies (how is this relevant to the volume? — ‘We shall argue that [the logic] LA reflects a fairly distinctive set of metaphysical and philosophical commitments, whereas LP, like any formal logic, is compatible with a broad set of metaphysical and philosophical commitments’). Finally, Tuomas Tahko writes on The Metaphysical Interpretation of Logical Truth: you’ll only like this paper if you think there is anything to be said for slogans like ‘A belief, or an assertion, is true if and only if its content is isomorphic with reality.’ Which I don’t.

So a pretty disappointing collection, one way or another. Save your pennies for some good haddock.
