---
title: "Encore #12: Advice on the book problem"
date: "2016-02-23"
page-layout: article
---

*During the lifetime of the blog, I have retired, which has meant that I lost the use of a university office to keep books -- and indeed I lost all the shelves in an adjacent teaching room which I also used. A major book cull had to follow, and then another. I posted my sorrows a number of times. Some excerpts ... leading to some wise advice about how to downsize your library!*

I'm having to try to sort out my philosophy library -- I can't start shelving yet another wall at home -- and that's a painful business. It's not just that there is a ridiculous number to sort through. It's also a matter of encountering long-past philosophical selves, and not quite wanting to wave them goodbye. In the seventies, I was mostly interested in the philosophy of language (though there are also many ancient philosophy books dating from then, and a lot of Wittgenstein-related stuff); from the eighties there is a great number of books on the philosophy of mind; from the nineties a lot of philosophy of science and metaphysics. Digging through these archeological layers I'm reminded of past enthusiasms -- not just of mine, but often quite widely shared enthusiasms which seemed philosophically rewarding at the time, but some of which now seem rather remote and even in some cases quite odd misdirections of energy. What creatures of fashion we are!

But at least in those more academically relaxed days I could follow my then interests wherever they led or didn't lead (I never got bored). Young colleagues now don't have the luxury: to get even their first permanent job they have to specialize, concentrate their resources, carve out a niche, build a research profile: and it takes more of the same to get promoted. Some feel constrained, lucky to have a job but trapped. The structures that we philosophers have allowed to be imposed on "the profession" (as we are now supposed to think of it) have thus come to be in real tension with the free-ranging cast of mind that gets many people into philosophy in the first place. What Marxists used to call a contradiction ...

---

I'm still trying to sort out my (tiny) study at home. It all takes ridiculously long. Not just because I have to decide what to give to the library/students/Oxfam (though that's difficult enough). But I find it impossible not to keep stopping over a book I haven't opened in years and begin reading. I'm of the same mind as Churchill, who wrote

> If you cannot read all your books, at any rate handle, or as it were, fondle them -- peer into them, let them fall open where they will, read from the first sentence that arrests the eye, set them back on the shelves with your own hands, arrange them on your own plan so that if you do not know what is in them, you at least know where they are. Let them be your friends; let them at any rate be your acquaintances. If they cannot enter the circle of your life, do not deny them at least a nod of recognition.

And those nods of recognition as I move the books from one shelf to another all take so much time!

---

[caption id="attachment_7610" align="aligncenter" width="500"] Chez Logic Matters, approximately[/caption]

So you start buying books -- I mean academic, work-related, books of one kind or another -- in your late teens. As retirement age looms you've been doing it for the better part of fifty  years. Suppose you average a couple of books a month. Not very difficult to do! You buy a few current books on topics that you are working on; books for reference; books you feel you should read anyway, given the ripples they are producing; books for seminars or reading groups you belong to; books it is useful to have to hand for teaching (the textbooks the kids are reading, or just useful collections of articles, before the days when everything was online). It very soon mounts up. Add in a few review copies, freebies, books given by friends, serendipitous finds rescued from the back of obscure second-hand bookshops (I got a set of Principia Mathematica that way). Then without any effort at all your modest library is steadily growing at over thirty books a year or more. But go figure: that's already around 1500 books as you get to the end of your career. I've been a bit more incontinent than some, but actually not a lot (especially as my interests have rather jumped about). Say I've acquired 1750 over the years. I've got rid of a few books from time to time, of course, though I've been absurdly reluctant to let them go: but overall, I've still probably got not far short of 1600. Which, I agree, is a quite stupid number to end up with -- but (as we've seen!) it's easy enough to end up there without a ridiculously self-indulgent rate of book-buying as you go along.

Soon enough, I'm going to finally lose an office; and we're trying to declutter at home anyway. So over the coming weeks and months I need to cut that number down. A lot. Halving is the order of the day. What to do?

Most of the Great Dead Philosophers and the commentaries can go -- I can't see myself ever being overwhelmed by a desire to re-read Locke's Essay, for example (and anyway I can always get the text online). But that doesn't make much of a dent, as I was never much into the history of philosophy anyway. I can get rid of some of the books-for-teaching, and old collections of articles whose contents are now instantly available on Jstor. But that doesn't help particularly either. So now it gets difficult.

It could just be neurotic attachment of course! But I like to think that there is a bit more to it than that. I'm sure I'm never going to seriously work on chaos again, so -- though it was great fun at the time -- I guess I will let the chaotic dynamics books go fairly easily. I'm also pretty sure that I'm never going to seriously work on the philosophy of mind again, and I've never done anything in epistemology: but just axing the phil. mind and theory of knowledge books seems to go clean against how I think of philosophy, as the business of trying to understand “how things in the broadest possible sense of the term hang together in the broadest sense of the term” as Sellars puts it. And anyway, some of the issues I'd like to understand better in the philosophy of mathematics seem to hang together with broader issues about representation and about knowledge. So perhaps I need to hang on to more of  the mind and knowledge books after all ....?

No, no, that way madness lies (or at any rate, swamping by unnecessary books). After all, Cambridge is not exactly short of libraries, even if I do dump something I later find myself wanting to read again! So, I'm just going to have to be brutal. A few old friends apart, if I haven't opened it in twenty years, it can certainly go. If it is just too remote from broadly logicky/phil mathsy stuff, it really better go too. Sigh.

---

... But now it is getting harder. I'm slowing down, and it is all getting more discombobulating. In some cases it is a matter of regretfully having to acknowledge that -- being realistic -- I am never going to have a year or so to really get my head again round *X* or *Y. *I'd love to really get to the point where I was back on top of the state of play in the philosophy of quantum mechanics (say); but it is never going to happen -- or at least, it's never going to happen if I am to have half a chance of finishing some logicky projects. So that whole area will have to remain a closed book, or rather a small pile of closed books. A cheering reminder of faded hopes, eh?

Then there are the books to which I still feel an odd attachment and find difficult to let go for no reason I can easily articulate. Irrational, as I've not read them for decades, and I'm surrounded by Cambridge libraries. For instance, I've just found myself rereading some of  Cornford's *Unwritten Philosophy*, which I must have bought in 1967, and not had occasion to read much since. I'm sure it is all very creaky: ancient philosophy has come such a very long way since when Cornford was writing (the essays date from the thirties and forties). I've long since lost touch, and my Greek has quite disappeared. And yet, and yet ... The charm of his writing still weaves its magic. No; *this* I think I will keep, just for a bit longer.

Back to the pile for sorting ...

---

Hello. My name is Peter and I am a bookaholic ...

Well, perhaps it isn't quite as bad as that. But I've certainly bought *far* too many books over the years. I've now given a great number away, but retiring and losing office space means there is still a serious Book Problem at home. We want to do some re-organization, which will mean losing book shelving there too. So lots more must go. Dammit, the house is for us, not the books. One hears tell of retiring academics who have built an extension at home for their library or converted a garage into a book store. But that way madness lies (not to mention considerable expense).

"A little library, growing larger every year, is an honourable part of a man's history. It is a man's duty to have books. A library is not a luxury, but one of the necessaries of life." Yes. But let "little" be the operative word!

Or so I now tell myself. Still it was -- at the beginning -- not exactly painless to let old friends go, or relinquish books that I'd never got that friendly with but always meant to, or give away those reproachful books that I *ought* to have read, and all the rest. After all, there goes my philosophical past, or at any rate the past I would have wanted to have (and similar rather depressing thoughts).

But I think I've now got a grip (*so at last, here's my advice to anyone else in the same position, needing to downsize*). It's a question of stopping looking backwards and instead thinking, realistically, about what I might want to think about seriously over the coming few years, and then aiming to cut right down to (a still generous) working library around and about *that*. So instead of daunting shelves of books reminding me about what I'm not going to do, there'll be a much smaller and more cheering collection of books to encourage me in what I might really want to do. The power of positive thinking, eh?

At least, that's the plan. I'll let you know how it goes.

*And in the event, I surprised myself. A few years on, I can remember only one occasion when I've been kicking myself, really regretting some book I got rid of. Though I confess I do seem to have acquired more books. Can't imagine how that happened. Time, I suppose, for another sort-out ... *
