---
title: "A few books of the year ..."
date: "2021-12-30"
page-layout: article
---

The lexicographer Susie Dent, asked for a word to sum up 2021, offered *mubble fubbles*. She explained: “It’s a 16th-Century word that means a sense of impending doom or despondency; never quite knowing what’s around the corner.” Indeed. There’s been quite a lot of that about. So a year when, among other things, reading has perhaps meant more than ever. What has worked particularly well for me?

I’m a pretty difficult person to buy books for, but Mrs Logic Matters had a triumph with Ross King’s *The Bookseller of Florence*. Here's the whole business of manuscript-making and the birth of the printed book, the walk-on cast of familiar characters from Medici Florence, the other glimpses of Renaissance Florentine life, and on top of that (what I guess I should have known more about and didn’t) the rediscovery of ancient authors and Plato in particular. What’s not to like? Well, more illustrations would have been a bonus! But the book zips along, and I much enjoyed it.

Among the travel escapism, a favourite was Eric Newby’s *A Small Place in Italy*, a sketch of vanished rural life of post-war Italy, written with his characteristic verve and lightness of touch.

The story of how Eric earlier met his wife Wanda when an escaped  prisoner of war is, of course, told in his earlier wonderful *Love and War in the Apennines. *But I only this year discovered that she too wrote her own story, *Peace and War: Growing Up in Fascist Italy*. It's a wonderfully evocative read.

I found *House of Glass: The story and secrets of a twentieth-century Jewish family* utterly compelling -- I had put off reading it when it first came out in 2020. But once I started I could hardly put it down and read it in a couple of days.

Hadley Freeman writes, not quite in the register of the journalist she is, but very plainly and directly -- which somehow makes the story she has to tell all the more affecting. If you haven't read it, do!

Edmund de Waal's letters to Count Moïse de Camondo -- so, here uncovering layers of the story of another twentieth-century Jewish family -- are finely carved miniatures of extraordinary writing. Like *netsuke*, mused Mrs Logic Matters. “A poetic meditation on grief, memory, and the fragile consolation of art,” wrote one reviewer, so aptly.

What about novels? There were some rereadings, some entertainments, some modern classics, some newly published books. But if pressed to pick the three I most *enjoyed* reading at the time, for one reason or another, then it might well be ...

 I surely don’t need to explain any of these! Jane Gardham is always wonderful, and *Bilgewater* (new to me) is a delight. *Spring* is surely the best of Ali Smith’s Seasonal quartet. And Robert Harris is just ridiculously readable (and you get to learn a lot about Roman water systems into the bargain!).

And the year ends just as I am finishing *Anna Karenina* for the fifth (or is it the sixth?) time. And having tried the Pavear/Volokhonsky translation on my previous reading a dozen years ago, I’ve returned to the old Rosemary Edmonds version. How much I have vividly remembered; how much has struck me anew.

One thing I had quite forgotten. Anna has just thrown herself under the train. “The candle ... flickered, grew dim and went out for ever.” And the very next page, Tolstoy quite brutally thrusts us back in media res. Of all things, Levin’s brother Koznyshev is fretting about his newly published book *Sketch of a Survey of the Principles and Forms of Government in Europe and Russia, *the fruit of six year’s labour, which seems to have fallen stone dead from the press. Dreadful things happen not so far from us, and the world has to rattle on, and our small concerns with it.

And yes, dreadful things are happening out there, it is difficult to avoid the mubble fubbles. Yet here’s me, of all things, fretting about the last few paragraphs of *Sketch of a Survey of the Principles and Forms of Logic -- *or the Study Guide. Such is life!
