---
title: "Five books -- Philosophical Logic, from the back catalogue"
date: "2018-04-28"
page-layout: article
---

As noted in a recent post, I've  recently been reading an old discussion by Geach of ‘any’ vs ‘every’. I'd largely forgotten what his view was -- I hadn't looked at my dusty copy of the relevant book for decades. But that got me thinking: what five books on philosophical logic from back in the day (say, the quarter century or so on from 1950), books that are little read these days, are still worth revisiting, and still could be/should be recommended to budding philosophers to round out their education?

Here are five suggestions. No doubt I've forgotten about some that are equally worthwhile. Given more time (and fewer things I ought to be doing instead), I might have been inspired to write longer, separate, blog posts on each of these books. But I'll have to be content with a brief paragraph on each. So taking them in order of publication, let's begin with ...

**Peter Geach, *Reference and Generality ***(Cornell U.P., originally 1962: third edition 1980). Cheerfully abuses some ideas to be found in various medieval logicians and in early Russell, in order to bring out the wisdom to be found in Frege. Tendentious, and you'll want to read Gareth Evans on pronouns as a counterbalance, but this is full of good things, and written with great verve and clarity.

Next, **Arthur Prior, *The Objects of Thought***  (OUP, 1971). This is Prior's unfinished, and somewhat uneven book, edited from his drafts after his death by Geach and Kenny. If you don't know it, the book is divided into two parts. The first concentrates on the logical properties of propositions, their relation to facts and sentences (Prior an early enthusiast for Ramsey). The second part is on  intentionality and discusses the relationship between different theories of naming and different accounts of belief. Of course these have been the topics of intense investigation in the near half-century since Prior was writing -- but he is still definitely engaging and thought-provoking.

The next might seem to be an odd suggestion for an under-read book from those days. Doesn't every well-brought up budding philosopher read their Quine? Well, not so much these days, or that's the impression I get. And if they do read him, they probably miss what seems to me one of his most engaging books --** W.V.O Quine, *The Roots of Reference*** (Open Court, 1973). Even if you dispute the details the way Quine handles it, his project of considering a sequence of more and more sophisticated linguistic practices and asking at what level we need to discern reference to objects still seems to me one that it is very profitable to pursue. Quine's wonderful style is, as always, a bonus.

For a very different book, written at the end of the  heyday of one kind of ‘linguistic philosophy', we have **Alan White,  *Modal Thinking ***(Blackwell, 1975). As White says in the preface “Much attention has recently been given to formal modal logic and to various of its problems, but little to the actual nature of those concepts of our everyday thinking for which the formal logic was ostensibly designed”. Which is still pretty much as true now as it was then. White has chapters on ‘possibility’, ‘probability’, ‘certainty’, ‘necessity’, ‘must’, ‘obliged’, ‘ought’, ‘the nature of modality’. His linguistic claims are not always entirely compelling; but there is a lot of philosophically important concept-mapping and distinction-drawing. Again, a relatively easy read. (If you like Ian Hacking's wonderful paper ‘All kinds of possibility’, then you'll get a lot out of White's book too – and if you don't know Hacking's paper, it really is a must-read!)

Finally -- and not just as an act of Cambridge piety -- let me mention a book which is probably gathering as much dust in your library as the other four combined: **Casimir Lewy, *Meaning and Modality*** (Cambridge, 1976). Although the last published of the five, this is by far the most old-school of the books, based on lectures that Lewy had famously been giving in Cambridge for over twenty years. And it is an austere book. For example, Lewy expends a lot on ink on the relationship  between the claims *‘vixen’ means ‘female fox’, ‘vixen’ means female fox*, and *the concept of being a vixen is identical with the concept of being a female fox*. It is left up to the reader to draw the moral from these discussions for more substantive claims of philosophical analysis. But still, it seems to me that the philosophical distinctions Lewy draws out from his apparently thin examples remain very important ones -- and ones you still frequently find people getting confused about (‘confused’, in a strong Polish accent, being a favourite word of his). The final chapters on entailment -- and Lewy's forgotten paradoxes of entailment -- are still well worth revisiting too.

So there are my five recommendations -- any other suggestions of overlooked books on philosophical logic from that era that we should blow the dust off?
