---
title: "Forgetting Turgenev?"
date: "2018-11-08"
page-layout: article
---

[
](https://logicmatters.net/wp-content/uploads/2018/11/a67ef6f51857e94ead545e3ece79d1a3.jpg)Isaiah Berlin writes so well in his* Russian Thinkers* about Ivan Turgenev. Yes, Turgenev *is — *there on the surface — “a writer of beautiful lyrical prose, ... the elegiac poet of the last enchantments of decaying country houses and of their ineffective but irresistibly attractive inhabitants, the incomparable story-teller with a marvellous gift for describing nuances of mood and feeling, the poetry of nature and of love”. We can indeed love him for that. But there is so much more. It is not for nothing that Turgenev's books were so controversial when they appeared and (at least for Russians) long remained so. Yes, as Berlin puts it, “unlike his great contemporaries, Tolstoy and Dostoevsky, he was not a preacher and did not wish to thunder at his generation.” But he was deeply engaged from the beginning “with the controversies, moral and political, social and personal, which divide the educated Russians of his day; in particular, the profound and bitter conflicts between Slavophil nationalists and admirers of the west, conservatives and liberals, liberals and radicals, moderates and fanatics, realists and visionaries, above all between old and young. He tried to stand aside and see the scene objectively. He did not always succeed. But because he was an acute and responsive observer, self-critical and self-effacing both as a man and as a writer, and, above all, because he was not anxious to bind his vision upon the reader, to preach, to convert, he proved a better prophet than the two self-centred, angry literary giants with whom he is usually compared, and discerned the birth of social issues which have grown world-wide since his day.” (For “Slavophil nationalists vs admirers of the west” read “English nostalgists vs those who hanker after an ideal of ‘Europe’”: the bitter conflicts are still with us!)

I wonder though how much Turgenev is read now, at least here in the England he visited a number of times and which used to much admire him. Is even the great *Fathers and Sons *still on people’s ‘must read’ lists (their real lists, I mean, recording live intentions!)?  Or has cultural amnesia set in here too?

Turgenev was born on November 9th, in 1818 (October 28th, old style). So it is his bicentenary today -- an occasion which seems to be passing here almost entirely unremarked. But I for one will be raising a glass of wine in his memory, as I sit down to reread once more his so evocative, so sad, novella *First Love *(wonderfully translated, in itself a work of love, by Isaiah Berlin).
