---
title: "What Frege didn't tell you"
date: "2013-09-29"
page-layout: article
---

*Why is Venus star multinominous and called both Phosphorus and Vesper?*

Venus is multinominous, to give example to her prostitute disciples who so often, either to renew or refresh themselves towards lovers, or to disguise themselves from magistrates, are to take new names. It may be she takes many names, after her many functions. For as she is supreme monarch of all love at large (which is lust) so is she joined in commission by all mythologists with Juno, Diana, and all others, for marriage. It may be, because of the diverse names of her affections, she assumes diverse names to her self. For her affections have more names then any vice, to wit Pollution, Fornication, Adultery, ... Incest, Rape, Sodomy, Masturbation, and a thousand others. Perchance her diverse names shew her appliableness to diverse men. For Neptune distilled and wept her into Love, the Sun warmed and melted her, Mercury persuaded and swore her; Jupiter's authority secured, and Vulcan hammered her. As Phosphorus she presents you with her *bonum utile*, because it is wholesomest in the morning; as Vesper, with her *bonum delectabile* because it is pleasantest in the evening. And because industrious men rise and endure, with the Sun, their civil business, this star calls them up a little before, and remembers them again a little after for *her* business.

John Donne, Problem XI, *Paradoxes and Problems *(c. 1590, published 1633) [Oddly, he in fact has "Hesperus" when he should have written, as here, "Phosphorus"!]
