---
title: "Jonathan Raban, 1942--2023"
date: "2023-01-19"
page-layout: article
---

I have hugely admired Jonathan Raban ever since I first read *Old Glory* forty years ago, and have praised his books here before. For example, I wrote this a few years ago (editing a little):

---

Now, how did that happen? Wanting to re-read Jonathan Raban's *Coasting*, his evocation of a journey of discovery sailing round Britain, first published over thirty years ago, I just found a couple of days ago that our copy has disappeared from the shelves. A mystery:  I wonder what happened to it. So it is very good to discover that the book has recently been [republished, along with four other books by Raban, by Eland](https://www.travelbooks.co.uk/search?q=jonathan%20raban), in rather handsomely produced paperbacks. I remember the book as being extraordinarily well written. The blurb on our new copy tells me that  Raban here “moves seamlessly between awkward memories of childhood as the son of a vicar, a vivid chronicle of the shape-shifting sea and incisive descriptions of the people and communities he encounters. As he faces his terror of racing water, eddies, offshore sandbars and ferries on a collision course, so he navigates the complex and turbulent waters of his own middle age. Coasting is a fearless attempt to discover the meaning of belonging and of his English homeland.” Which indeed is how I recall the book. I look forward to it!

I've been put in mind to read *Coasting* again because I have recently been re-reading with great  enjoyment two of Raban's other books that *are* on our shelves (as it happens, another two of the five that have been republished by Eland). First there was *For Love & Money*, which is subtitled “Writing, Reading, Travelling: 1969–87”, and which reprints some early reviews and occasional pieces. The writing is consistently humane and insightful, but more than that, it is just so beautifully readable (the number of times I thought, “I wish I could write even half as well”). And then there was Raban's early masterpiece, *Old Glory* from 1981, notionally recounting his voyage down the Mississippi in a small boat.

I say “notionally” as this complex work is lightly disguised as a straight travel book, a literal recounting of a journey taken. But the one-time English literature lecturer warns us clearly enough. One of the epigraphs of the book is from T. S. Eliot (writing of the  Mississippi), starting “I do not know much about gods; but I think that the river/Is a strong brown god ...” The other epigraph is from Jean François Millet: “One man may paint a picture from a careful drawing made on the spot, and another may paint the same scene from memory, from a brief but strong impression; and the last may succeed better in giving the character, the physiognomy of the place, though all the details may be inexact.”

So we are set up for this to be a mythic tale (“the river/Is a strong brown god”)  and for the “Jonathan Raban” who features as the narrator and his adventures to be a very loose rendition of the author and his own journey (“all the details may be inexact”). And a mythic tale is indeed what we get, an ordeal by water, with auguries and signs, battles fought, even a princess won (but also lost, for this is a flawed epic, and the journey ends in emptiness as the river becomes the sea). But woven together with this are encounters with old American myths of frontiers and journeys. And, presciently -- so striking, reading again now, nearly forty years later --  Raban notes the “deep, unsatisfied capacity for hero-worship” that makes many Americans long for a “strong” leader, a saviour. This is a many layered book, artful in the artlessness of its transparent prose. Wonderful.

---

[](https://logicmatters.net/wp-content/uploads/2011/03/raban.jpg)And yes, I did indeed hugely enjoy re-reading *Coasting*. But Raban’s best book is surely *Passage to Juneau* (and this is saying something, for he is one of the very finest writers of non-fiction prose in English of recent decades). This is his 1999 book, notionally about sailing his 35ft ketch up the Inside Passage, from his home in Seattle to Juneau in Alaska. But like all great travel books, it is about so very much more -- the voyage of Captain Vancouver that he is retracing, about the original Indian inhabitants and their relationship to the sea, about the idea of the sublime, about the death of his father, about his feelings for his young daughter, about other escapees he encounters at the edge of the world. And as ever “journeys hardly ever disclose their true meaning until after -- and sometimes years after -- they are over”. A masterpiece. Read it.

---

Jonathan Raban died a few days ago, aged 80. A stroke some years ago kept him confined to a wheelchair, an ironic fate, [as the Guardian obituarist notes](https://www.theguardian.com/books/2023/jan/18/jonathan-raban-obituary), for a writer who saw his journeys as “a means of escape, freedom and solitude, I could be happy … in a way I couldn’t be at home”. But he kept writing. And as [another Guardian tribute tells us](https://www.theguardian.com/books/2023/jan/18/jonathan-raban-travel-writer-and-novelist-dies-aged-80), “Raban’s memoir *Father and Son* is due to be published this autumn. ... He is survived by his daughter, who said that on his last day he saw a bald eagle swooping and playing in the wind from his hospital window, before it flew off over Puget Sound, off Washington state.”
