---
title: "Encore #17: Larkin was right ..."
date: "2016-03-02"
page-layout: article
---

*The old always think the world is going to the dogs. I try to resist. Sometimes, though, it is difficult. *

### **Going, gone** (Nov 23, 2011)

The main road west from Cambridge used to go down the main street of the market town of St. Neots before crossing the river. But there has long since been a bypass, and it is quite a while since I've chosen to turn off it to take the old route. But I wanted a coffee, so today I stopped in the town and went to a scruffy and run-down branch of Caffè Nero on the large market square.

Their espresso wasn't very good, but that's probably only to be expected. What I hadn't really bargained for was just how depressing the view out to the square is now. Even on a bright autumn morning, it looked as scruffy and run down as the coffee shop. This was never a very wealthy place: but there was once some small domestic grace to the surrounding mostly nineteenth century buildings. But now many of them are quite disfigured with the gross shop-fronts of cheap stores, and others look miserably unkempt. There's a particularly vile effort by the HBSC bank, which gives a special meaning to “private affluence and public squalor” -- only an institution with utter contempt for its customers and their community could plonk such a frontage onto a main street. Where once even small-town branches of banks were solid imposing edifices in miniature, with hints of the classical orders here and a vaulted ceiling there, signifying permanence and  reliability, now they are seem to take pride in having all the visual class of a here-today, gone-tomorrow betting shop. How appropriate.

And the square itself (like so many other urban spaces in England) seems to have been repaved on the cheap, with the kind of gimcrack blockwork that always seems, a few years in, to settle into random waves of undulation. The bleakly open space cries out for more trees to surround it, and inviting wooden seats. But no, on non-market days it is just the inevitable carpark.

Next to coffee shop, still on the square, a horrible looking cafe is plastered outside with pictures of greasy food. I walk a little further down the road before driving on. It is a visual mess. Even Marks and Spencer manages a particularly inappropriate shout of a shop-front, as sad-looking charity shops cringe nearby. Could *anyone* feel proud or even fond of this street as it now is?

A couple of hundred yards away there are lovely water-meadows by the bridge over the river, and some fancy residential developments. On the outskirts of town the other side, as the road leaves towards Cambridge, there is a lot more quite expensive-looking new housing (though heaven knows how it will seem a few years hence). But the town centre itself is in such a sorry state.

“Most things are never meant,” wrote Larkin when he foresaw something of this in ‘Going, going’. And we -- I mean my generation, for it is we who were in charge -- surely didn't mean this, for the hearts of old country towns like St. Neots (or the larger next town,  Bedford) to become such shabby, ugly, run-down places. But it has happened apace, all over the country, and on our watch.

*Philip Larkin reads [‘Going, going’](https://www.youtube.com/watch?v=dQkKr_9jcNs).*
