---
title: "The last dance"
date: "2014-12-31"
page-layout: article
---

[embed]http://youtu.be/BsFzxPzlqQA[/embed]

It isn't all High Culture chez Logic Matters. Oh no. Perish the thought. For a start, from September to December we are devotees of *Strictly. *

That's *Strictly Come Dancing *(the original, BBC, version of *Dancing with the Stars, Ballando con Le Stelle, *and over forty other versions). So it is all glamour and glitter, sequins and sexy outfits, fake tans and gallons of hair products, tears and tantrums. And that's just the guys.

Each season we start watching with the same amused detachment. We tell  ourselves that *this* year we won't get hooked, *this *year the quarter-celebrities (most of whom we've never heard of) are an uninteresting/unattractive bunch, *this* year the silliness of the whole palaver is just too much ...

And yet ...

Like millions others, we find ourselves tuning in every Saturday. And as the no-hopers and the joke participants are voted off the show, we get more enthused. We start watching *It Takes Two  -- *the admirably warm and amusing weekday programmes interviewing participants, explaining the finer points of choreography, and generally having fun. Which can reveal that an impossibly glamorous pro dancer has a very sharp self-deprecating wit and is endearingly happy to send herself up, while a seemingly equally glamorous member of a boy band is self-doubting and charming. And that this soap actor is as two-dimensional as his character, but that that footballer's wife is plainly a sweet girl who is delightfully surprised to find that she *can* dance. You get engaged with the contestants (and indeed with some of the pro dancers), with the 'journeys', with the increasingly terrific dances. Fellow devotees will know how it goes ...

... And if you don't, well, here for your holiday delight is the very final dance of the series. Down to the last three couples, the final contestants can choose their favourite dance to perform again. Here Simon Webbe and Kristina Rihanoff reprise their Argentine tango. They didn't win *Strictly 2014*. But this was the dance of the series, from a man who three months before seemingly had two left feet and zero confidence. Who has come so far. And the result is really rather moving ... Enjoy!

And Happy New Year!
