---
title: "Meeting Leibniz on the white road."
date: "2022-12-15"
page-layout: article
---

The non-fiction, non-logic, book which I have most enjoyed this year is the one I have just finished, Edmund de Waal’s remarkable *The White Road *(from 2105). I was enticed by the jacket description -- the author “sets out on a quest - a journey that begins in the dusty city of Jingdezhen in China and travels on to Venice, Versailles, Dublin, Dresden, the Appalachian Mountains of South Carolina and the hills of Cornwall to tell the history of porcelain. Along the way, he meets the witnesses to its creation; those who were inspired, made rich or heartsick by it, and the many whose livelihoods, minds and bodies were broken by this obsession. It spans a thousand years and reaches into some of the most tragic moments of recent times.” It is indeed a quite remarkable read, intriguing and then -- when it touches on some of the human disasters of the last century -- distressing and moving. As you would expect from *The Hare with Amber Eyes* or *Letter to Camondo*, it is quite wonderfully well written -- de Waal’s often short, beautifully crafted, paragraphs as carefully arranged as those white porcelain pots of his in their vitrines. Which makes the later pages all the more telling.

---

I hadn’t expected to bump into Leibniz on the road that takes us to seventeenth century Chinese porcelain and the attempts of the Jesuit missionaries to discern its secrets. But then I didn’t know that one of the few books Leibniz published in his lifetime was the *Novissima Sinica* -- the *very* latest news from China! Unlike a Descartes who thinks that what is most fundamental is common to us all and is available through rational reﬂection, Leibniz is committed to the idea that the growth of knowledge will come from bringing together different perspectives, different ways of thinking, about our shared universe. So he has an extensive correspondence with the Jesuit mission, and (to quote de Waal) writes that

> all this activity around China ... is ‘un commerce de lumière’; enlightenment stretching both ways. This is a tremendous idea and a beautiful image, one of an equality of concerns, a correspondence of civilisations, of light.
> 
> As Leibniz writes to his friend Sophie, the wife of the elector of Hanover:
> 
> *I will thus have a sign placed at my door with these words: bureau of address for China, because everyone knows that one only has to address me in order to learn some news. And if you wish to know about the great philosopher Confucius ... or the drink of immortality which is the philosopher’s stone of that country, or some things which are a little more certain, you only have to order it.*
> 
> He is one of the gatekeepers. If you want to know about Chinese mathematics, the I Ching as a coding of chance events, Chinese characters and their relationship to hieroglyphs, you go to him. Leibniz has been to visit Father Francesco Grimaldi in Rome, just back from the emperor Kangxi’s court, and written up copious notes on fireworks, glass and metal. I realise to my surprise that my hero, the father of rationalism, is anxious to keep ahead in this new, congested field of China Studies.

So Leibniz knows about the problem of porcelain. Later, he corresponds with the mathematician Ehrenfried Walter von Tschirnhaus, who has a sideline experimenting on how to create porcelain here in Europe, and almost gets there. And the extraordinary story continues, that was all new to me, as I followed *The White Road. *
