---
title: "Until the lights go out"
date: "2015-08-18"
page-layout: article
---

"If you don't know the exact moment when the lights will go out, you might as well read until they do." I think I will adopt that as my motto. It's from Clive James, in the Introduction to his *Latest Readings *which comes out next week, a little book that reflects on a delightfully idiosyncratic range of authors and books. James is still reading, and writing too with humanity and wit and insight and, as we say, with undying enthusiasm. Except our author *is* dying. Though he confesses to feel “the childish urge to understand everything”, an urge which “doesn't necessarily fade when the time approaches for you to do the most adult thing of all: vanish”.

I've been living the last few weeks with Clive James's previous book, *Sentenced to Life. *We share the same still-small town-within-a-city, share similarly eclectic tastes (or perhaps not so much eclectic as tastes that place us in the same generation and in somewhat overlapping worlds), and share some favourite authors: we also share rather more that I wish we didn't. So I have been finding these last poems (if that's what they prove to be) speaking particularly directly.  Poignant, regretful, looking death in the face without illusion. And very accessible too  – as if, by imposing such clear form, such unabashed rhyming structures, our poet is making his stand against the formlessness to come. There is no false consolation here.  But still (as Blake Morrison puts it in a review) “When in death, we’re in the midst of life – that’s the recurrent, bleakly hopeful theme.”

Not that it is all bleak. Far from it. There is still Jamesian fun to be had: his Compendium Catullianum, for example –

> My girlfriend's sparrow is dead. It is an ex-sparrow.

Though after the jests, we are back to a recurrent thread: “For I ...

> Miss you the way you miss that stupid bird:
> Excruciating. Let's live and let's love.
> Our brief light spent, night is an endless sleep.

And our poet, before the lights go out, is so vividly aware of the small particulars of his ever-narrowing world:

> Once I would not have noticed; nor have known
> The name for Japanese anemones,
> So pale, so frail. But now I catch the tone
> Of leaves. No birds can touch down in the trees
> Without my seeing them. I count the bees.*”*

I can recognise that. And so much else here.

---

I would quote whole poems from *Sentenced to Life*  if I could. But [here is one of the last poems](http://www.newyorker.com/magazine/2014/09/15/japanese-maple), one of my favourites, first published a year ago in the New Yorker.
