---
title: "Lockdown recommendations"
date: "2023-10-20"
page-layout: article
---

In 2020, I wrote a number of lockdown blogposts “from a small corner of Cambridge”. As I said at the time, we were very fortunately placed compared with many, very comfortably housed, with Midsummer Common and the river almost on our doorstep, and used to quiet life. There was little really to add about our minimal doings as the months rolled on under various degrees of constraint. However, along the way, I did comment on various things we'd been watching, listening to, or reading. So here is some of what I said ...

---

*When I put Emily Thomas's excellent *The Meaning of Travel* away alongside other travel books, I found a copy of Eric Newby's *Love and War in the Appenines.* I couldn't remember ever having read it before. Here's one of the advantages of age; amnesia happily makes your bookshelves renew themselves!

Newby tells of his adventures as a prisoner of war and then afterwards, when he takes to the mountains, sheltered by courageous Italian peasants, in the process meeting Wanda who later becomes his wife. This perhaps isn't one of the reflective, philosophically-coloured, travel books: but Newby's story is very engaging as he draws some memorable characters, and sketches both a landscape and a lost way of life. I rattled through it in a few days; a very enjoyable distraction from these differently troubled times.

---

We were much looking forward to a Wigmore Hall concert a couple of days ago with the countertenor Iestyn Davies and the lutenist Thomas Dunford. But that of course was cancelled like all London concerts. To see what we missed, there are some really nice videos of Iestyn Davies singing [on his site here](http://www.iestyndavies.com/watch/2017/11/16/iestyn-davies-npr-music-tiny-desk-concert). And looking ahead we've had to cancel our usual spring stay in Cornwall, which is a sad (apart from other reasons, they are now rightly strongly asking visitors to stay away). With that missed trip at the front of my mind, I picked up again, and read from end to end, a book (not Cornish but at least West Country in theme) that we bought on one trip in [the delightful indie bookshop in Falmouth](https://www.falmouth-bookseller.co.uk) -- namely Alice Oswald's *Dart*, that follows the river and its people from source to sea. This is a wonderfully ambitious  many-layered, many-voiced, poetic journey full of allusion and mythic echoes and observation of nature and more: no wonder it won the T.S. Eliot Prize. This week's warm recommendation!

---

In the London Review of Books a couple of issues ago, there was [a strangely timely review](https://www.lrb.co.uk/the-paper/v42/n04/erin-maglaque/inclined-to-putrefaction) of a book on the plague in Florence in the early seventeenth century. The plague approached the city, only temporarily halted by the natural barrier of the Appenines

> 
On the other side of the mountains, Florence braced itself. The officials of the Sanità, the city’s health board, wrote anxiously to their colleagues in Milan, Verona, Venice, in the hope that studying the patterns of contagion would help them protect their city. Reports came from Parma that its ‘inhabitants are reduced to such a state that they are jealous of those who are dead’. The Sanità learned that, in Bologna, officials had forbidden people to discuss the *peste*, as if they feared you could summon death with a word. Plague was thought to spread through corrupt air, on the breath of the sick or trapped in soft materials like cloth or wood, so in June 1630 the Sanità stopped the flow of commerce and implemented a *cordon sanitaire* across the mountain passes of the Apennines. But they soon discovered that the boundary was distressingly permeable. Peasants slipped past bored guards as they played cards. In the dog days of the summer, a chicken-seller fell ill and died in Trespiano, a village in the hills above Florence. The city teetered on the brink of calamity.

> By August, Florentines were dying. The archbishop ordered the bells of all the churches in the city to be rung while men and women fell to their knees and prayed for divine intercession. In September, six hundred people were buried in pits outside the city walls. As panic mounted, rumours spread: about malicious ‘anointers’, swirling infection through holy water stoups, about a Sicilian doctor who poisoned his patients with rotten chickens. In October, the number of plague burials rose to more than a thousand. The Sanità opened *lazaretti*, quarantine centres for the sick and dying, commandeering dozens of monasteries and villas across the Florentine hills. In November, 2100 plague dead were buried. A general quarantine seemed the only answer. In January 1631, the Sanità ordered the majority of citizens to be locked in their homes for forty days under threat of fines and imprisonment.

And so it went (the review is really gripping). And so, with some rather marked similarities though a thankfully less vicious infection, it goes. The coronavirus lockdown has now reached Cambridge. Surely some days after it should have done, and surely it is still less stringent that it ought to be, given the experience of Italy now. The English, or rather too many of them it seems, are not conducting themselves well. Some national myths are being unmade as we watch. Grim times.

---

And there has been much to divert us -- a nice mix of the occasional streamed High Culture and fun (the *Così *from the Royal Opera House scored very well on both counts!). Hilary Mantel's *The Mirror and the Light* arrived a couple of weeks ago, but we haven't yet tackled that, because we both decided we wanted to re-read from the beginning of the trilogy. So Mrs Logic Matters has been diving back into *Wolf Hall *with great enjoyment. And I've just finished re-reading another weighty book -- Arnold Bennett's *The Old Wives Tale. *Is Bennett much regarded these days? But he writes so well --- with irony yes, but insight -- about ordinary lives, the way our upbringings so constrain us, about the passing of the years, the compromises we make. He creates a very human world that you find yourself swept up in.  This week's warm recommendation, then.

---

[](https://logicmatters.net/wp-content/uploads/2020/03/71rmA65LocL._AC_SY679_.jpg)Distractions are needed. There's a lot of High Culture being provided free online as various opera houses open up their back catalogue of recorded performances for streaming. For instance, we  caught the *Swan Lake* from Paris Opera.  But mostly we are in the mood for unchallenging comfort viewing. So we watched the 2009 BBC adaption of *Emma *again. We enjoyed it enormously (thinking it even better on a second viewing). Of course you can cavil. You can argue that no filmed version can do even a quarter justice to Austen's knowing narration as she slips in and out of her character's minds. You can complain that, in this *Emma, *Hartfield is too grand, Mr Elton too caricatured, and the like. But as Austen adaptations go, this is surely as true to its original as any. And Romola Garai is terrific in capturing Emma's vivacity and youth and fundamental good-heartedness (and shortcomings!). So that is this week's recommendation for something to distract you!

---

It was my birthday a couple of weeks ago. Once upon a time in olden days, BC, we'd thought of going up to London to visit the Artemisia exhibition at the National Gallery. Well, that didn't happen, either the exhibition or the visit. But as a present I did get[ the catalogue](https://www.nationalgallery.co.uk/products/artemisia-catalogue/p_1048656) which has been published and is terrific. In fact, aren't many art exhibition catalogues these days just wonderful? Quite beautifully produced, with often very readable and illuminating essays (which, judging by the characteristic pages of endnotes, are grounded in a huge amount of scholarship lightly worn), and all for the price of a couple of exhibition entry tickets. This book is no exception. We saw the [Artemisia exhibition in Rome](http://www.museodiroma.it/en/mostre_ed_eventi/mostre/artemisia_gentileschi_e_il_suo_tempo) a few years ago; and yes of course it is a great pity not to experience again the visual impact of some of those dramatic canvasses face to face (and that seems the appropriate description). But this catalogue is much more than a small consolation: it's an art-work in itself and very enjoyable. So that’s this week’s lockdown book recommendation!

---

We can, of course, get books delivered here by post. But where's the fun in that? One small everyday pleasure we really miss is getting to second-hand charity bookshops; we much enjoy the serendipity, the chance discoveries. The wonderfully well-run and well-stocked Oxfam bookshop in Walden is a particular favourite, and in normal times we drop in there every three weeks or so. And when in Cornwall [ah, those were the days!], there is a terrific bookshop at the National Trust house at Trelissick near St. Mawes. A couple of years ago, we happened to be there when someone came in to donate a paperback set of Helen Dunmore's first ten novels (obviously brand new); I snapped them up within a minute, having by chance just finished and much admired one of her later novels, *Exposure*. I have been reading those earlier novels with great pleasure over the intervening months. And I've just finished *Counting the Stars, *Dunmore's imagining of Catullus and his obsession with Clodia. I'm not sure that this is her *most* successful novel; and arguably her Catullus -- for all his obsession -- seems a mite too tame, lacking some of the fury and satiric energy that drives the poetry. But I can still recommend it for a spring evening read, far from Rome!

---

I imagine that we won't be going to concerts, for example, for many months. It’s really good to see, then, that Wigmore Hall are planning a series of twenty lunchtime concerts (one or two performers and no audience, broadcast live and then available for video streaming) for a month.   I wonder, though, if they are trying to tell us something in having the series culminating  by rending our hearts in a performance of *Winterreise*? In the meantime, though, some unalloyed musical pleasure. The Chiaroscuro Quartet have released a disc of the first three of Haydn’s late great Op. 76 quartets. This is wonderful music and here played with same insight and verve and delight and (appropriately!) light and shade as the Chiaroscuro’s earlier recording of the Op. 20 quartets. Something, then, to relieve the gloom of these troubled days for an hour, and for more hours of repeated listening! Warmly recommended.

---

The latest issue of the London Review of Books* arrives. Of course, I could already have read it on the iPad. But there still is something very pleasing about sitting over coffee with the elegantly produced paper edition (even if this is at home rather than out at a café). Yes, the *LRB* can be idiosyncratic and provoking (though mostly in a good way). I will usually dive into most of it. Sometimes -- though, trying to be realistic, not as often as I’d like -- I’m even spurred on to buy one of the books reviewed. A piece in the current issue entices me to send off for a copy of the poet A. E. Stalling’s recent collection *Like*. I confess I had not heard of her before. [Added 2023: I loved the book -- and enthusiastically recommend her selected poems *This Afterlife*.]

In the same post as the *LRB*, a copy of the newly paperbacked *Fleishman is in Trouble* by Taffy Brodesser-Akner. Praise was heaped when first published. But Mrs Logic Matters, fifty-something pages in, is not at all impressed; she rarely gives up on a book, but has already passed it on to my pile. [Added 2023: She was dead right.]

I’ve just been looking for our copy of Tony Judt’s wonderful *The Memory Chalet*. Where can it possibly have gone? It surely can’t accidentally have been given away in one of those many piles of books that have gone to Oxfam in the last few years. I find losing or misplacing a book that I’ve been emotionally affected by to be strangely dismaying, even if the copy can be readily replaced. We’ve both searched high and low, and still no sign. [Added 2023: I did buy another copy. So, of course, now we have two copies.]

---

*I’ve been struck by some of Vassily Kandinsky’s paintings for a long time. But I knew really embarrassingly little about his background, life and thought when I chose his *Blue Painting* for the cover of *IFL2*. So I've been reading the large illustrated book of essays edited by Helmut Friedel and Annegret Hoberg. Which perhaps tells me just a bit *more* than I needed to know.

But, with some judicious skimming, the essays are indeed fascinating for someone as ignorant as I am about the birth of modernism and its roots. And the book’s many reproductions of paintings and other artworks are terrific. Art books these days can be produced to a wonderful standard -- cheaply too, at least for someone used to academic book prices, even for student texts.

---

No concerts to go to. Wigmore Hall's series of streamed concerts has included some wonderful occasions, most recently Mitsuko Uchida's playing of two Schubert sonatas. Initially, being able to see so many concerts online in lockdown seemed terrific: but lately, I’ve been feeling that they somehow emphasized what we were missing by not being able to go to a live performance shared with an audience. Others have said the same.

Of CDs released in recent months, I've kept coming back to Supraphon's boxed set of the [Smetana Quartet playing the Beethoven quartets](https://www.supraphon.com/articles/307-beethoven-s-complete-string-quartets-by-the-smetana-quartet) (recorded between 1976 and 1985), playing of the greatest humanity and insight. The tradition of Czech string quartets is indeed extraordinary.

---

The third instalment of Hilary Mantel’s Tudor trilogy remains on the coffee table. But it’s  time to decide who is going to read it first, as we have now both read Wolf Hall* and *Bring Up The Bodies* again. And we have independently both been *very* struck by how much we’ve got out of rereading them -- appreciating them, if anything, even more the second time around. The writing really is stunningly good. So that’s this week’s (*very* unoriginal) semi-lockdown reading recommendation: if you have been wondering about rereading those first two books of Hilary Mantel’s trilogy, don’t hesitate any longer. You’ll really enjoy it! ...

... Having got so much out of revisiting *Wolf Hall* and *Bring Up the Bodies*, I’m at last launched into the final part of Hilary Mantel’s trilogy, *The Mirror and the Light. *Best, I think, to treat this massive volume as itself another three books (and anyway, I don’t want to finish it too quickly). So having read the first two parts of the new book, I’m pausing -- and really enjoying re-reading Kate Atkinson’s *Case Histories*. That’s the first of her Jackson Brodie novels, which are both wonderfully well written and also entertaining enough detective stories. What’s not to like? If you don’t know the series, warmly recommended for when you need distracting but not mindless reading!

---

On my desk, dipped into at random times, have been some of Alice Oswald's books of poetry. I do not find her at all easy or comfortable to read. But her work is deep and challenging and rewarding. My (shamingly belated) poetry discovery of the year.

But so many books to read. And re-read. Indeed, I mostly seem to have been re-reading since lockdown. But this [written in December] is the season when all those lists of Books of the Year are published, depressingly emphasizing how few recent books have come our way. I certainly won't be adding to those lists of obscure titles you mostly have never head of. Among the books which *were* published this year, I've in fact most enjoyed two that very many others have equally enjoyed: Maggie O’Farrell's *Hamnet* is very fine and I thought terrific. And then, again, Hilary Mantel's *The Mirror and the Light * is in a league of its own. Which hardly counts as insightful literary criticism -- but take those as hearfelt recommendations!
