---
title: "Peter Cropper, 1945--2015"
date: "2015-06-02"
page-layout: article
---

[](https://logicmatters.net/wp-content/uploads/2015/06/84f2f3d0-d060-4682-b176-c5f3e1e9a488-1020x612.jpeg)It is very sad to hear of the untimely death of Peter Cropper, for forty years the inspirational and charismatic leader of the Lindsay String Quartet.

When we lived in Sheffield, we often went to hear the Lindsays play at the Sheffield Crucible Theatre (not the big hall, but the very intimate studio theatre where the players sit in  a central space surrounded by tiered seats, a few hundred people just yards away). These could be extraordinary occasions, which always involved Peter Cropper talking to the audience about what the Quartet was about to play. His enthusiasm and passionate involvement made for memorable evenings.  The playing wasn't always immaculate -- but “Who wants perfection? Perfection is sterile. We’re human beings.” Peter Cropper was also instrumental in setting up quite exceptional series of concerts over the years in  Sheffield’s ‘Music in the Round’ (I guess using his personal warmth and contacts to entice world-renowned musicians to this small venue).

The Lindsays were at the height of their musical achievement in the period when we were able to hear them so often, and the CDs that came out at this time -- often, like the ‘Bohemians’ series, after series of performances in Sheffield and the Wigmore Hall -- are consistently wonderful and are among the very best quartet performances we have. Peter Cropper's playing on their Haydn disks shows a warmth and a delight in Haydn's endless invention that is absolutely captivating. The quartet's Beethoven is unsurpassed.

But I also have more personal memories. When at school, The Daughter was taught the violin by Nina Martin, Peter Cropper's wife. And Nina would a couple of times a year arrange concerts of her pupils (and pupils of local viola and cello teachers, so quartets and baroque concertos could be played). After the concerts, some pupils and parents would often go back to Peter and Nina's house, and crammed into the sitting room there would be more music. I can remember now a scratch, sight-read, performance of the first half of Mendelssohn's Octet with six assorted school kids, including The Daughter on fourth violin, plus Nina busking on second viola, and Peter attacking the first violin part with his usual passion, and inspiring  a moment of magic from his impromptu ensemble.
