---
title: "Encore #14: The Pavel Haas Quartet reviewed"
date: "2016-02-25"
page-layout: article
---

*We had tickets to hear the Pavel Haas Quartet three weeks ago, and again for today when they were due to play the Schubert Quintet. Very sadly, they have had to cancel their series of four London lunchtime concerts this month, because of serious family illness. Here is what I wrote about their recording of the Quintet.*

### **Review: the Pavel Haas Quartet, Schubert ‘Death and the Maiden’ and the String Quintet** (October 6, 2013)

[](http://www.supraphon.com/en/catalogue/news-by-date/?item=1288)Readers of this blog will know how greatly I have admired the Pavel Haas Quartet for a while. And it isn't just me who finds them absolutely compelling both in live performance and on disc. Their previous four CDs have rightly been hugely praised, with the most recent Dvorak disk even winning The Gramophone Recording of the Year for 2011. And live, they are the most exciting quartet to watch and hear.

Now, at last, we have a new recording, of the Schubert D minor quartet, "Death and the Maiden", and the String Quintet.  Michael Tanner writing in the *BBC Music Magazine*, another philosopher who weighs his words carefully,*  *called these "great performances ... essential listening for anyone who loves Schubert". The *Times* reviewer wrote "If CDs had grooves I would already have worn out these marvellous recordings  ... the perfect fusion of virtuosity and profundity."  Indeed. These performances are of a quite unworldly quality, deeply felt yet utterly thought-through, the most passionate you have heard but with moments of haunting delicacy,  with an overarching architectural vision always holding it all together.

The Pavel Haas launch into "Death and the Maiden" with fierce attack and astringent (almost vibrato-less) tone.  And they start as they mean to go on. The recent Takacs and the Belcea versions -- good though they are -- now seem slightly restrained in contrast (this is the still-young Schubert confronting *death *here, and the still-young Pavel Haas respond with apt intensity). The obvious comparison would be with the Lindsays' great recording from twenty five years ago, which I would previously have said was the finest post-war version. But the Pavel Haas's controlled passion, their even more moving account of the variations of the second movement, and their vehement drive to the end of the quartet, makes -- I think -- for an unparalleled performance.

As for the Quintet, this performance with Danjulo Ishizaka as the second cello is perhaps even finer. For any players, the problem -- isn't it? -- is to maintain a shape to the whole piece: a bit too ethereal with the second movement and a bit too cheery with the last movements, and the Quintet is in danger of seeming unsatisfyingly unbalanced. But here, the whole hangs together better than any other interpretation I know. Although the playing is more expansive, within a few bars of the opening, the Pavel Haas have again built an extraordinary sense of tension. This is not comfortable listening -- but then much of late Schubert isn't. And the underlying tension is then maintained in a driven, uncompromising, way to the very end, with the slow movement giving only some partial relief (and there, the central section is played with a yearning fierceness, and the playing when the original theme returns is heart-stopping).  This makes for an exploration of the music at a level of intensity that again more than bears comparison with the Lindsays' historic recording. Surely, a truly great interpretation of this great musical exploration of our humanity and mortality.

After a series of changes of second violin over the years, the Pavel Haas have never sounded better. Hopefully they will now stay happily together as they are.

*Added *The *Gramophone* reviewer writes of their "fearless risk-taking , their fervency" and "insanely memorable" phrasing; the Pavel Haas are "absolutely mesmerising" (in the close of the slow movement of the Quintet); "raw, visceral, and with an emotional immediacy that is almost unbearable" (at the ending of Death and the Maiden), and more. Yes!

*Added * In the months since this review was first written, I've found that these performances more than live up to repeated listening.

* Added*: Hopefully, their next CD will be of the Smetena Quartets: their live performances which I've heard have been nothing short of astonishing.

*And indeed, their next CD was their stunning, award-winning, disc of the two Smetena Quartets.*
