---
title: "Encore #7: Postcards from Siena"
date: "2016-02-14"
page-layout: article
---

[*](https://logicmatters.net/wp-content/uploads/2016/02/DSCF2066.jpg)

*Continuing the series of re-posts as we approach the tenth birthday of the blog. In the early years of the blog, The Daughter had a home near Siena, and we visited often, and we came to love the place. The photo above is her village a few miles east of Siena (and indeed the just-visible white blob in the middle distance in the centre of the picture, is the dome of the Duomo, which was covered for repair at the time). Here are some snippets from one visit in May and June 2008.*

We have decamped back to Siena for the better part of a month. Or rather to a small village about 15km to the east. Siena is already bustling with tourists, but here things are very quiet. From one window, a few domestic sounds of village life; from another I can see half-a-dozen men slowly working in a line between the vines below the village walls. I suspect that logic postings here might be infrequent for a while, though I've brought a laptop and some things to work on when the mood takes me.

---

In the little piazza beneath our window, children have been celebrating their first communion. Being Italy, the occasion is marked before and after by a lot of noise, clanging bells and a brass band, and the inevitable gathering for food and wine. There are proud parents and grandparents, and the youth of the village dressed more for a party than for a solemn occasion. No doubt, it all means different things to different people: but these occasions are just part of village life, and I suspect that many of the participants are just comfortable through long familiarity with participating in religious services (with more or less regularity, more or less enthusiasm), and don't worry too much about what it all means. It is what you do, and it ceremoniously links the occasions of life with the eternal verities.

---

We normally never watch breakfast TV, but here we have the excuse of trying to pick up more Italian: and actually it isn't at all bad. The weekend show we watch has a nice slot visiting different places around Italy and talking at length about their local produce, and demonstrating a characteristic recipe. That -- followed by walking through the woods onto the estate of Villa Arceno and alongside their vineyards -- worked up appetites for Sunday lunch at a favourite restaurant,[ La Bottega di Lornano](http://www.bottegadilornano.it). But by then the weather was getting too threatening again to eat outside (even under their big awning). Still, a terrific meal as always, in Tuscan quantities, and we drank a favourite wine, Dievole's [Broccato](http://www.dievole.it/en/catalogue/productsDetail.aspx?idmaster=41). Prices in Italy are going up, and the pound is going down against the euro, so this is not quite the stunning bargain it would have seemed three years ago. But we still ate much better for less than the cost of a second-rate chain restaurant meal in England. Which is why we very rarely bother to eat out at home.

---

We went yesterday to the Archivio di Stato in Siena (which does guided visits three times a morning). The interest there -- apart from the great ranks of volumes of documents -- is an exhibition of the Tavolette di Biccherna. These are painted wooden panels that were produced as covers for bundles of civic account books, starting in 1258 with the practice continuing to the eighteenth century. The earlier ones, in particular, are fascinating (particularly interesting to see secular art of the time). Very definitely worth a visit: we enjoyed it great deal. There were exactly two other people there when we went.

---

Here, everyone has to park outside the walls of the old part of the borgo*. But that's no hardship. There's stone and gravel put down between the olive trees just under the house, and you park the car among them, leaving it to quietly admire the views for miles over the hills. The trees have been brutalized since last year, obviously scaring the living daylight out of them, and as a result they are beginning to fruit like mad. I can report that the local olive oils vary, but from merely very good indeed to the amazing. (And judging from the ages on the gravestones in the village cemetery, they must have magically life-extending properties.)

---

It's sunnier and warmer (for a while). This year the excellent restaurant just a few steps across the piazza has put a few tables outside, and will bring you a coffee and *cornetto* from when they open up in the morning, or an *aperitivo* in the afternoon. A great idea, but so far the weather has been such that we've only made use of it a few times. But this morning, sitting in the sun at half-past nine, it was already pretty hot. At last.

---

The *meteo* predicts that really good weather will start on Thursday. Since we are leaving on Wednesday, this is just a bit galling. This morning it was so cold we put the heating on again. And jazz last night in the little village piazza under our window was good, but not the balmy June night under the stars we might have expected, and the well-wrapped-up audience was understandably a bit thin.

Siena itself is like Cambridge at least in this respect: the tourists tend to stick to a small part of the city. So it can be very busy round the Campo and the Duomo. But other sights, even those the guide books warmly praise, can be more or less deserted. We did make one nice discovery a couple of days ago when it *was* dry in the afternoon. We found ourselves at the botanical gardens which we'd never visited before -- the gardens, predictably, were more or less empty of people. They are very fine, cool under the trees, tumble down a steep slope, and the views out of the city are beautiful. Recommended.
