---
title: "Encore #19: Schubert's piano music"
date: "2016-03-06"
page-layout: article
---

*Is it something about the philosophical temperament? But I have known a number of philosophers for whom Schubert's later piano works are absolutely central among the music which means the most to them. Certainly they are for me. I have blogged over the years about a number of recordings -- more than I realised -- including these posts: *

*From 2009* Sometimes, in an idle moment, I jot down — be honest, don’t we all? — a list of the eight discs I would select as my [Desert Island Discs](http://en.wikipedia.org/wiki/Desert_Island_Discs). Impossibly difficult of course! But one constant choice is the last Schubert piano sonata, D960 (and if I had to save one of the eight discs from the waves, then this would probably be it). But which recording? Well, that’s almost impossible too. ... I still think that that has to be one of the Brendel recordings: after listening to others, I always listen to him again with a sense of coming home. Perhaps I love his 1988 recording the most.

[](https://logicmatters.net/wp-content/uploads/2010/06/Schubert3_cooper_AV21581.jpg)*From 2010* The third double-CD has recently been released of Imogen Cooper's stunning journey through late Schubert in her QE Hall recitals in 2008 and 2009. The first two pairs of disks got some extraordinarily warm reviews, and this too strikes me as just wonderful. Thoughtful, deep, utterly persuasive. And lyrically beautiful.

At the end of the second of the new disks she reaches the pinnacle, the end of her journey  -- an amazing performance of D. 960.  As I said in an earlier post, I've accumulated over too many years recordings of this sonata played by Schnabel, Richter twice, Brendel three times, Schiff, Kovacevich, Perahaia, Uchida, and Lewis as well as the earlier Imogen Cooper; and yet here are new insights, a wonderful overall architecture, and an utterly compelling performance. This could well become my new "Desert Island" choice of  all those performances.

*From 2011*  Here's some other recordings to recommend -- [the new two CD set of Schubert from Paul Lewis](http://www.amazon.co.uk/Schubert-Piano-Sonatas-D-840-Lewis/dp/B00585QLX2), the D. 850 Sonata, the great D. 894 G major, the unfinished 'Reliquie' D. 840, the D.899 Impromptus -- and last but very certainly not least the D. 946 Klavierstücke (try the second of those last pieces for something magical again).  By my lights, simply wonderful. I've a lot of recordings of this repertoire, but these performances are revelatory. Which is a rather feebly inarticulate response, I do realize -- sorry! But if you love Schubert's piano music then I promise that this is just unmissable.

*From 2011* Thanks to Askonas Holt, her agents, three videos of Imogen Cooper playing at a concert in 2009 have just been posted on YouTube (the video isn’t HD, but the sound is just fine). There is a nice performance of [Schubert’s Hungarian Melody D817](http://www.youtube.com/watch?v=b6B44AN5lq4), and a lovely short piece of Janacek, [‘Good Night’](http://www.youtube.com/watch?v=M48p-2Eukzs) from On an Overgrown Path, which I haven’t heard for ages. But then, on a quite different scale of length and emotional intensity, she is joined by Paul Lewis for a stunning performance of the [Schubert Fantasie D940](http://www.youtube.com/watch?v=XCcIAJlT96k). And this is surely as good as it gets: two of the greatest Schubert pianists seemingly as one in their shared vision of the piece. Just wonderful.

*From 2013* [](https://logicmatters.net/wp-content/uploads/2013/02/51UUv-ZgUL._SL500_AA300_.jpg) Suppose, just suppose, that one of the very greatest and most loved actors of his (or her) generation was tackling one of the high peaks of the repertoire, returning perhaps to a previous near-triumph with a quarter of a century's more experience. Every broadsheet would have extensive reviews, though telling most readers about a performance they will never see (even if in reach of London and in funds to make the journey), because the tickets have long since sold out. There will be interviews with the actor, even colour-supplement spreads. You know how it goes.

Now here is one of the very greatest  and most admired pianists of her generation, still at the very height of her powers, returning to Schubert's last piano sonata, a quarter of a century after a very fine earlier recording. You would have thought that the broadsheets with arts pages would at least notice this major event. After all, nearly all their readers can afford the CD, which is so accessible that it will arrive at the click of a button. So *here* surely is something worth reviewing. Here too perhaps is even an occasion for a retrospective pieces on a remarkable artist. But no. As far as I've seen, nothing. Which is not at all unusual these days. It is difficult  not to feel (as you do when look round your fellow concert-goers, noting all the grey heads) that slowly but inexorably a deep engagement with classical music is becoming less and less central to our cultural life.

Well here, let it be said, is the most extraordinary music-making, indeed inviting the most personal engagement. Maria João Pires offers us a performance of the A Minor Sonata D845  played with intense intimacy. There is nothing declamatory here: she is sitting across the room, playing for us listening, close around her. There's a care to every phrase which isn't mannered, wonderful lightness of touch when called for, and moments when time is slowed to a pause (her magical way with the Trio of the third movement). For this sonata alone you will want the disc.

But then there is D960. What is to be said? For many, this is very high on the list of  the music that matters the most, that has to be returned to time and again. We have a most wonderful inheritance of recordings from Schnabel onwards of this "music which ... is better than it can be performed". Brendel, Richter and Imogen Cooper, all more than once, Lupu, Kovecevich and Uchida -- all are stunning in their different ways, all their recordings are to be listened to repeatedly.  And Pires herself recorded the sonata 25 years ago.

It would be absurd (or at least absurd for me) to try to make comparisons. Let me just say that this new recording is surely a more than a worthy addition to that great inheritance. This is not one of those more brooding performances where we are made conscious from the beginning that this *is* the work of a dying man (performances which give the first movement such ominous weight as to unbalance the whole sonata). There is an intimate directness to her undeclamatory opening: again, we are sitting with Pires -- she is not addressing us across a concert hall. And it is only slowly that the intensity is ratcheted up in the first movement (especially about 11 minutes in), and then we are gripped by a new tension as the opening theme and development return once more. The following *Andante sostenuto* is unsentimental, played with a rhythmic delicacy that becomes magical. The *Scherzo* is played vivace con delicatezza as Schubert asks: but Pires deconstructs the Trio with bass emphases which I can't recall being made quite so aware of before,  harking back to previous movements. The final *Allegro* has moments of lightness again but also a certain weight and drive giving a more-than-satisfying balance to the whole sonata, the tumbling final chords finishing in a sudden silence.

This won't replace your other recordings of D960, how could it? But you will want to listen and listen again, and you will hear more from Pires each time. Wonderful.

*From 2015* I buy too many CDs and we go to a fair number of concerts, and so I usually blog only about some of the ‘five star’ discs or concerts which bowl me over. Which does mean that when I *do* offer reviews,  they tend to be consistently full of superlatives. It is certainly not that I'm an uncritical listener: very far from it. Still, I don't want to be carping or tediously negative here (I'll keep that for the philosophy!). I prefer to write about music, when I do, from heartfelt enthusiasm. And this time, the enthusiasm is for David Fray's latest CD.

[](https://logicmatters.net/wp-content/uploads/2015/03/71E82Cp9UWL._SL1500_.jpg)One of the very finest Schubert recordings of the last ten years, it is widely agreed, is Fray's CD of the Op 92 Impromptus and the Moments Musicaux. He plays those pieces with luminous artistry and acute sensitivity -- taking some notably slow tempi yet never seeming mannered or other than fully immersed in the complexities and ambiguities of Schubert's music. There is, I have remarked elsewhere, something Richter-like in Fray's intensity, and in his wonderful ability to impose his vision of the music.

Fray has now returned to Schubert, and indeed firstly to a piece indelibly associated with a quite extraordinary recording by Richter -- the G major sonata D894. And the comparison in some ways is still very apt. For Fray too takes the first movement unusually slowly. Where, for example,  Brendel in his later digital recording takes 17'.16" and Paul Lewis 17'.28" -- both very fine performances -- Fray takes 19'.06". This still falls far short of Richter's astonishing, bordering-on-the-perverse, 26'.51" in the (in)famous 1979 recording. Yet here is the magical thing: from Fray's way with his very slight holdings-back, the slightest hesitations, to his control of the architecture of the movement, everything gives his performance a seeming scale closer to Richter's. (He takes little more than half a minute more than Mitsuko Uchida's 18'.29" and yet Fray's first movement  at crucial moments seems markedly more spacious.)

Another magical thing is the wonderfully nuanced clarity of Fray's playing here --  effortlessly cantabile passage work, forte passages which never become brashly declamatory, unending attention to detail with nothing exaggerated or out of place.

Now, there can be a problem -- can't there? -- with performances of some of Schubert's major works: how to make a satisfying whole of a piece that starts with one or two immense movements -- immense both in scale and emotional weight. (One of the many things that I particularly admire about the Pavel Haas Quartet's Schubert CD [which I reviewed here](https://logicmatters.net/2013/10/06/review-the-pavel-haas-quartet-schubert-death-and-the-maiden-and-the-string-quintet/) is the extraordinarily balance they achieve across the four movements of Death and the Maiden and again of the String Quintet.) How does the rest of David Fray's performance of the ‘Fantasie’ sonata hold up against this test?

Extraordinarily well, I would say. Partly this is because, although the first movement is played very expansively, it is never becomes *heavy*. And partly because of the compelling readings he gives of the other movements. I was rather surprised, when I checked, that Fray's timings in the last three movements are all rather quicker than Brendel, Lewis and Uchida. Yet he plays with such grace and attention to texture and detail that Schubert's music is given all the space it needs, and there are again quite magical touches. The Trio in the third movement catches with your breath. The final Allegretto dances through its episodes with a wonderful lightness of touch in building to its conclusion.

In short, I would say that of the dozen or more great performances of the G major sonata that I have on disc, this is at least as fine as any: it is worth getting Fray's new CD for this alone.

But there is much more. Fray follows with a lovely performance of the haunting Hungarian Melody D817. And then for the last two major pieces on the CD he is joined by his one-time teacher Jacques Rouvier. First, they play the Fantasia in F minor D940. This, the incurable romantics among us will remember, was dedicated by Schubert to his young pupil the Countess Karoline Esterházy, often thought to have been the object of his hopeless love: and the piece certainly calls for yearning and passion. I have long loved the old recording from 1978 by Imogen Cooper and Anne Queffélec. But Fray and Rouvier are perhaps even better. Certainly, the yearning in the first dotted theme (with its Hungarian echoes) is as intense; the passion as the music then goes through its evolving moods -- stormy, a burst of sunshine, clouds regathering interspersed with more moments of fleeting happiness -- is as heartful; the moment when the first yearning theme returns is as affecting; the build-up through the *fugato* passage to the very final appearance of the initial theme as the music comes to its abrupt recognition that the yearning is indeed hopeless, all this is wonderfully well done.

The CD concludes with the ‘Lebensstürme’ Allegro D947. This is not, for whatever reason, my favourite Schubert piano music: but again surely it could not be played better than it is here. A wonderful disc then, most warmly recommended.  (And there is, by the way, a [video about this CD on David Fray's website](http://davidfraymusic.com/project/watch-davids-new-video-for-schubert-fantaisie/).)
