---
title: "Serendipity"
date: "2015-12-22"
page-layout: article
---

[](https://logicmatters.net/wp-content/uploads/2015/12/51QH-wFLTeL._SX323_BO1204203200_.jpg)We have far too many books for a house this small, despite our best efforts to make room on shelves by passing on the unloved or the never-to-be-reread to Oxfam. So these days, we try not to buy a newly published book if neither of us is going to read it more or less immediately (of course, a different rule applies to happy second-hand finds). That's why, when Kate Atkinson's companion piece to her truly brilliant *Life after Life* came out, despite our both very much looking forward to reading it, we didn't buy it immediately, both already having tall piles of books waiting for us. And then it got to the point when a paperback was announced for the end of this month, and we decided to hang on and buy it to read over the festive season.

But ah,  a couple of weeks ago, in  the National Trust second-hand bookshop at Wimpole, there it was -- an almost pristine copy of *A God in Ruins. *The beautifully produced hardback for less than half the cost of a paperback. And it's quite unreasonably cheering -- isn't it? -- this kind of serendipitous find. Well ok, *not*  that serendipitous, when you think about it: Kate Atkinson is a best-selling author, we often drop in to take a quick look at the book shelves of charity shops large and small, so I suppose it was pretty likely that we'd stumble on a copy over the months since it came out. But even that thought doesn't make the find less cheering. It isn't the matter of saving a few pounds (or of giving the money to a charity rather than a chain bookstore); that's nice, to be sure, but it doesn't account for the pleasure, the happy feeling engendered by the little smidgin of good fortune. And it's the sort of little thing that sticks in the mind,  "Do you remember finding that by chance when we were on holiday in ...?", it becomes part of your history of your encounter with the book in a way that just marching into Blackwells and picking the volume off a pile never does.

It is, or rather was, the same with CDs, the pleasure of the happy find in charity shops of something well-known that you've been wanting for a while, or of something quite obscure but intriguing. I had much more enjoyment over some years acquiring the complete Hyperion Schubert Edition -- all 37 volumes of Graham Johnson's astonishing exploration of all Schubert's songs with various singers -- mostly second-hand than I ever would have done just buying the lot new. I have had more fun again discovering baroque composers you've never heard of, or later obscure Bohemians, and the rest. (Of course there are plenty of misses as well as the hits, but the few pounds have gone to charity, so the misses don't matter at all.)  But now I mostly use Apple Music to stream music, for there is precious little space for more CDs too; and I miss that kind of serendipity. Yes, of course, there is an unending source of music to explore there for the small subscription. Yes, of course, you make happy finds. But, dinosaur that I am, it just doesn't *feel* the same.

No way, though, are we swapping real books for e-books. Putting a few on the iPads when travelling is fine: but a well-made real book remains a continuing delight that we are not giving up.  So we'll carry on the pleasurable truffling through the charity shops: it's the splendid Oxfam bookshop in Saffron Walden tomorrow, I think ...

And how was *A God in Ruins*? As good as they say. Just wonderful.
