---
title: "Tarski on truth -- a thumbnail sketch"
date: "2018-11-05"
page-layout: article
---

A couple of days ago, someone wanting brief headline-news-for-non-experts asked me about Tarski's views on truth -- in “The Concept of Truth in Formalized Languages” -- and about how these ideas related to what was going on in the Vienna Circle at the time when Tarski presented those views in 1935. By coincidence[](https://logicmatters.net/wp-content/uploads/2018/11/Fig-B-Alfred-Tarski.png), I was thinking a bit about some related Tarskian issues in redrafting sections of *IFL*; so I was happy to pause and to try to gather together some (very) brief thoughts. I’m certainly no expert myself; but for whatever it is worth, here is a version of what I said in reply, in case anyone else might find the rather arm-waving remarks interesting/helpful.

The *Tractatus* -- which of course much influenced central figures in the Circle --  offers what looks like a correspondence theory of truth, with true propositions picturing facts. However, the very notion of “facts” seems metaphysically loaded in a way that the positivists were deeply unhappy about; so Neurath, for example, argues that sentences can only be compared with other sentences, coming close (it might seem) to an outright coherence theory of truth. A very interesting and accessible thing to read here, revealing something of the state-of-play pre-Tarski in debates between Neurath, Carnap and Schlick, is Carl Hempel’s short paper “[On the Logical Positivist’s Theory of Truth](https://www.jstor.org/stable/3326781)” in *Analysis* 1935.  So yes, an obvious question is now: how does Tarski -- presenting his ideas in 1935 --  fit into the story?

In fact, Tarski is coming from outside these inner-Circle debates. His problematic and his approach arise from inside the Polish philosophy/logic tradition.  Three themes worth remarking on:

 	- From Leśniewski, Tarski acquires a scepticism about naive treatments of semantic ideas, and the idea that the notion of truth applied without restraint in natural language contexts will inevitably entangle us with the Liar paradox.

 	- From Kotarbiński, Tarski gets the two thoughts (a) that the classic idea that to be true is to correspond with reality can come to no more than this:  the Copernican theory is true — or  the assertion that the earth goes round the sun is true — just in case the earth goes round the sun (K’s example), and so on through other cases.  But also (b) this weak understanding of what correspondence amounts to doesn’t mean that the notion of truth is redundant.

 	- From Leśniewski (3) again, Tarski gets a conception of how we should go about pinning down a troublesome concept -- not by attempting to give a snappy “analysis”, but by setting out in a tidily organized deductive system or “theory" systematizing a whole body of intuitive truths in which that concept is deployed, in enough detail to thereby fix what that concept has to be, in order to play the displayed role in the theory. In this sense, the theory as a whole can be said to define the concept in question. (If it is to be elucidatory, we’ll need to be able to grasp this deductively organized theory, which means that, inter alia, it will need to be finite!)

So (1), (2) and (3) set the scene for Tarski’s pivotal paper.  Do note by the way, it is about truth for “formalized” -- not “formal” -- languages. That’s rather crucial. If by “formal” one means more or less de-interpreted, then Tarski explicitly rules out formal languages from  consideration in his 1935 paper. Now, many mathematical languages are at least partially de-interpreted: thus a group theorist might use “+” for a group operation, without giving any particular intended interpretation. But it is not until much later that Tarski explicitly deals with the model theory of such partially de-interpreted language. In 1935, then, Tarski is concerned with some fully interpreted languages. They are formalized in the sense of having a tidy syntax, lacking structural or lexical ambiguities etc. etc. so we can easily theorise about them. (But it is  a matter of taste and convenience whether these languages introduce symbolic shorthand too — the use of symbols isn’t really of the essence at all, although Tarski's examples are languages deploying symbolic shorthand.)

As I say, (1), (2) and (3) set the scene. What we find, then, is Tarski continuing to endorse (1), arguing at the beginning of his paper that accepting (2a) and applying it across the board to all ordinary language, where self-reference is possible, leads us inevitably to the liar paradox. If we accept all T-biconditionals, for the moment in the form *“p” is true if and only if p,* but allow suitably self-referential instances of *p*, then trouble ensues! So we have to rein in our ambition.

Tarski's aim then will be to show how a notion of truth can consistently be applied to limited fragments of language which lack troublesome self-reference and lack a truth-predicate. So now we will have to distinguish the limited fragment we are (at any point) theorising about from the ambient language in which we are doing the theorizing. Hence the introduction of the distinction between the language which is the current object of investigation and the metalanguage in which we are going to be doing the investigation.

So how is Tarski going to do the investigation? *Exactly in accord with (3)*. To pin down the notion of truth for sentences in the language L under investigation Tarski is not (he explicitly says he is not) going to try for an analysis or philosopher’s-style definition. He aims for a tidily organized deductive system or “theory" (in a suitable metalanguage) systematizing a whole body of intuitive truths in which the metalanguistic concept of true-sentence-of-L is deployed. Which intuitive truths? As in (2a) -- i.e. what we now call T-sentences of the shape “S is true if and only if p” where “S” denotes a sentence of L, and “p” stands in for a sentence of our metalanguage which gives the content of S (except that Tarski symbolizes the theory in the metalanguage too, but that's not of the essence either). Note, what makes giving a tidy deductive theory of this kind feasible is that L is itself sufficiently tidily organized — formalized, as we said. In this way, we get to define* true-in-L* — define, that is, in the rather distinctive sense of (3).

For any interesting L, there will be infinitely many T-sentences for our finite truth-theory/truth-definition to entail, so the theory will have to proceed by paying attention to the structure of L-sentences (it will proceed by recursion, as we say, on the structure). The novel work done by Tarski is to show us how to do the recursion in the case of languages L with quantificational structure — with the recursion done not in terms of the notion of truth, but in terms of a notion of true-of (or rather its converse, satisfaction). Note though that it isn’t that Tarski is helping himself to the notion of satisfaction and taking that as already understood: rather the whole theory is now to be taken as defining satisfaction-in-L (of which truth-in-L is a special case).

So how did all this go down with the Vienna Circle? Some, e.g. Neurath, thought it just didn’t help with what they were worried about — for in the end satisfaction is a word/world relation which must be just as suspect as the classical notion of truth we started off with. But others thought this was point-missing. Tarski showed how we can happily talk about truth in what we would now think of as a deflationist spirit (at least for tamely well-behaved languages L), telling us about truth without getting embroiled in facts, structural correspondence with the facts, etc., coherence, or ideas of that ilk. It’s not so much a rival theory of truth, but a pinning down of what the notion of truth does for us which shows -- as the redundancy theory in a cruder way aims to show -- that we don’t  need a theory of the traditional sort. That debate about the significance of theories like Tarski's continues …
