---
title: "University \"reforms\""
date: "2016-02-04"
page-layout: article
---

*I am now doubly removed from the impact of the various "reforms" to universities in the UK and beyond. For one thing, those of us in Cambridge are well protected in various ways from the worst effects. And for another, I am now officially retired from the fray. Which doesn't stop me getting distressed by reports of what is happening.*

*One of the most acute writers recently on what is befalling universities in the UK  is a Cambridge colleague, the intellectual historian and cultural critic Stefan Collini. But telling though his analyses are, I'm not sure that he has much more idea than I have about what is then to be done. As I ruefully reflected in this piece: *

### **Universities, galleries and Stefan Collini** (February 26, 2012)

I read Stefan Collini's [*What are Universities For?*](http://www.amazon.co.uk/dp/1846144825) last week with very mixed feelings. In the past, I've much admired his polemical essays on the REF, "impact", the Browne Report, etc. in the *London Review of Books* and elsewhere: they speak to my heart.

But to be honest, I found the book a disappointment. Perhaps the trouble is that Collini is too decent, too high-minded, has too unrealistically exalted a view about what actually happens in universities which is too coloured by attitudes appropriate to the traditional humanities. And he is optimistic to the point of fantasy if he thinks that people are so susceptible to "the romance of ideas and the power of beauty" that they will want, or can be brought to want, lots and *lots* of universities in order to promote these ideas (as if they would suppose that the task of "conserving, understanding, extending and handing on to subsequent generations the intellectual, scientific, and artistic heritage of mankind" was clearly ill-served when there were only forty universities in England, as opposed to a hundred and whatever).

The cultural goods that Collini extols, perhaps enough will agree, are not to be measured in crassly economic terms and should be publicly sustained. But *that* thought falls so very short of helping us to think about what should be happening with the mass university education of almost half the age cohort, about what should be taught and how it should be funded. Collini's considerations -- if they push anywhere -- might indeed suggest the ring-fencing of a relatively few elite institutions, to be protected (as in the old days of the UGC) from quotidian government interference and direction. He himself mentions the Californian model (layers of different kinds of tertiary institutions, with a lot of movement between, but with a sharp intellectual hierarchy, with research concentrated at the top). But Collini doesn't say if that is where he wants us to go. The myths of basic-equality-of-institutions that continue to be endorsed so often in public discourse about the universities in the UK are quite inimical to official moves in that direction.

I am still musing about Collini's book which I'd finished on the train down, while in the Central Hall of the National Gallery. I am looking at one of their greatest paintings, Giovanni Moroni's [*The Tailor*](http://www.guardian.co.uk/artanddesign/2007/may/01/art). The tailor's gaze is challenging, appraising: I sit for a while to gaze back. It was a busy weekday afternoon. But in ten minutes or more not one other visitor walking through the Hall pauses to give him a glance.

A bit later, I go to see once more the painting I'd perhaps most like to smuggle home and put over the mantelpiece, Fra Lippo Lippi's wonderful [*Annunciation*](http://www.artunframed.com/images/artmis48/lippi6.jpg). I spend another ten minutes in the room where it hangs. One other person wanders in, and rather rapidly leaves again. Even Vermeer's *Young Woman Standing at a Virginal* -- and isn't she on the 'must see' list in every pocket guide? -- is surprisingly lonely, and almost no one stops to keep her company.

Take away all the school parties, take away all the overseas visitors, and who is left? You might reasonably imagine that the English don't really care, or at any rate don't care very much, about the art which is on show here. Oh, to be sure, we chattering classes know which blockbuster exhibitions are the done things to see: Leondardo in London or Vermeer in Cambridge will, for a while, be chock full of people. But from day to ordinary day? Some are vaguely glad to know that the National Gallery and the Fitzwilliam Museum are *there*. But, to be honest, a nice National Trust garden is really more our cup of tea (with scones and jam to follow, thank you).

I'm sure it's not that we are more philistine as a nation than others (the Uffizi in December isn't suddenly full of Italians glad to take advantage of the absence of tourists). But equally, I wouldn't overrate the interest of even the more educated English in Culture with a capital 'C'. When I was a Director of Studies, I used to ask my students towards the end of their time in Cambridge if they'd ever visited the Fitzwilliam: almost no-one ever had.

Collini, to return to him, reflects that "Some, at least, of what lies at the heart of a university is closer to the nature of a museum or gallery than is usually allowed or than most of today's spokespersons for universities would be comfortable with." And I rather agree. But where does the thought take us? I doubt that even Collini really thinks that the tepid interest of the English -- just some of the English -- in museums and galleries can be parlayed into a wide public enthusiasm for spending a lot more on universities in these difficult times. So what's to be done?

*Stefan Collini has written more since on what is happening to universities since his book. In a later post, I noted another piece of his from the London Review of Books, [about the privatisation disasters befalling British universities](http://www.lrb.co.uk/v35/n20/stefan-collini/sold-out). Let me quote again his acerbic  peroration:*

> Future historians, pondering changes in British society from the 1980s onwards, will struggle to account for the following curious fact. Although British business enterprises have an extremely mixed record (frequently posting gigantic losses, mostly failing to match overseas competitors, scarcely benefiting the weaker groups in society), and although such arm’s length public institutions as museums and galleries, the BBC and the universities have by and large a very good record (universally acknowledged creativity, streets ahead of most of their international peers, positive forces for human development and social cohesion), nonetheless over the past three decades politicians have repeatedly attempted to force the second set of institutions to change so that they more closely resemble the first. Some of those historians may even wonder why at the time there was so little concerted protest at this deeply implausible programme. But they will at least record that, alongside its many other achievements, the coalition government took the decisive steps in helping to turn some first-rate universities into third-rate companies. If you still think the time for criticism is over, perhaps you’d better think again.

*And Collini's latest entirely admirable piece in the LRB turns [to analyse, deconstruct, and shred the latest government proposals on teaching assessment.](http://www.lrb.co.uk/v38/n02/stefan-collini/who-are-the-spongers-now) Not very cheering reading, I am afraid.*
