---
title: "So what's it all about then?"
date: "2007-02-11"
page-layout: article
---

The photographer Steven Pyke has produced another [set of photos](http://www.pyke-eye.com/philosophers_II.html) of great and not-so-great living philosophers. The style is, as with his earlier set published as a book, dramatically black-and-white, distinctly pretentious -- and so, of course, in some cases the portraits are hardly recognizable.

Pyke asks his sitters to describe 'in fifty words of so their own idea of what philosophy means'. So what's it all about then? Ruth Millikan gives a favourite quotation of mine from Sellars: ''The aim of philosophy, abstractly formulated, is to understand how things in the broadest possible sense of the term hang together in the broadest possible sense of the term." (I wonder how many students, at least this side of the Atlantic, read Sellars any more?)

Here are two other answers that chimed with me. David Papineau: "Some hold that the aim of philosophy is to construct theories that confirm everyday intuitions. What a dispiriting ambition. In my book, the best philosophy overturns common sense. Often, the impetus for change comes from outside philosophy, in the form of scientific or cultural innovation. The task of the philosopher is then to show how the new ideas reshape everyday thinking. Does this reduce philosophy to the status of a hand-maiden? Well, far better a hand-maiden of change than a lackey of the intellectual status quo."

And Steve Stich: "The idea that philosophy could be kept apart from the sciences would have been dismissed out of hand by most of the great philosophers of the 17th and 18th centuries. But many contemporary philosophers believe they can practice their craft without knowing what is going on in the natural and social sciences. If facts are needed, they rely on their "intuition", or they simply invent them. The results of philosophy done in this way are typically sterile and often silly. There are no proprietary philosophical questions that are worth answering, nor is there any productive philosophical method that does not engage the sciences. But there are lots of deeply important (and fascinating and frustrating) questions about minds, morals, language, culture and more. To make progress on them we need to use anything that science can tell us, and any method that works."
