---
title: "Logical snippets"
description: "Short answers on logic, answering questions on the math.stackexchange site."
---

For a number of years now, though not so much recently I’ve been a sporadic visitor to the very useful question-and-answer site, [math.stackexchange.com](https://math.stackexchange.com) — this is a student-orientated forum, not to be confused with the truly wonderful [mathoverflow.net](https://mathoverflow.net) which is its research-level counterpart. OK, you can think of these visits as (hopefully) constructive procrastination on my part …

Of course, many of the questions on the site, including many I’ve found myself answering, are very ephemeral or very localized or based on very specific confusions. But a proportion of the exchanges to which I’ve contributed might, for one reason or another, be of some interest/use to other students — or at least, to beginners and near beginners in logic.

Do read other people’s answers of course, which are sometimes more interesting than mine! I’ve included a few exchanges where all I contribute is a reference to something interesting in the literature. Do explore other logic and related questions on the math.stackexchange site too. And why not register so you can occasionally “vote up” answers you get something out of, as the feedback encourages good authors — and there are a significant number there — to keep posting to the general benefit.

## Beginning logic

- [What is meant by “sentence”?](https://math.stackexchange.com/questions/4745388/what-exactly-is-meant-by-sentence-and-expression/4745396#4745396)
- [Why bother to study deductive systems for propositional logic?](http://math.stackexchange.com/questions/275683/why-is-axiomatic-system-needed-in-propositional-logic)
- [Introductions to logic talk about sets of atomic formulae, etc. But doesn’t set theory in turn depend on logic? Isn’t this circular?](http://math.stackexchange.com/questions/370342/language-set-and-sentential-calculus)
- [Elementary logic, formal logic, metalogic — what are they?](http://math.stackexchange.com/questions/202066/difference-between-elementary-logic-and-formal-logic/202085#202085)
- [How are different approaches to logic related?](http://math.stackexchange.com/questions/927881/what-are-the-different-approachs-to-logic)
- [Sermon: Questions of the form ‘How do I prove X by natural deduction?’ are ill-posed](https://math.stackexchange.com/questions/2192585/proving-that-neg-forall-x-neg-ga-x-vdash-exists-xga-x/2192681#2192681)
- [Disjunction: why did the inclusive “or” become the convention?](http://math.stackexchange.com/questions/366122/disjunction-why-did-the-inclusive-or-become-the-convention)
- [Is natural language “or” ambiguous?](https://math.stackexchange.com/questions/2652868/intuition-behind-exclusive-or)
- [More on inclusive/exclusive “or”](https://math.stackexchange.com/a/3598800/35151)
- [What does “contradiction” mean in logic?](https://math.stackexchange.com/a/3600800/35151)
- [What is the “correct” reading of ⊥?](http://math.stackexchange.com/questions/658262/what-is-the-correct-reading-of-bot)
- [Does false entail everything?](https://math.stackexchange.com/questions/4745885/does-false-logically-entails-everything/4745972#4745972)
- [What does “classical logic” mean?](http://math.stackexchange.com/questions/206786/what-does-classical-logic-mean/206812#206812)
- [Why do we prefer classical logic over e.g. relevant logic?](http://math.stackexchange.com/questions/348685/why-do-we-prefer-classical-logic-over-non-classical-logic)
- [Why is “traditional logic” inadequate?](http://math.stackexchange.com/questions/209156/motivation-behind-theory-of-relations/209213#209213)
- [Is there a formalization of syllogistic logic?](https://math.stackexchange.com/questions/3670578/is-there-a-formalization-of-syllogistic-logic/3676661#3676661)
- [Does *All A are B* imply *Some A are B*?](https://math.stackexchange.com/questions/236583/deducing-some-are-from-all-are/239112#239112)
- [Why not allow empty domains?](https://math.stackexchange.com/a/3002997/35151)
- [What is the role of free variables in first-order logic?](http://math.stackexchange.com/questions/769205/what-is-the-purpose-of-free-variables-in-first-order-logic/769338#769338)
- [Why do the clauses in a semantics for quantifiers mention free variables?](http://math.stackexchange.com/questions/323571/why-do-the-clauses-in-a-semantics-for-quantifiers-mention-free-variables)
- [Should we prefer to use first-order theories with multiple sorts?](http://math.stackexchange.com/questions/471865/in-a-first-order-theory-with-multiple-sorts-is-there-any-reason-not-to-throw-aw)
- [Can we replace the identity sign in first-order logic by the convention that different variables get assigned different values?](http://math.stackexchange.com/questions/363168/first-order-logic-without-equality)
- [What’s the best method to determine whether a first order formula is logically valid or not?](http://math.stackexchange.com/questions/432482/best-method-to-determine-if-a-first-order-formula-is-logically-valid)
- [What is a zero-place predicate? a 0-adic function, etc.?](http://math.stackexchange.com/questions/873237/relations-and-functions-with-valence-0/873385#873385)
- [Do tableaux proofs show syntactic or semantic entailment?](http://math.stackexchange.com/questions/505239/do-semantic-tableaux-show-syntactic-or-semantic-entailment)
- [How do we prove for a tableaux system that if $S \vdash X$ and $S \vdash X \to Y$ that $S \vdash Y$?](https://math.stackexchange.com/questions/2694701/is-there-a-purely-syntactic-proof-of-modus-ponens-with-tableau)
- [How about marrying the axiomatic approach and natural deduction as Kleene does](http://math.stackexchange.com/questions/577072/virtues-of-presentation-of-fo-logic-in-kleenes-mathematical-logic/577175#577175)
- [How does the meta-language relate to the object-language?](http://math.stackexchange.com/questions/432522/object-language-and-meta-language)
- [What are the rules for the use of dots rather than parentheses in logical formulae?](http://math.stackexchange.com/questions/311871/what-are-the-rules-for-the-use-of-dots-rather-than-parentheses-in-logical-formul)
- [Some definitions of the idea of a wff make unique readability trivial: why not use such a definition?](http://math.stackexchange.com/questions/780114/unique-readability/780545#780545)

## Explaining the material conditional, etc.

- [Why do we use the material conditional in logic?](http://math.stackexchange.com/questions/232309/how-to-interpret-material-conditional-and-explain-it-to-freshmen/232490#232490)
- [When does material implication supposedly not “work?”](https://math.stackexchange.com/questions/2611358/when-does-material-implication-supposedly-not-work)
- [Do the usual natural deduction rules for the conditional determine its truth-table?](http://math.stackexchange.com/questions/1243056/reconstructing-the-conditionals-truth-table-from-natural-deduction)
- [Why is *if P then Q* equivalent to $\neg P \lor Q$?](https://math.stackexchange.com/questions/2596766/arguments-pro-material-implication/2596921#2596921)
- [Why is *if P then Q* not equivalent to $\neg P \lor Q$?](https://math.stackexchange.com/questions/2611358/when-does-material-implication-supposedly-not-work/2611456#2611456)
- [Can we replace the modus ponens rule with a conditional proposition?](http://math.stackexchange.com/questions/287142/modus-ponens-implication-versus-entailment/287179#287179)
- [What’s the sense of ‘implies’ in logic?](http://math.stackexchange.com/questions/244001/whats-the-sense-in-implies-logic/244027#244027)
- [What is the difference between “if $\vdash P$, then $\vdash Q$” and “$\vdash (P \Rightarrow Q)$”?](http://math.stackexchange.com/questions/539096/difference-between-if-vdash-p-then-vdash-q-and-vdashp-rightarrow-q)
- [What is the difference between $\to,\ \vdash,\ \vDash$ etc. (i)?](http://math.stackexchange.com/questions/238872/difference-between-implies-and-therefore/238952#238952)
- [What is the difference between $\to,\ \vdash,\ \vDash$ etc. (ii)?](http://math.stackexchange.com/questions/286077/implies-vs-entails-vs-provable/286106#286106)

## Help for beginners with translation into first-order logic

- [How to translate “Any A who is B is C”](http://math.stackexchange.com/questions/583214/predicate-logic-difference-between-who-and-if-in-symbolization)
- [Translate “Every person who dislikes all vegetarians is smart”](http://math.stackexchange.com/questions/243699/misinterpreting-logic-expression/243729#243729)
- [Translate “There is exactly one person whom everybody can fool”](http://math.stackexchange.com/questions/499021/nested-quantifiers-in-english-translation/499097#499097)
- [Translate “Anyone who knows everyone Alma knows knows Alma”](http://math.stackexchange.com/questions/695742/some-ql-translations/695946#695946)
- [Can we translate ‘Everyone loves themself’ as $\forall x\forall y(x = y \to Lxy)$?](http://math.stackexchange.com/questions/312238/trivial-question-about-nested-quantifiers/312727#312727)
- [When regimenting an argument with a definite description in first-order logic, when must we use Russell’s theory of descriptions?](http://math.stackexchange.com/questions/635299/formalising-definite-description-russell/635545#635545)

## Help for beginners with natural deduction proofs etc.: how to think strategically!

- [How to show $P \vdash Q \to P$](http://math.stackexchange.com/questions/203995/proof-p-vdash-q-rightarrow-p/204010#204010)
- [How to show $\lnot (P \supset Q) \supset (P \land \lnot Q)$](http://math.stackexchange.com/questions/82188/propositional-logic-proof-of-vdash-lnot-p-supset-q-supset-p-land-lnot/305560#305560)
- [How to show $(P \land Q) \to R$ and $P \to (Q \to R)$ are equivalent](http://math.stackexchange.com/questions/477313/natural-deduction-proof/477432#477432)
- [How to show $(P \to (Q \to R)) \to (Q \to (\lnot R \to \lnot P))$](http://math.stackexchange.com/questions/516291/prove-using-inference-rules/516329#516329)
- [How to show $((P \lor Q) \to R) \to (\lnot R \to (\lnot P \land \lnot Q))$](http://math.stackexchange.com/questions/207185/tautology-proof-without-truth-table/207207#207207)
- [How to show $\vdash (P \lor \neg P)$, and another problem](http://math.stackexchange.com/questions/693711/a-couple-natural-deduction-proofs/693739#693739)
- [How to show $(\neg P \lor Q) \vdash (P \to Q)$](https://math.stackexchange.com/questions/2588556/how-to-proof-¬p∨q-entails-p→q-by-natural-deduction/2588568#2588568)
- [How to show $\vdash (P \land Q) \to (P \to Q)$](http://math.stackexchange.com/questions/1139873/⊢p-land-q-to-p-to-q-natural-deduction-proof-confusion)
- [How to show $P\to (\neg Q\leftrightarrow(R\lor S)),\neg S\vdash (P\land \neg Q)\to R$](http://math.stackexchange.com/questions/519711/natural-deduction-p-lor-q-to-r-vdash-p-to-r-and-p-to-neg-q-leftrightarro)
- [How to show $(P \land (Q \lor R)) \leftrightarrow ((P \land Q) \lor (P \land R))$](http://math.stackexchange.com/questions/222160/how-to-prove-the-distributive-property-without-using-truth-tables/222186#222186)
- [How to show $(A \lor B) \land \neg C, \neg C \to (D \lor \neg A), B \to (A \lor E) \vdash E \lor F$](http://math.stackexchange.com/questions/670607/logic-formal-proofs/670731#670731)
- [How to show $p \to (q \land r) \vdash (q \to r) \lor \neg(p \lor r)$](https://math.stackexchange.com/questions/2529653/using-natural-deduction-to-prove-p-rightarrow-q-wedge-r-vdash-q-rightarrow/2530062#2530062)
- [How to show $\forall x(\varphi(x) \to P) \to (\exists x\varphi(x) \to P)$](http://math.stackexchange.com/questions/432388/t-f-vdash-ndfol-forall-xb-to-a-to-exists-x-b-to-a/432400#432400)
- [How to show $\exists x(\varphi(x) \to P)$ entails $(\forall x\varphi(x) \to P)$](https://math.stackexchange.com/a/3016485/35151)
- [How to show $\exists x (\exists yA(y) \to A(x))$ is a theorem.](https://math.stackexchange.com/questions/3593034/prove-exists-x-exists-yay-to-ax-is-a-theorem/3593579#3593579)
- [How to show $\exists x \exists y (\varphi(x) \to \psi(y)) \rightarrow \exists x (\varphi(x) \to \psi(x))$](http://math.stackexchange.com/questions/573458/proof-of-exists-x-exists-y-varphix-rightarrow-psiy-rightarrow-exist/573921#573921)
- [How to show $\exists x \forall y\,x = y \to \forall x \forall y\,x = y$](http://math.stackexchange.com/questions/520775/natural-deduction-and-identity/521369#521369)
- [How to prove $\forall x\exists y f(x) = y$ in FOL](http://math.stackexchange.com/questions/761818/how-to-prove-vdash-forall-v-1-exists-v-2-fv-1-v-2/761846#761846)
- [How to show $\forall x(\exists y Rxy \to \forall yRyx), Rab \vdash \forall x\forall y Rxy$](http://math.stackexchange.com/questions/767862/proofs-for-relational-predicate-logic-difficult-question/767970#767970)
- [Strategy for another tricky proof with multiple quantifiers!](https://math.stackexchange.com/a/3032651/35151)
- [How to derive $A \to (B \to C) \to ((A \to B) \to (A \to C))$ in the sequent calculus](http://math.stackexchange.com/questions/882850/deriving-a-rightarrow-b-rightarrow-c-rightarrow-a-rightarrow-b-r/883080#883080)

## Paradoxes

- [What makes something a paradox?](http://math.stackexchange.com/questions/636467/paradoxes-in-logic/636942#636942)
- [A: B is true. B: A is false. Nonsense? Paradox?](http://math.stackexchange.com/questions/209805/logic-nonsense-paradox/209844#209844)
- [Is the Barber’s paradox a paradox?](https://math.stackexchange.com/questions/2189436/why-is-the-barbers-paradox-a-paradox)
- [Why is Russell’s Paradox a paradox? (i)](https://math.stackexchange.com/questions/4381029/formalizing-russels-paradox-in-fol/4381047#4381047)
- [Why is Russell’s Paradox a paradox? (ii)](http://math.stackexchange.com/questions/496029/russells-paradox)

## Theories

- [Why are we interested in models as well as formal axioms for theories?](https://math.stackexchange.com/questions/2184030/how-are-primitive-mathematical-objects-chosen/2188475#2188475)
- [What’s the difference between an interpretation and a model of a theory?](https://math.stackexchange.com/questions/2191479/interpretation-vs-model/2191959#2191959)
- [What is the relationship between the consistency, axiomatizability, and decidability of a theory?](https://math.stackexchange.com/questions/2254328/relationship-of-consistency-axiomatizability-and-decidability)
- [What is the use of identifying objects in different mathematical theories?](http://math.stackexchange.com/questions/1187438/what-are-the-uses-of-cross-theoretic-identifications-within-mathematics)
- [How is it legitimate to add non-standard elements to a model of arithmetic?](https://math.stackexchange.com/questions/2624907/non-standard-model-of-arithmetic-why-is-adding-new-constants-to-the-model-acce)

## Arithmetic and computability

- [Natural numbers, real numbers, complex numbers, p-adic numbers …. what makes them all numbers?](http://math.stackexchange.com/questions/1259198/what-are-numbers)
- [We allow “imaginary” numbers such as $x^2 = -1$; why not other imaginary numbers such that $x + 1 = 1$?](http://math.stackexchange.com/questions/259584/why-dont-we-define-imaginary-numbers-for-every-impossibility)
- [Can we define the usual arithmetic operations in terms of a single operator?](http://math.stackexchange.com/questions/338370/is-there-an-numeric-arithmetic-with-a-single-operator)
- [Are partial functions interesting (outside recursion theory)?](http://math.stackexchange.com/questions/195556/examples-of-partial-functions-outside-recursive-function-theory/195573#195573)
- [How is the standard model of number theory specified and why can’t we use that?](http://math.stackexchange.com/questions/415725/how-is-the-standard-model-of-number-theory-specified-and-why-cant-we-use-that)
- [How do you prove that proof by induction is a proof?](http://math.stackexchange.com/questions/215846/how-do-you-prove-that-proof-by-induction-is-a-proof)
- [Do we just have to take proofs by induction on faith?](https://math.stackexchange.com/a/2984946/35151)
- [If you prove Goldbach’s conjecture is independent of ZFC, that proves Goldbach’s conjecture is true: why?](http://math.stackexchange.com/questions/275405/clarification-of-a-remark-of-j-steel-on-the-independence-of-goldbach-from-zfc/275495#275495)
- [What is the relationship between the idea of a “recursive” set and the concept of recursion in the sense of a function calling itself?](http://math.stackexchange.com/questions/398535/what-is-the-relationship-between-recursive-or-recursively-enumerable-sets-an)
- [‘I would like a proof that first order logic is undecidable, but without using arithmetic’](http://math.stackexchange.com/questions/694845/proving-undecidability-of-first-order-logic-without-first-proving-it-for-arithme/694887#694887)
- [Why is the set of truths of arithmetic not effectively enumerable?](http://math.stackexchange.com/questions/246429/question-about-computability-of-true-provable-formulas/246461#246461)
- [Why do we believe the Church-Turing Thesis?](http://math.stackexchange.com/questions/402934/why-do-we-believe-the-church-turing-thesis)
- [Can every partially computable function be extended to a total computable function?](https://math.stackexchange.com/questions/2185847/can-every-partially-computable-function-be-extended-to-a-total-computable-functi)
- [Is the inverse of a primitive recursive bijection on the natural numbers primitive recursive?](https://math.stackexchange.com/questions/2975305/inverse-of-a-primitive-recursive-bijection/2979596)
- [Do recursive definitions and impredicative definitions both involve self-reference?](https://math.stackexchange.com/questions/2704636/what-is-the-difference-between-impredicativity-and-recursion/)
- [What is the link between Church’s theorem and the undecidability of predicate logic?](https://math.stackexchange.com/questions/2190125/what-is-the-link-between-churchs-theorem-and-the-undecidability-of-predicate-lo)

## Gödel’s incompleteness theorem(s)

- [What background knowledge do you need for understanding Gödel’s Theorem?](http://math.stackexchange.com/questions/205518/what-is-the-prerequisite-knowledge-for-learning-godels-incompleteness-theorem)
- [Can someone explain Gödel’s incompleteness theorems in layman terms?](http://math.stackexchange.com/questions/453503/can-someone-explain-godels-incompleteness-theorems-in-layman-terms) [Notable for other people’s answers!]
- [Don’t Gödel’s completeness and incompleteness theorems contradict each other? (i)](http://math.stackexchange.com/questions/280642/sequent-calculus-and-first-incompletness-theorem/280701#280701)
- [Don’t Gödel’s completeness and incompleteness theorems contradict each other? (ii)](http://math.stackexchange.com/questions/435963/dont-godels-completeness-and-incompleteness-theorems-contradict-each-other)
- [Does Gödel’s theorem show that some things are never provable?](https://math.stackexchange.com/questions/4481855/regarding-godels-arithmetic-technique-in-incompleteness-theorem/4481974#4481974)
- [What axioms is Gödel using to prove his theorem?](https://math.stackexchange.com/questions/2617872/what-axioms-g%c3%b6del-is-using-if-any)
- [What’s so great about showing that Peano Arithmetic is incomplete?](http://math.stackexchange.com/questions/730017/how-to-explain-the-power-of-pa-to-non-logicians/730055#730055)
- [What’s so great about Gödel’s Theorem, since incompleteness is pervasive?](http://math.stackexchange.com/questions/169319/what-does-the-completeness-of-a-system-mean-for-the-provability-of-certain-statm/169373#169373)
- [What is meant by saying that a Gödel sentence is “true in arithmetic”?](https://math.stackexchange.com/users/35151/peter-smith?tab=answers&sort=newest)
- [Are Gödel sentences always true?](http://math.stackexchange.com/questions/845569/criticism-on-truth-of-gödel-sentence-in-standard-interpretation/845583#845583)
- [Is there an algorithm for producing undecidable sentences for any given theory?](http://math.stackexchange.com/questions/884959/godel-incompleteness-theorem/884969#884969)
- [Is there a proof of Gödel’s Theorem without self-referential statements?](http://math.stackexchange.com/questions/171863/is-there-a-proof-of-godels-incompleteness-theorem-without-self-referential-stat)
- [Is the negation of the Gödel sentence always unprovable too?](http://math.stackexchange.com/questions/182961/is-the-negation-of-the-godel-sentence-always-unprovable-too)
- [Are the proofs of incompleteness theorems valid for an intuitionist?](http://math.stackexchange.com/questions/448527/are-the-proofs-of-incompleteness-theorems-valid-for-both-classical-and-intuitionis)
- [Does Gödel’s Theorem also show that are non-standard models of second-order arithmetic?](http://math.stackexchange.com/questions/203299/are-there-non-standard-models-of-arithmetic-in-second-order-arithmetic/203372#203372)
- [Does Gödel’s Theorem say anything about the limitations of theoretical physics?](http://math.stackexchange.com/questions/228806/does-godels-incompleteness-theorem-really-say-anything-about-the-limitations-of)
- [What is the relation between the original proofs of Gödel’s two incompleteness theorems?](http://math.stackexchange.com/questions/756287/gödels-incompleteness-theorems-where-to-learn-is-there-a-straightforward-rela/756441#756441)
- [What is the relation between Turing’s theorem about the halting problem and Gödelian incompleteness?](http://math.stackexchange.com/questions/1181151/is-there-a-relationship-between-turings-halting-theorem-and-gödel-incompletenes)
- [Are the axioms of arithmetic consistent?](http://math.stackexchange.com/questions/191099/axiomatic-system-and-hilberts-2nd-problem/191122#191122) [Gödel’s second theorem]
- [Is there more than one Rosser sentence?](http://math.stackexchange.com/questions/372037/is-there-more-than-one-rosser-sentence)

## Sets and functions

- [What’s so special about set theory?](http://math.stackexchange.com/questions/366463/any-branch-of-math-can-be-expressed-within-set-theory-is-the-reverse-true)
- [Do we need to use set-theoretic concepts in theorizing about first order logic? 1](https://math.stackexchange.com/questions/2721461/set-theoretic-concepts-in-first-order-logic/2721975)
- [Do we need to use set-theoretic concepts in theorising about first order logic? 2](https://math.stackexchange.com/a/3024322/35151)
- [How much set theory is needed for serious logic?](http://math.stackexchange.com/questions/910305/how-much-set-theory-is-necessary-for-serious-logic)
- [Why suppose there is such a set as the empty set?](http://math.stackexchange.com/questions/245828/validity-of-empty-sets/245882#245882)
- [Why is the empty set a subset of any set?](https://math.stackexchange.com/questions/823643/subsets-and-sets/823651#823651)
- [What is an ordered pair really?](https://math.stackexchange.com/questions/4484662/definition-of-ordered-pair-and-intuition/4484694#4484694)
- [Can we identity a relation with its extension?](https://math.stackexchange.com/questions/4991918/what-exactly-is-the-extension-of-a-binary-relation/4992900#4992900)
- [Is a function a relation?](https://math.stackexchange.com/questions/2189860/do-functions-have-truth-values/2189909#2189909)
- [Can we identify a function with its graph?](https://math.stackexchange.com/questions/4492753/function-and-graph/4495420#4495420)
- [Is a function a set? (i)](http://math.stackexchange.com/questions/442522/difference-between-a-function-and-a-graph-of-a-function)
- [Is a function a set? (ii)](http://math.stackexchange.com/questions/479936/in-what-manner-are-functions-sets)
- [Why is a function defined as having only one y value output?](http://math.stackexchange.com/questions/271613/why-is-a-function-defined-as-having-only-one-y-value-output/271619#271619)
- [Should we allow individuals (urelemente) in set theory? (i)](http://math.stackexchange.com/questions/499299/the-use-of-individuals-in-set-theory)
- [Should we allow individuals (urelemente) in set theory? (ii)](https://math.stackexchange.com/questions/4384354/how-do-we-formally-describe-mathematical-modelling-using-set-theory/4384386#4384386)
- [How is Cantor’s diagonal argument related to Russell’s paradox in naive set theory?](http://math.stackexchange.com/questions/222970/how-is-cantors-diagonal-argument-related-to-russells-paradox-in-naive-set-theo)
- [If it takes infinite steps to prove a statement is that a valid proof?](http://math.stackexchange.com/questions/193619/if-it-takes-infinite-steps-to-prove-a-statement-is-that-a-valid-proof/193635#193635)
- [Is the domain of discourse in axiomatic set theory also a set?](http://math.stackexchange.com/questions/1087022/is-the-domain-of-discourse-in-axiomatic-set-theory-also-a-set)
- [What does it mean to say that a set is equipped with a function?](http://math.stackexchange.com/questions/209484/what-does-it-mean-to-say-that-a-set-is-equipped-with-a-function)
- [How do we formalize the idea of set together with some other operations?](http://math.stackexchange.com/questions/208682/formalizing-the-idea-of-a-set-a-together-with-the-operations-cdot/208758#208758)
- [Are there sets A and B such that A ∈ B and B ∈ A?](http://math.stackexchange.com/questions/676121/are-there-sets-a-and-b-such-that-a-in-b-and-b-in-a)
- [What is the neatest proof that the set of finite subsets of a countable set is countable?](http://math.stackexchange.com/questions/361320/neatest-proof-that-set-of-finite-subsets-is-countable)
- [What is the purpose of the Axiom of Infinity](http://math.stackexchange.com/questions/476076/the-purpose-of-the-sf-zfc-axiom-of-infinity)
- [Why use ZF over NFU?](http://math.stackexchange.com/questions/193198/why-use-zf-over-nfu)
- [Where can I find out about non-wellfounded sets?](https://math.stackexchange.com/questions/4958596/i-am-learning-about-non-well-founded-sets-and-i-wanted-to-know-what-books-everyo/4958827#4958827)
- [Should we be realists about set theory?](http://math.stackexchange.com/questions/836537/set-theoretic-realism/837448#837448)
- [Why doesn’t the independence of the continuum hypothesis immediately imply that ZFC is unsatisfactory?](https://math.stackexchange.com/questions/2622162/why-doesnt-the-independence-of-the-continuum-hypothesis-immediately-imply-that)

## History of Logic

- [Why did the later Frege appeal to geometry to found arithmetic?](http://math.stackexchange.com/questions/685927/building-logic-on-geometry)
- [What does Russell mean when he defines the “Posterity… with respect to the immediate predecessor”?](http://math.stackexchange.com/questions/252608/what-does-russell-mean-when-he-defines-the-posterity-with-respect-to-the-immed)
- [Where, specifically, did Principia Mathematica fail?](http://math.stackexchange.com/questions/460683/where-specifically-did-principia-mathematica-fail)
- [Who first defined the notion of a wff?](http://math.stackexchange.com/questions/203179/origin-of-the-notion-of-a-well-formed-formula/203325#203325)
- [When and where was the concept of valid logic formula was defined?](http://math.stackexchange.com/questions/667377/when-and-where-the-concept-of-valid-logic-formula-was-defined)
- [Was Hilbert trying to eliminate the infinite from maths?](https://math.stackexchange.com/questions/2187518/understanding-hilberts-programme/2188380#2188380)
- [How does Gödel’s theorem impact on Hilbert’s Programme?](https://math.stackexchange.com/questions/2976716/why-godels-theorem-influences-hilberts-programme/2976913#2976913)

## Varia

- [How does logic-for-philosophers relate to mathematical logic?](http://math.stackexchange.com/questions/1180235/logic-in-philosophy-vs-mathematical-logic)
- [What are some good maths/logic study-habits?](http://math.stackexchange.com/questions/191770/what-are-some-good-math-specific-study-habits/191825#191825)
- [How much maths is necessary to understand logic and set theory?](http://math.stackexchange.com/questions/226381/the-maths-necessary-to-understand-logic-model-theory-and-set-theory-to-a-very-h)
- [What are fun but serious mathematics books?](http://math.stackexchange.com/questions/264371/fun-but-serious-mathematics-books-to-gift-advanced-undergraduates)
- [How much math does one need to know to do philosophy of math?](http://math.stackexchange.com/questions/556147/how-much-math-does-one-need-to-know-to-do-philosophy-of-math)
- [Is mathematics a formal game with symbols?](http://math.stackexchange.com/questions/200848/please-help-great-confusion-about-the-two-levels-of-discourse-mathematical-l/201027#201027) [see esp. Henning Makholm’s answer]
- [Are there paradigm shifts in mathematics?](https://math.stackexchange.com/questions/3948302/paradigm-shifts-in-mathematics/3948344#3948344)
- [Should we look to Bourbaki for rigorous foundations of mathematics?](http://math.stackexchange.com/questions/264913/book-on-the-rigorous-foundations-of-mathematics-logic-and-set-theory/265346#265346)
- [What is there to read on the relation between category theory and logic?](https://math.stackexchange.com/questions/2711289/reference-of-the-connection-of-category-theory-and-logicfoundation-of-mathemati/2711473)
- [How might we think about quantification in category-theoretic terms?](http://math.stackexchange.com/questions/467640/categorical-interpretation-of-quantification)
- [What’s an example of a sentence valid in standard second-order logic but not in Henkin semantics?](https://math.stackexchange.com/questions/722011/there-is-a-second-order-sentence-that-is-valid-in-standard-semantics-but-not-val/722113#722113) [see esp. Carl Mummert’s answer]
- [What is the minimal difference between classical and intuitionistic sequent calculus?](http://math.stackexchange.com/questions/561020/minimal-difference-between-classical-and-intuitionistic-sequent-calculus)
