---
title: "The *BML* Study Guide and Book Notes"
---

### Beginning Mathematical Logic

A re-titled, expanded version of my old *Teach Yourself Logic* notes, this is a Study Guide to mathematical logic. It introduces the main topics, and it suggests some suitable texts either for teaching yourself logic by individual self-study or to supplement a university course. (It is book length, but you only need to read the first half-dozen pages to see if this is for you.)

- [Beginning Mathematical Logic: A Study Guide](pdfs/LogicStudyGuide.pdf) [2022 Version]

This version of the *Guide* is also available as a *very* inexpensive paperback direct from Amazon (sorry!) as this minimizes the price for you: ISBN 1916906338.

- [Corrections to 2022 printed version.](pdfs/Corrections_BML.pdf)

NB: I am now starting to work on a 2026  updated version of the *Guide*. So far there are just three revised chapters:

- [New chapter of recommended readings on FOL](pdfs/FOL.pdf)

- [Revised chapter on computable functions, formal arithmetics, and Gödel's theorems](pdfs/Arithcomp.pdf)

- [Revised chapter on proof theory](pdfs/ProofTheory.pdf)

In addition, there is an Appendix to the Guide saying more about some of the Big Books on mathematical logic:

- [Appendix to the Guide](pdfs/Appendix.pdf) (a 79 page PDF, discussing 30 books).

### The Book Notes

The reviews in the *Appendix* are just some of the book notes I have written over recent years. See:

- [Book Notes](/tyl/booknotes/) (a page of links to separate webpages on some 81 books, including those covered in the Appendix)

These webpages range from half-pages to (in one case) a 52 page essay. Most are the equivalent of two or three printed pages!

### A little more about the Study Guide and its Appendix

Most philosophy departments, and many maths departments too, teach little or no serious logic, despite the centrality of the subject. Many students will therefore need to teach themselves, either solo or by organizing study groups. But what to read? Students need annotated reading lists for self-study, giving advice about the available texts. In around 2012, I started the *Teach Yourself Logic* Study Guide, which aimed to provide the needed advice by suggesting some stand-out books on various areas of mathematical logic. NB: it covered *mathematical* logic — so we are working a step up from what’s rudely called “baby logic” (that philosophers may encounter in their first year courses).

The 2022 *Guide* has now been radically rewritten. After a couple of preliminary chapters, Chapters 3 to 9 introduce core topics from the mathematical logic curriculum, and suggest suitable entry-level reading. Chapters 10 and 11 broaden the scope just a bit. And then there is a final Chapter 12 pointing to more advanced texts on the core topics.

Mathematical logic is indeed a big subject, and different people have different backgrounds and/or requirements. So you’ll want detailed advice from which you can work out which books on which areas might be suitable for you. That’s why the Guide is so long. But there are a lot of pointers to help you find your way around.

The recommendations in the *Guide* are organised topic by topic. The *Appendix* then reviews some of the big multi-topic textbooks on mathematical logic book by book.
